dappnode/DNP_DAPPMANAGER

build/src/utils/dependencies.js, build/src/utils/validate.js
Use package name for fs operations
=> fix installation with IPFS

build/src/modules/ipfsCalls.js, build/src/package.json, build/src/utils/generate.test.js
Prevents the app from crashing
=> Verify IPFS hash before downloading

build/src/src/utils/generate.js, build/src/src/utils/generate.test.js
Will later regulate their approval through a user interaction
=> Added support for extra docker-compose features

build/src/src/utils/generate.js, build/src/src/utils/generate.test.js, build/src/src/utils/shell.js
=> Add support for cap_add, cap_drop, network_mode and command

build/src/src/calls/diskSpaceAvailable.js, build/src/src/index.js, build/src/src/utils/shell.js
Call: 'diskSpaceAvailable.dappmanager.dnp.dappnode.eth'
=> Implemented display available size

build/src/src/calls/changeIpfsTimeout.js, build/src/src/calls/index.js, build/src/src/modules/ipfs/ipfsTasks.js, build/src/src/params.js
Timeout set to 30s. Also it is changeable in the fly calling `changeIpfsTimeout.dappmanager.dnp.dappnode.eth` with 
```
kwargs = {
timeout: 20000 // ms
}
=> Increase IPFS timeout

build/src/src/calls/restartPackageVolumes.js, build/src/src/modules/dockerList.js, build/src/src/utils/parse.js, build/src/test/calls/restartPackageVolumes.test.js, build/src/test/calls/updatePackageEnv.test.js
Use different strategy:
- For cores: get the volume list from a `GET /containers/json` docker api call, remove package and up
- For non-cores: docker-compose down --volumes
=> Fix remove volumes

build/src/.eslintrc, build/src/src/calls/installPackage.js, build/src/src/calls/managePorts.js, build/src/src/calls/restartPackage.js, build/src/src/calls/restartPackageVolumes.js, build/src/src/calls/updatePackageEnv.js, build/src/src/modules/docker/Docker.js, build/src/src/modules/docker/dockerSafe.js, build/src/src/modules/docker/index.js, build/src/src/modules/lockPorts.js, build/src/src/modules/unlockPorts.js, build/src/src/utils/merge.js, build/src/test/calls/installPackage.test.js, build/src/test/calls/restartPackage.test.js, build/src/test/calls/restartPackageVolumes.test.js, build/src/test/modules/lockPorts.test.js, build/src/test/modules/unlockPorts.test.js, build/src/test/utils/merge.test.js
- Call `docker-compose up` again if necessary to apply labels immediately
- Allow user to customize ports and vols
=> Random port p2p issues

build/src/src/calls/copyFileFrom.js, build/src/src/calls/copyFileTo.js, build/src/src/eventBus.js, build/src/src/modules/docker/dockerCommands.js, build/src/src/params.js
Dependant on https://github.com/dappnode/DNP_ADMIN/pull/258
=> File Manager: Allow relative paths and dirs

build/src/src/modules/dappGet/aggregate/index.js, build/src/src/modules/dappGet/basic.js, build/src/src/modules/dappGet/index.js, build/src/src/modules/dappGet/utils/shouldUpdate.js, build/src/test/modules/dappGet/basic.test.js
Applies a set of pre-0.2.0 commits that were not merged on the release.
=> Do not downgrade on dappget and dappget basic

build/Dockerfile, build/src/src/calls/copyFileFrom.js
Limit directory size before and after compression,
- 200MB precompresion
- 20MB compressed
Also, compress as .zip
=> Limit from transfers size

build/src/src/calls/passwordChange.js, build/src/src/logUserAction.js
=> Private fields in user action logs

build/src/src/calls/index.js, build/src/src/calls/passwordChange.js, build/src/src/calls/passwordIsSecure.js, build/src/src/index.js, build/src/src/logUserAction.js, build/src/src/modules/passwordManager.js, build/src/src/registerHandler.js, build/src/test/modules/passwordManager.test.js, dappnode_package.json, docker-compose.yml
=> v0.2.6 Release

build/src/src/calls/backupGet.js, build/src/src/params.js, build/src/test/backup.test.int.js
=> Remove file size limit in backup transfers

build/Dockerfile, build/src/src/calls/index.js, build/src/src/calls/poweroffHost.js, build/src/src/calls/rebootHost.js, dappnode_package.json
`poweroffHost` and `rebootHost` via `dbus-send`
=> add Reboot and Poweroff

build/src/src/calls/installPackage.js, build/src/src/calls/poweroffHost.js, build/src/src/calls/rebootHost.js, build/src/src/modules/passwordManager.js, build/src/src/utils/getDappmanagerImage.js, build/src/test/modules/passwordManager.test.js
=> Use side container for power

build/src/src/calls/fetchDirectory.ts, build/src/src/watchers/chains/bitcoin.ts, build/src/test/watchers/chains/bitcoin.test.ts, dappnode_package.json, docker-compose.yml
- Add try / catch block on each release fetch in fetchDirectory
- Generalize bitcoin chain driver to support forks
=> v0.2.12 Release

build/Dockerfile, build/rndc.conf, build/src/package.json, build/src/src/initializeDb.ts, build/src/yarn.lock, build/update_local_dyndns.sh
this pull request helps resolve the dyndns domain from the local network
=> Install bind, add rndc.conf and update_local_dyndns

build/src/src/db/index.ts, build/src/src/db/systemFlags.ts, build/src/src/index.ts, build/src/src/modules/docker/listContainers.ts, build/src/src/types.ts, build/src/test/fetchExternalData.test.int.ts, build/src/test/modules/docker/listContainers.test.ts, dappnode_package.json
* hotfix_volume_info: Return legacy volume info properties for admin compatibility
* hotfix_envs_migrate: Fix envs migration error on certain cases
=> v0.2.19 Release

build/src/hostScripts/detect_fs.sh, build/src/src/calls/fetchDnpRequest.ts, build/src/src/calls/index.ts, build/src/src/calls/listPackages.ts, build/src/src/calls/mountpointsGet.ts, build/src/src/calls/restartPackageVolumes.ts, build/src/src/calls/volumeRemove.ts, build/src/src/calls/volumesGet.ts, build/src/src/index.ts, build/src/src/modules/docker/dockerApi.ts, build/src/src/modules/docker/getHostVolumeSizes.ts, build/src/src/modules/hostScripts/runScripts.ts, build/src/src/modules/upnpc/list.ts, build/src/src/modules/upnpc/parseGeneralErrors.ts, build/src/src/modules/upnpc/parseListOutput.ts, build/src/src/registerSubscriptions.ts, build/src/src/route-types/fetchDirectory.ts, build/src/src/route-types/fetchDnpRequest.ts, build/src/src/route-types/index.ts, build/src/src/route-types/listPackages.ts, build/src/src/route-types/mountpointsGet.ts, build/src/src/route-types/passwordChange.ts, build/src/src/route-types/restartPackageVolumes.ts, build/src/src/route-types/subscriptionVolumes.ts, build/src/src/route-types/volumeRemove.ts, build/src/src/route-types/volumesGet.ts, build/src/src/schemas.ts, build/src/src/types.ts, build/src/test/modules/upnpc/parseListOutput.test.ts, build/src/test/testUtils.ts
Depends on https://github.com/dappnode/DNP_ADMIN/pull/397
=> Manage volumes feature

build/src/src/calls/listPackages.ts, build/src/src/modules/docker/listContainers.ts, build/src/src/utils/configFiles.ts, build/src/test/modules/docker/dockerApiSamples/containers.ts, build/src/test/modules/docker/listContainers.test.ts
- Fix an issue that prevented from reading a package ENVs if the manifest was missing
- Fix an issue showing mandatory core package's ports as deletable.
=> Fix issues found during final testing of v0.2.24

build/src/hostScripts/migrate_volume.sh, build/src/src/modules/hostScripts/runScripts.ts
Extends https://github.com/dappnode/DNP_DAPPMANAGER/pull/322
=> Check all migrate_volume arguments

build/src/src/calls/logPackage.ts, build/src/src/httpApi/index.ts, build/src/src/modules/docker/dockerApi.ts, build/src/src/modules/docker/dockerCommands.ts
=> Support very large container logs

build/src/src/db/systemFlags.ts, build/src/src/index.ts, build/src/src/modules/docker/restartPatch.ts, build/src/src/modules/hostScripts/copyScripts.ts, build/src/src/modules/installer/postCoreUpdate.ts, build/src/src/params.ts
- Makes sure the DAPPMANAGER is at the correct version after updating itself. Addresses a race condition that may happen with the restart-patch container
=> Post core update

build/src/src/calls/fetchCoreUpdateData.ts, build/src/src/db/ethClient.ts, build/src/src/modules/docker/listContainers.ts, build/src/src/modules/ethClient/changeEthMultiClient.ts, build/src/src/modules/ethClient/migrateEthchain.ts, dappnode_package.json, docker-compose.yml
- Make sure coreRelease is defined in fetchCoreUpdateData
- Tolerate same target on changeEthMultiClient
- Persist settings of the ethchain during the eth client migration
- Make sure container name is the exact query on listContainer
=> v0.2.27 Release

build/src/src/modules/release/getRelease.ts, build/src/src/modules/release/parsers/index.ts, build/src/src/types.ts, build/src/src/utils/format.ts, build/src/test/modules/release/parsers/index.test.ts, build/src/test/utils/format.test.ts
Trigger with 
```js
manifest = {
...
ssl: true
}
```
=> Add package subdomain to compose if manifest.ssl = true

build/src/src/modules/legacy/removeLegacyBindVolume.ts, build/src/src/params.ts, build/src/src/watchers/nsupdate/index.ts, dappnode_package.json, docker-compose.yml
- Remove new and old legacy bind volume
- When the BIND is re-created, run nsupdate on all domains
- Bump versions
=> Bind hotfix - Remove new and old legacy bind volume

build/src/src/ethForward/index.ts, dappnode_package.json, docker-compose.yml, releases.json
- Change req.host sent to IPFS to prevent triggering the DNSLink
=> v0.2.32 Release

packages/admin-ui/src/components/SetupWizard/index.tsx, packages/admin-ui/src/pages/packages/actions.ts, packages/admin-ui/src/pages/packages/components/Config.tsx
- Disable config update button if user settings are equal
- Improve the toast text when updating a package config
=> Improve package config UX

packages/admin-ui/package.json, packages/admin-ui/src/api/index.ts, packages/admin-ui/src/api/utils.ts, yarn.lock
Current PubSub doesn't work on webkit based browsers
=> Use cross-browser safe pubsub module

dappnode_package.json, docker-compose.yml, packages/admin-ui/package.json, packages/admin-ui/src/api/index.ts, packages/admin-ui/src/api/utils.ts, yarn.lock
- Fix bug crashing the UI on Safari browsers #407
=> v0.2.34 Release

packages/admin-ui/src/api/index.ts, packages/admin-ui/src/common/transport/jsonRpc/index.ts, packages/admin-ui/src/common/transport/types.ts, packages/dappmanager/src/api/index.ts
Browsers timeout long requests, which happen on the installation of heavy DAppNode packages
=> Do ADMIN's JSON RPC requests over socket.io

packages/dappmanager/src/modules/docker/dockerCommands.ts
Added timeout parameter to functions:
- dockerComposeUp
- dockerComposeDown
- dockerComposerm
- dockerComposeStop
Added time parameter to functions:
- dockerStop
=> Added timeout option to docker, docker-compose commands

packages/admin-ui/src/common/types.ts, packages/dappmanager/package.json, packages/dappmanager/src/modules/compose/labelsDb.ts, packages/dappmanager/src/modules/installer/getInstallerPackageData.ts, packages/dappmanager/src/modules/release/getRelease.ts, packages/dappmanager/src/utils/timeout.ts, packages/dappmanager/test/utils/timeout.test.ts, yarn.lock
**Changes:**
- Added `parseTimeout()` function.
- Called `parseTimeout()` function where needed (getInstallerPackageData)
- New unit test for testing the function.
- Added new functionality to `parseTimeout()` function: returns undefined when the parameter is undefined.
=> Added parseTimeout function and unit test for that function

packages/dappmanager/src/api/index.ts, packages/dappmanager/src/api/routes/containerLogs.ts, packages/dappmanager/src/api/routes/packageManifest.ts, packages/dappmanager/src/api/routes/publicPackagesData.ts
Will be used by the DMS to query the monitoring files
=> Expose package manifest public endpoint

packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/dashboard/components/HostStats.tsx, packages/admin-ui/src/pages/support/components/Report.tsx, packages/admin-ui/src/pages/support/formaters/autoDiagnoseTexts.ts, packages/dappmanager/src/calls/statsCpuGet.ts, packages/dappmanager/src/calls/statsDiskGet.ts, packages/dappmanager/src/calls/statsMemoryGet.ts, packages/dappmanager/src/utils/parseDiskStats.ts, packages/dappmanager/src/utils/parseMemoryStats.ts, packages/dappmanager/src/utils/toBytes.ts, packages/dappmanager/test/utils/parseDiskStats.test.ts, packages/dappmanager/test/utils/parseMemoryStats.test.ts
**Change disk commmand**
`df / --block-size=1`   --->   ` df / -B 1`
**Solved spelling mistake in HostStats.**
Switch disk and memory
=> Fixed hostStats problems

packages/dappmanager/src/watchers/ethMultiClient/index.ts, packages/dappmanager/test/watchers/ethMultiClient/index.test.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/431
=> Set fullnode.dappnode domain even if package is already installed

packages/dappmanager/src/modules/docker/dockerCommands.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/454
=> Fix order of docker-compose command arguments

dappnode_package.json, docker-compose.yml, packages/admin-ui/server-mock/methods/pending.ts, packages/admin-ui/server-mock/methods/volumes.ts, packages/admin-ui/src/common/routes.ts, packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/support/components/AutoDiagnose.tsx, packages/admin-ui/src/pages/support/formaters/autoDiagnoseTexts.ts, packages/dappmanager/src/calls/index.ts, packages/dappmanager/src/calls/ipPublicGet.ts, packages/dappmanager/src/calls/packageRemove.ts, packages/dappmanager/src/calls/packageStartStop.ts, packages/dappmanager/src/modules/compose/unsafeCompose.ts, packages/dappmanager/src/modules/docker/dockerCommands.ts, packages/dappmanager/src/params.ts, packages/dappmanager/src/utils/getPublicIpFromUrls.ts, packages/dappmanager/test/integration/releaseFormat.test.int.ts, packages/dappmanager/test/modules/compose/unsafeCompose.test.ts, packages/dappmanager/test/modules/compose/userSettings.test.ts
- Fix bug preventing the restart of individual packages. Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/454
- Prevent stopping sensitive core packages
- Set default restart policy to unless-stopped
=> v0.2.37 Release

packages/admin-ui/src/services/dappnodeStatus/selectors.ts
Fixes https://github.com/dappnode/DAppNode/issues/197
=> Show internal IP in dappnode top right menu

packages/dappmanager/src/watchers/natRenewal/index.ts
**Changes**
1. The localIP global env variable will be refreshed using the watcher: "natRenewal".
=> Refresh ip vpn

packages/admin-ui/src/api/auth.ts, packages/admin-ui/src/components/Button.tsx, packages/admin-ui/src/components/Input.tsx, packages/admin-ui/src/components/InputForm.tsx, packages/admin-ui/src/components/input.css, packages/admin-ui/src/components/navbar/dropdownMenus/Profile.tsx, packages/admin-ui/src/components/welcome/features/ChangeHostPassword.tsx, packages/admin-ui/src/dappnode_colors.css, packages/admin-ui/src/pages/system/components/Profile/ChangePassword.tsx, packages/admin-ui/src/pages/system/components/Profile/SignOut.tsx, packages/admin-ui/src/pages/system/components/Security/ChangeHostUserPassword.tsx, packages/admin-ui/src/pages/system/components/Security/ChangeWifiPassword.tsx, packages/admin-ui/src/start-pages/Login.tsx, packages/admin-ui/src/start-pages/Register.tsx, packages/admin-ui/src/start-pages/ResetPassword.tsx
From https://youtu.be/alGcULGtiv8
- Use form label input button markup
- Use button type submit to trigger validation
- Use autofocus
- Use name and autocomplete for browser password suggestions
- Use require for built-in HTML validation
=> Apply Sign-in form best practices

packages/admin-ui/src/common/types.ts, packages/dappmanager/src/modules/compose/unsafeCompose.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/499
=> Allow compose service extra_hosts prop

packages/admin-ui/src/pages/support/components/Report.tsx
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/509
=> Show diskUsedPercentage in Report

packages/dappmanager/src/calls/packageRemove.ts, packages/dappmanager/src/calls/packageRestartVolumes.ts, packages/dappmanager/src/calls/packageStartStop.ts, packages/dappmanager/src/modules/chains/drivers/bitcoin.ts, packages/dappmanager/src/modules/docker/api/container.ts, packages/dappmanager/src/modules/docker/api/index.ts, packages/dappmanager/src/modules/docker/api/volume.ts, packages/dappmanager/src/modules/docker/api/volumeInspect.ts, packages/dappmanager/src/modules/docker/cli.ts, packages/dappmanager/src/modules/docker/index.ts, packages/dappmanager/src/modules/docker/removeNamedVolume.ts, packages/dappmanager/src/modules/ethClient/migrateEthchain.ts, packages/dappmanager/src/modules/installer/restartPatch.ts, packages/dappmanager/src/modules/legacy/index.ts, packages/dappmanager/test/calls/packageRemove.test.ts, packages/dappmanager/test/dockerAutoUpdate/dockerAutoUpdate.test.int.ts, packages/dappmanager/test/integration/dnpLifecycle.test.int.ts
- Replace docker shell commands with calls to the docker API
=> Use docker API instead of CLI

packages/admin-ui/server-mock/data/dnps/bitcoin.ts, packages/admin-ui/server-mock/methods/pending.ts, packages/admin-ui/src/components/Columns.tsx, packages/admin-ui/src/components/columns.scss, packages/admin-ui/src/pages/packages/components/Backup/Download.tsx, packages/admin-ui/src/pages/packages/components/Backup/Restore.tsx, packages/admin-ui/src/pages/packages/components/Backup/backup.scss, packages/admin-ui/src/pages/packages/components/Backup/index.tsx, packages/admin-ui/src/pages/packages/components/packages.scss
Fixes https://github.com/dappnode/dnp_dappmanager/issues/517
=> Add security or notice when downloading a backup

README.md
Added information for the current developing modes in the dappmanager.
=> Document developing modes

packages/dappmanager/src/daemons/diskUsage/index.ts
Print stopped containers as a markdown list instead of inlined separated by commas.
**Before**
(geth.dnp.dappnode.eth, ipfs.dnp.dappnode.eth)
**Now**
- geth.dnp.dappnode.eth
- ipfs.dnp.dappnode.eth
=> Format disk usage notification

packages/admin-ui/src/__mock-backend__/data/dnps/multiService.ts, packages/admin-ui/src/components/InputSecret.tsx, packages/admin-ui/src/components/navbar/navbarItems.ts, packages/admin-ui/src/pages/packages/components/ServiceSelector.tsx, packages/admin-ui/src/pages/packages/components/StateBadge/utils.ts, packages/admin-ui/src/pages/system/components/Notifications/index.tsx, packages/admin-ui/src/params.ts, packages/dappmanager/package.json, packages/dappmanager/src/api/helmet.ts, packages/dappmanager/src/api/startHttpApi.ts, packages/dappmanager/src/daemons/telegramBot/commands.ts, packages/dappmanager/src/params.ts, yarn.lock
=> Release fixes

packages/admin-ui/src/pages/devices/components/DevicesHome.tsx
Reversed the message, before was throwing the opposite message when making/removing as admin
=> Reverse message

packages/admin-ui/src/components/SetupWizard/SelectMountpoint.tsx, packages/admin-ui/src/components/welcome/Finished.tsx, packages/admin-ui/src/pages/support/components/Report.tsx, packages/admin-ui/src/pages/system/components/Notifications/index.tsx, packages/admin-ui/src/params.ts, packages/admin-ui/src/start-pages/NoConnection.tsx
- Move all URLs to params file for better maintainability
- Adds guide to setup Telegram https://forum.dappnode.io/t/816
=> Move all URLs to params file +  add telegram guide

packages/admin-ui/src/api/index.ts, packages/admin-ui/src/api/rpc.ts, packages/admin-ui/src/api/utils.ts, packages/admin-ui/src/common/transport/socketIo/index.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/564. Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/583
=> Fix broken events in UI

packages/dappmanager/src/modules/compose/unsafeCompose.ts, packages/dappmanager/test/modules/compose/unsafeCompose.test.ts, packages/dappmanager/test/modules/releaseSpecs/sample-core/docker-compose.parsed.yml, packages/dappmanager/test/modules/releaseSpecs/sample-core/docker-compose.yml
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/618
=> Allow to declare extra networks

packages/dappmanager/src/modules/installer/loadImages.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/455
=> Fix image loading percent for multi-service packages

packages/admin-ui/src/common/types.ts, packages/dappmanager/src/modules/compose/unsafeCompose.ts, packages/dappmanager/src/modules/compose/userSettings.ts, packages/dappmanager/src/modules/installer/createVolumeDevicePaths.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/606
=> docker-compose volume may be null

packages/admin-ui/src/__mock-backend__/httpsPortal.ts, packages/admin-ui/src/common/routes.ts, packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/system/components/Network/HttpsMappings.tsx, packages/admin-ui/src/pages/system/components/Network/https-mapping.scss, packages/admin-ui/src/pages/system/components/Network/index.tsx, packages/admin-ui/src/pages/system/components/SystemRoot.tsx, packages/admin-ui/src/pages/system/data.ts, packages/dappmanager/src/calls/httpsPortal.ts, packages/dappmanager/src/modules/https-portal/getExposableServices.ts, packages/dappmanager/src/modules/https-portal/index.ts
=> Add easier HTTPs Portal UI in system

packages/admin-ui/src/__tests__/pages/installer/parsers/setupWizardParser.test.ts, packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/installer/parsers/formDataParser.ts
Same as https://github.com/dappnode/DNP_DAPPMANAGER/pull/647
=> Share variables with multiples services

packages/dappmanager/package.json, packages/dappmanager/src/modules/docker/api/network.ts, packages/dappmanager/src/modules/https-portal/index.ts, packages/dappmanager/src/modules/https-portal/migration.ts, yarn.lock
- Updated @types/dockerode library
- Refactor types `network.ts`
- Edited `dockerNetworkConnect()` function
- Fix `dockerNetworkConnect()` function calls
=> Fix docker-aliases 

packages/dappmanager/src/modules/dockerUpdate/params.ts
=> Fix Debian distro name typo

.github/workflows/build-core.yml, .github/workflows/main.yml, Dockerfile
Version 10 will stop being maintained this month https://nodejs.org/en/about/releases/
=> Bump to Node 12 LTS

packages/dappmanager/package.json, packages/dappmanager/src/ethForward/utils/decodeContentHash.ts, yarn.lock
Get upstream types finally :tada:
=> Bump multihashes

packages/admin-ui/src/pages/packages/components/FileManager/index.tsx
Fixes a visual bug introduced by https://github.com/dappnode/DNP_DAPPMANAGER/pull/678
=> Fix service selector view

packages/admin-ui/src/__mock-backend__/data/dnps/bitcoin.ts, packages/admin-ui/src/__mock-backend__/data/sample.ts, packages/admin-ui/src/common/types.ts, packages/admin-ui/src/components/Button.tsx, packages/admin-ui/src/components/NotificationsMain.tsx, packages/admin-ui/src/pages/packages/components/AlertPackageUpdateAvailable.tsx, packages/admin-ui/src/pages/packages/pages/ById.tsx, packages/dappmanager/src/calls/packageGet.ts, packages/dappmanager/src/daemons/autoUpdates/sendUpdateNotification.ts, packages/dappmanager/src/db/package.ts, packages/dappmanager/src/modules/dappGet/utils/shouldUpdate.ts
- Uses existing auto-updates daemon to persist the latest known version to db
- When loading a package checks that version to conditionally show this banner
- The "Update" button redirects to the install package
=> Show should update banner in package view

packages/admin-ui/src/pages/support/components/PortsStatusTable.tsx, packages/admin-ui/src/services/dnpDirectory/selectors.ts, packages/dappmanager/src/calls/fetchDnpRequest.ts, packages/dappmanager/src/calls/portsStatusGet.ts, packages/dappmanager/src/modules/compose/ports.ts, packages/dappmanager/src/modules/compose/userSettings.ts, packages/dappmanager/src/modules/upnpc/parseOpenOutput.ts
After reviewing the entire codebase due to https://github.com/dappnode/DNP_DAPPMANAGER/pull/690 some return statements style didn't match the standard of the codebase.
=> Review return statement styling consistency

packages/dappmanager/src/domains.ts, packages/dappmanager/src/modules/compose/unsafeCompose.ts, packages/dappmanager/test/modules/releaseSpecs/prysm/docker-compose.parsed.yml
Closes https://github.com/dappnode/DNP_DAPPMANAGER/issues/704
=> Add mainService rootAlias logic to docker DNS

packages/admin-ui/src/__mock-backend__/httpsPortal.ts, packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/system/components/Network/HttpsMappings.tsx, packages/dappmanager/src/calls/httpsPortal.ts, packages/dappmanager/src/domains.ts, packages/dappmanager/src/modules/https-portal/exposable/parseExposable.ts, packages/dappmanager/src/modules/https-portal/exposable/predefined.ts, packages/dappmanager/test/modules/https-portal/exposable.test.ts
Allows packages to declare multiple services
=> Add custom fromSubdomain field

Dockerfile, packages/dappmanager/src/daemons/avahi/index.ts, packages/dappmanager/src/daemons/index.ts, packages/dappmanager/src/params.ts
This PR may not be merged into this release.
Closes https://github.com/dappnode/DNP_DAPPMANAGER/issues/669
=> Add avahi-publish

packages/admin-ui/src/pages/packages/components/Network/HttpsMappings.tsx, packages/admin-ui/src/pages/system/components/Network/HttpsMappings.tsx
=> Re-order HTTPs Portal view: data, error, loading

packages/dappmanager/src/modules/https-portal/apiClient.ts
Fixes a regression introduced by https://github.com/dappnode/DNP_DAPPMANAGER/pull/718
=> Run schema validator on in HTTPs Portal list method

packages/dappmanager/src/domains.ts, packages/dappmanager/src/modules/https-portal/exposable/parseExposable.ts, packages/dappmanager/src/modules/https-portal/exposable/predefined.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/724
=> Fix nethermind exposable service

packages/dappmanager/src/daemons/avahi/index.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/721
=> Don't run avahi-publish on VPS

packages/dappmanager/src/daemons/avahi/index.ts
=> Skip avahi-daemon

packages/admin-ui/src/pages/packages/components/Info/RemovePackage.tsx
Replace isCore with notRemovable
=> Allow to remove notRemovable packages

.github/workflows/netlify.yml, README.md, packages/admin-ui/src/__mock-backend__/index.ts
- There should be deployed a site on every PR against v0.something branches
- There should be deployed a site on every PR against master branch
=> Testing Netlify

packages/admin-ui/src/pages/dashboard/components/ChainCard.tsx
Changes of chain card when error
- Add package logs path as Link
- CHange from danger to warning
=> Added package logs link and changed chaind card color

packages/dappmanager/src/params.ts
- Added local domain to https cors
- Use vpn alias instead of ip
=> Use of aliases instead of ips

packages/admin-ui/src/__mock-backend__/wireguard.ts, packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/vpn/components/openvpn/OpenVpnDeviceDetails.tsx, packages/admin-ui/src/pages/vpn/components/openvpn/OpenVpnDevicesHome.tsx, packages/admin-ui/src/pages/vpn/components/wireguard/WireguardDeviceDetails.tsx, packages/admin-ui/src/pages/vpn/components/wireguard/WireguardDevicesHome.tsx, packages/admin-ui/src/pages/vpn/components/wireguard/wireguard.scss, packages/admin-ui/src/pages/vpn/data.ts, packages/dappmanager/src/modules/wireguard/client.ts, packages/dappmanager/src/params.ts
Serve two configuration files:
- Remote
- Local
Todo: 
Deppends on: https://github.com/dappnode/DNP_WIREGUARD/pull/10
=> Wireguard multiple endpoints

packages/dappmanager/src/ethForward/index.ts
Remove typo introduced in https://github.com/dappnode/DNP_DAPPMANAGER/pull/762
=> Remove console trace

packages/admin-ui/src/common/routes.ts, packages/admin-ui/src/pages/wifi/components/localProxying/LocalProxying.tsx, packages/admin-ui/src/params.ts, packages/dappmanager/hostScripts/avahi_daemon.sh, packages/dappmanager/src/calls/localProxy.ts, packages/dappmanager/src/daemons/index.ts, packages/dappmanager/src/index.ts, packages/dappmanager/src/modules/hostScripts/scripts/avahiDaemon.ts, packages/dappmanager/src/params.ts
- Relocate avahi daemon startup
- Remove unnecesary revalidate
=> Avahi fixes

packages/dappmanager/src/modules/wireguard/client.ts
Otherwise in the server returns code 404 for another reason we will never know
=> Log full body in wireguard 404 error

packages/dappmanager/src/modules/wireguard/client.ts, packages/dappmanager/src/params.ts
Deppends on https://github.com/dappnode/DNP_WIREGUARD/pull/15/files
=> Wireguard api refactor

packages/dappmanager/src/modules/chains/drivers/ethereum2Prysm.ts
Updates Prysm API client to handle snake_case capitalization.
Fixes
=> Update Prysm API client

docker-compose.yml, packages/dappmanager/src/domains.ts, packages/dappmanager/src/params.ts, packages/dappmanager/test/modules/releaseSpecs/dappmanager/docker-compose.parsed.yml
@3alpha @pablomendezroyo  Do we want to add this?
=> Add .local alias

packages/admin-ui/server-mock/index.ts, packages/admin-ui/src/api/interface.ts, packages/admin-ui/src/api/mock/routes.ts, packages/admin-ui/src/api/routes/index.ts, packages/admin-ui/src/pages/vpn/components/openvpn/OpenVpnDeviceDetails.tsx, packages/admin-ui/src/pages/vpn/components/wireguard/WireguardDeviceDetails.tsx, packages/admin-ui/src/params.ts, packages/dappmanager/src/api/routes/downloadWireguardConfig.ts, packages/dappmanager/src/api/routes/index.ts, packages/dappmanager/src/api/startHttpApi.ts
- Modified help text
- Add new apiRoute to serve files to the user
=> Improve Wireguard UIX

packages/dappmanager/src/daemons/natRenewal/index.ts, packages/dappmanager/src/daemons/nsupdate/index.ts, packages/dappmanager/src/utils/asyncFlows.ts
Partially addresses https://github.com/dappnode/DNP_DAPPMANAGER/issues/806
=> Run UPnP more frequently on start

packages/dappmanager/src/initializeDb.ts
Closes https://github.com/dappnode/DNP_DAPPMANAGER/issues/807
=> Disable local proxying if exposed to the public internet

packages/admin-ui/src/components/LinkDocs.tsx, packages/admin-ui/src/pages/community/components/DiscordActions.tsx, packages/admin-ui/src/pages/community/components/DiscourseActions.tsx, packages/admin-ui/src/pages/community/components/GithubActions.tsx, packages/admin-ui/src/pages/community/components/GrantsActions.tsx, packages/admin-ui/src/pages/community/components/TreasuryActions.tsx, packages/admin-ui/src/pages/system/components/Network/index.tsx, packages/admin-ui/src/pages/system/components/Peers/index.tsx, packages/admin-ui/src/pages/vpn/components/VpnHome.tsx, packages/admin-ui/src/pages/vpn/components/wireguard/WireguardDeviceDetails.tsx, packages/admin-ui/src/pages/wifi/components/localProxying/LocalProxying.tsx, packages/admin-ui/src/pages/wifi/components/wifi/WifiStatus.tsx, packages/admin-ui/src/start-pages/ResetPassword.tsx
- Create component for DocsUrls links since are used in a lot of parts in the UI
- Open in new tab for external links in docs and community actions
=> Docs URLs links and other links

.github/CODEOWNERS
According to this issue dappnode/DAppNode#334
=> Fix the codeowner file location

packages/admin-ui/src/pages/system/components/Advanced/DockerUpdate/DockerCompose.tsx, packages/admin-ui/src/pages/system/components/Advanced/DockerUpdate/DockerEngine.tsx, packages/admin-ui/src/pages/system/components/Security/securityUpdate/HostSecurityUpdate.tsx
use warning instead og warming
=> fix typo in warning

.github/workflows/main.yml
There was a typo to check input from developer on release workflow
=> Fix typo in release workflow

packages/dappmanager/.env, packages/dappmanager/package.json, packages/dappmanager/test/integration/.mocharc.yaml, packages/dappmanager/test/integration/hook.ts, packages/dappmanager/test/testIpfsUtils.ts
- Setup local IPFS node for int tests
- Use of mocha root hooks
- Set down local IPFS node after int tests
=> setup local ipfs node for int tests

packages/admin-ui/src/pages/dashboard/components/ChainCard.tsx, packages/dappmanager/src/modules/chains/index.ts
Now the chain cards that are in the dashboard are ordered by name.
#841
=> Adding a sort function to the chaincards

packages/admin-ui/src/pages/system/components/Hardware/Lvm.tsx, packages/admin-ui/src/pages/system/components/Notifications/Telegram.tsx, packages/admin-ui/src/pages/system/components/Repository/Ipfs.tsx, packages/admin-ui/src/params.ts
- Reorg forum URLs
- Added forum URLs for: IPFS remote and expand host filesystem with storage device
=> Added forum docs for new release

packages/admin-ui/src/pages/system/components/Hardware/Lvm.tsx
Warn users about the danger of extending host filesystem with LVM
=> Added disclaimer to LVM

packages/dappmanager/src/modules/release/getRelease.ts, packages/dappmanager/src/params.ts
Fix typo in `coreFromForeignRegistry`
=> Hot fix that prevent from update core packages from the UI

.github/workflows/netlify.yml, packages/dappmanager/test/integration/backup.test.int.ts, packages/dappmanager/test/integration/fetchRelease.test.int.ts, packages/dappmanager/test/integration/releaseFormat.test.int.ts, packages/dappmanager/test/integrationSpecs/testReleaseUtils.ts, packages/dappmanager/test/testIpfsUtils.ts, packages/dappmanager/test/testUtils.ts
Fix integration tests, clean residual volumes
=> Fix integration tests and Netlify build

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/params.ts, packages/dappmanager/src/params.ts
Migration to the new IPFS gateway URL
=> Changed IPFS gateway endpoints

packages/dappmanager/src/modules/https-portal/index.ts
=> Adding external network to DNP_HTTPS compose file on first mapping

packages/admin-ui/src/pages/installer/components/Steps/Info.tsx
=> Disable updated button

packages/admin-ui/src/common/types.ts, packages/dappmanager/src/modules/chains/drivers/ethereum2.ts, packages/dappmanager/src/modules/chains/drivers/index.ts, packages/dappmanager/src/modules/chains/getChainDriverName.ts, packages/dappmanager/src/modules/compose/labelsDb.ts, packages/dappmanager/test/modules/compose/labelDb.test.ts
Build base URL of the beaconchain node dynamically, based on port and service name defined in the manifest
=> Build beaconchain base URL dynamically

packages/admin-ui/src/pages/vpn/components/wireguard/WireguardDeviceDetails.tsx
- Fixes copy config button: https://github.com/dappnode/DNP_DAPPMANAGER/issues/862
=> Fix copy wireguard button 

packages/admin-ui/src/common/types.ts, packages/dappmanager/src/modules/compose/unsafeCompose.ts
- Docs: https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
- Example of usage https://github.com/dappnode/DAppNodePackage-web3signer-prater/blob/3dceb188aaa3906fc8b22e10284df62939eae9b0/docker-compose.yml#L24
=> docker compose healthcheck support 

packages/dappmanager/src/modules/installer/ensureIsNotValidatorLegacyPackage.ts
Related to https://github.com/dappnode/DNP_DAPPMANAGER/pull/980#discussion_r821318445
=> use for each instead of map

packages/dappmanager/src/calls/packageInstall.ts, packages/dappmanager/src/modules/installer/ensureEth2MigrationRequirements.ts
Bypass rollback if client legacy to ensure always move forward
=> Bypass rollback if client legacy

packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx, packages/admin-ui/src/pages/installer/components/Steps/Warnings.tsx
Setup installer warnings for:
- Update (minor/major/patch)
- Installation
=> Implement installation and updates warnings in installer

packages/dappmanager/src/modules/installer/exposeByDefaultHttpsPorts.ts
Only do the HTTPs mapping if the mapping does not exist already, otherwise there will be an error
=> Expose default HTTPs ports if dont already exist

packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx, packages/admin-ui/src/pages/installer/components/Steps/Warnings.tsx
Fix showing navigation buttons when installing package and warnings available. Only show onInstall warnings
=> Fix warning buttons

packages/dappmanager/src/modules/https-portal/exposable/predefined.ts
Fixing Monero predefined exposable port.
=> Changed Monero predefined exposable port

packages/dappmanager/package.json, yarn.lock
Fix dependabot alert https://github.com/dappnode/DNP_DAPPMANAGER/security/dependabot/213
Update ipfs-car dependency
Test ipfs remote:
- Dappstore
- Instal package lifecycle
=> update ipfs-car dependency

package.json, packages/admin-ui/package.json, packages/admin-ui/src/api/subscriptions.ts, packages/admin-ui/tsconfig.json, packages/dappmanager/package.json, yarn.lock
Update typescript dependencies in either: dappmanager and adminui, this has required the following changes:
- Use of `"useUnknownInCatchVariables": false,` in adminUi `tsconfig.json`
- Update of `ts-node` dependency in root and dappmanager 
- Update of `@typescript-eslint/eslint-plugin` dependency
Research for breaking changes:
- https://github.com/Microsoft/TypeScript/releases
- https://github.com/microsoft/TypeScript/wiki/Breaking-Changes
=> update typescript dependency in adminui and dappmanager

packages/dappmanager/src/modules/https-portal/utils/exposeByDefaultHttpsPorts.ts
When installing/updating a dappnode package with portal mappings, if these portal mapping already exists in the HTTPS there will be thrown an error, not allowing to install/update such package
Bypass the error if the HTTPS already contains the portal mapping  that the dappnode package to be installed/updated requires.
Create a portal mapping for a dappnode package, try to update it and make sure that it is allowed to update it even if the HTTPS portal mapping already exists. Use the `exposable` feature from the manifest
=> Bypass error if mapping already exists

packages/dappmanager/src/modules/installer/ensureEth2MigrationRequirements.ts, packages/dappmanager/test/integration/ensureEth2MigrationRequirements.test.int.ts
Installing web3signer should be allowed to be installed when it is installed as a dependency and the Prysm Legacy is been updated to a non-legacy version
Do not throw error when this situation matches
Having Prysm legacy installed, try to update it to a non-legacy version with web3signer as a dependency. It should be allowed
=> Allow installing web3signer if it is a Prysm legacy update

packages/admin-ui/src/pages/installer/components/Steps/Warnings.tsx
=> fixed update warning headers

packages/admin-ui/src/pages/packages/components/Backup/Download.tsx
Fixed #1082
> Typo
> Replace "in you local" by "in your local"
=> Fix #1082 Typo

packages/dappmanager/src/modules/docker/api/container.ts
Implement docker kill API call
=> implement docker kill

packages/admin-ui/src/pages/packages/components/Info/Links.tsx
=> Display EngineAPI same as QueryingAPI

packages/admin-ui/src/components/confirmDialog.scss
Increase the maximum size of the `Confirm` react component
=> Implement a bigger confirm dialog

packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts
There was a bug when creating the `userSettings` object. It must be different deppending on the packages that are multiservice and monoservice
=> Fix creation of userSettings when setting a new staker configuration

packages/admin-ui/src/components/confirmDialog.scss
Increase the max size of the component `Confirm`
=> Increase confirm component size

.github/workflows/netlify.yml
Update the ubuntu workflow image used to create netlify builds
=> update ubuntu to latest

.github/workflows/main.yml
Create releases on master branch instead of develop
=> Create release on master branch

packages/dappmanager/src/modules/compose/setDappnodeComposeDefaults.ts, packages/dappmanager/test/modules/compose/setDappnodeComposeDefaults.test.ts, packages/dappmanager/test/modules/releaseSpecs/dappmanager/docker-compose.parsed.yml, packages/dappmanager/test/modules/releaseSpecs/prysm/docker-compose.parsed.yml, packages/dappmanager/test/modules/releaseSpecs/sample-core/docker-compose.parsed.yml, packages/dappmanager/test/modules/releaseSpecs/vpn/docker-compose.parsed.yml
Default memory limit has been giving us more trouble then it solved issues so we should remove it.
=> Delete default limit

packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/stakers/components/AdvanceView.tsx, packages/dappmanager/src/daemons/stakerConfig/index.ts, packages/dappmanager/src/db/dyndns.ts, packages/dappmanager/src/db/interceptGlobalEnvOnSet.ts, packages/dappmanager/src/db/network.ts, packages/dappmanager/src/db/stakerConfig.ts, packages/dappmanager/src/db/system.ts, packages/dappmanager/src/db/upnp.ts, packages/dappmanager/src/modules/stakerConfig/setDefaultStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts
Add types to `interceptGlobalEnvsOnSet`
=> Add typings to interceptGlobalEnvsOnSet

packages/admin-ui/package.json, packages/dappmanager/package.json, yarn.lock
Update the @dappnodesdk dependency to v0.2.56
=> Update dappnodesdk dependency to v0.2.56

packages/admin-ui/src/__mock-backend__/stakerConfig.ts, packages/admin-ui/src/pages/stakers/components/AdvanceView.tsx, packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx
Set defaults values for consensus client config:
- Graffiti: value set by the user || **validating_from_DAppNode**  
- Checkpointsync: current consensus client checkpointsync || dappnode checkpointsync
- Fee recipient: current consensus client fee recipient
=> Defaults for fee recipient and checkpointsync

packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts
Stop the previous clients in the stakres UI if no exec and cons clients options provided
=> Stop previous clients in stakers UI if no options provided

packages/admin-ui/src/__mock-backend__/stakerConfig.ts, packages/admin-ui/src/pages/stakers/components/columns/RemoteSigner.tsx
Show the web3signer UI link to upload the keystores in the stakers UI
=> Show web3signer ui link

packages/admin-ui/src/__mock-backend__/stakerConfig.ts, packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/stakers/components/AdvanceView.tsx, packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx, packages/admin-ui/src/pages/stakers/components/utils.ts, packages/admin-ui/src/pages/stakers/data.ts, packages/dappmanager/src/daemons/stakerConfig/index.ts, packages/dappmanager/src/modules/stakerConfig/getStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts
Allow to set which relays to enable from the stakers UI
=> Allow to set relays from stakers ui

packages/admin-ui/src/pages/stakers/components/columns/RemoteSigner.tsx
Fix signer UI link to be opened on a new tab
=> Fix signer ui link

packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/StakersRoot.tsx, packages/admin-ui/src/pages/stakers/components/columns/RemoteSigner.tsx, packages/dappmanager/src/modules/migrations/setDefaultStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/getStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts
=> Add mainnet to stakers UI

packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/data.ts
Set default consensus client config:
- If no previous consensus client selected use defaults
- If previouse consensus client selected use previous values
=> Set default consensus client config

packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/utils.ts
When stakers UI button is not allowed to be clicked, show a banner indicating the reason
=> Stakers UI - show banner indicating why changes are not allowed to be applied

packages/admin-ui/src/__mock-backend__/stakerConfig.ts, packages/admin-ui/src/common/types.ts, packages/dappmanager/src/modules/migrations/setDefaultStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts, packages/dappmanager/src/params.ts
Keep the Besu package as `public`. https://github.com/dappnode/DAppNodePackage-besu
=> Set Besu as `public` instead as `dnp`

packages/dappmanager/src/calls/packageRemove.ts
When calling `packageRemove` it fails when there was a stopped container with the error: 
```
Error: (HTTP code 304) container already stopped -  
at /usr/src/app/webpack:/node_modules/docker-modem/lib/modem.js:301:1
at getCause (/usr/src/app/webpack:/node_modules/docker-modem/lib/modem.js:331:1)
at Modem.buildPayload (/usr/src/app/webpack:/node_modules/docker-modem/lib/modem.js:300:1)
at IncomingMessage.<anonymous> (/usr/src/app/webpack:/node_modules/docker-modem/lib/modem.js:275:1)
at IncomingMessage.emit (events.js:412:35)
at endReadableNT (internal/streams/readable.js:1317:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
{
"dnpName": "https.dnp.dappnode.eth",
"deleteVolumes": true
}
```
Catch and bypass the error for `packageRemove`
=> Remove package even if container is stopped

packages/admin-ui/src/pages/stakers/components/utils.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts
Do not allow to apply changes if MEV boost package is selected and not relays set
=> Stakers UI relays length check

packages/admin-ui/src/dappnode_styles.scss, packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/utils.ts, packages/dappmanager/src/calls/packageSetPortMappings.ts
Added info, warning and danger colors for Stakers UI logs
=> Improving log colors for Stakers UI

packages/admin-ui/server-mock/eventBus.ts, packages/admin-ui/src/__mock-backend__/stakerConfig.ts, packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx, packages/admin-ui/src/pages/stakers/components/columns/ExecutionClient.tsx, packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx, packages/admin-ui/src/pages/stakers/components/columns/RemoteSigner.tsx, packages/dappmanager/src/calls/packageRemove.ts, packages/dappmanager/src/daemons/index.ts, packages/dappmanager/src/daemons/stakerConfig/index.ts, packages/dappmanager/src/db/stakerConfig.ts, packages/dappmanager/src/eventBus.ts, packages/dappmanager/src/modules/migrations/setDefaultStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/getStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/stakerParamsByNetwork.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts, packages/dappmanager/src/utils/asyncFlows.ts
Cache the stakers ui packages metadata to speed up the initial loading. Update the cache on every request in background
=> Cache staker ui packages metadata

packages/admin-ui/src/pages/stakers/components/AdvanceView.tsx, packages/admin-ui/src/pages/stakers/components/utils.ts
Use substrings in stakers UI advanced view
=> Use substrings in stakers uI advanced view

packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx, packages/admin-ui/src/pages/stakers/components/utils.ts
Add relays external docs URLs and fix naming for BloxRoute relays
=> Add relays docs and fix naming

packages/admin-ui/src/pages/stakers/components/columns/columns.scss
Add cursor pointer in stakers UI
=> add cursor pointer

packages/dappmanager/src/modules/migrations/setDefaultStakerConfig.ts
Set default values for network mainnet based on the following priority:
- Execution clients:
1. Get the ethereum client target and if its installed and running set it
2. Get any exec client installed and running
3. Get any exec client
- Consensus clients
1. Get the value from the legacy web3signer env ETH2_CLIENT 
2. Get the cons client from any cons client installed and running
3. Get the cons client from any cons client installed
The set of these values will re-activate all the containers using this global env with the new value
=> More resilience on setting default values for staker config in network mainnet

packages/dappmanager/src/modules/migrations/setDefaultStakerConfig.ts
Remove unnecessary types from utils funcions in `setDefaultStakerConfig`
=> Remove unnecesary types from `setDefaultStakerConfig`

docker/start_dev.sh
Force to reinstall all the node modules while using dappmanager docker developer mode
=> Remove node modules on docker dev

packages/admin-ui/src/pages/stakers/components/StakersRoot.tsx, packages/dappmanager/src/modules/migrations/setDefaultStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/stakerParamsByNetwork.ts
Enable gnosis chain in the stakers UI
=> enable gnosis for stakers UI

packages/admin-ui/src/pages/installer/components/dappnodeDappstore/InstallerDnp.tsx, packages/dappmanager/src/calls/fetchDirectory.ts
Implement fake featured cards for gnosis and mainnet. These cards will redirect to the stakers UI (gnosis and mainnet correspondingly)
=> Set fake staker cards gnosis and mainnet

packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx
Added banner to warn users not to use Prysm in Gnosis. There is no link to the source of the information in this branch
=> Added Prysm Gnosis warning

packages/dappmanager/src/modules/stakerConfig/stakerParamsByNetwork.ts
Update Gnosis stakers minimum versions
=> Update gnosis stakers versions

packages/dappmanager/src/calls/fetchDirectory.ts
=> Fix staker cards wording

packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/StakersRoot.tsx, packages/admin-ui/src/pages/stakers/data.ts, packages/admin-ui/src/params.ts
- Set default dappnode checkpoint sync for gnosis
- Rename mainnet with Ethereum
- Remove MEV boost config from gnosis description
=> Staker UIX for gnosis chain - small edits

packages/admin-ui/src/components/welcome/Finished.tsx, packages/admin-ui/src/pages/system/actions.ts, packages/admin-ui/src/params.ts
Update wording for ethereum repository
=> Update wording for Ethereum repository

Dockerfile, Dockerfile.dev
Update the docker node engine version to 19.2.0
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/1271 (The method `.getRandomValues` was not implemented in that node vesion)
=> Update docker node engine version

packages/dappmanager/src/daemons/ethMultiClient/index.ts
Deserialize checkpointsync object on ethClientInstaller
=> Deserialize checkpointsync object

packages/admin-ui/src/pages/stakers/components/utils.ts
Added new Gnosis and Monet relays for MEV Boost
=> Added Gnosis and Monet relays

Dockerfile, Dockerfile.dev
Reverts dappnode/DNP_DAPPMANAGER#1276
=> Revert "Update docker node engine version"

packages/dappmanager/src/params.ts
Add the nethermind public key to the default trusted keys.
=> Add nethermind public key to trusted keys

packages/dappmanager/src/modules/ethClient/apiUrl.ts, packages/dappmanager/src/modules/ethClient/clientStatus.ts
Build the beacon API dynamically
=> Build beacon API dynamically

packages/dappmanager/test/testIpfsUtils.ts
Add dappnode ipfs peer for int tests
=> Add dappnode ipfs peer

Dockerfile.dev, packages/dappmanager/src/api/startTestApi.ts, packages/dappmanager/src/index.ts, packages/dappmanager/src/params.ts, packages/dappmanager/test/integration/testIpfsUtils.ts
Implement test API with all the calls between frontend and backend
=> Implement test API

packages/admin-ui/package.json, packages/admin-ui/src/common/validation/generateSchemas.js, packages/admin-ui/src/common/validation/generateSchemas.ts, packages/dappmanager/package.json, yarn.lock
Bump dependency typescript-json-schema
=> Bumb typescript-json-schema

packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/packages/components/StateBadge/utils.ts, packages/dappmanager/src/modules/docker/dockerComposeUp.ts
Add the `removing` docker container state to the list of docker container states list
=> Add `removing` docker container state

packages/admin-ui/src/pages/community/components/TreasuryActions.tsx, packages/admin-ui/src/params.ts
fix more links, remove gitcoin references.
=> fix more links, remove gitcoin references.

.github/workflows/main.yml, Dockerfile, Dockerfile.dev
=> Set node LTS version

dappmanager-grafana-dashboard.json, packages/dappmanager/src/api/routes/metrics.ts
Add `dappmanager` prefix to custom metrics
=> Add `dappmanager` prefix to custom metrics

packages/admin-ui/src/common/types.ts, packages/admin-ui/src/pages/dashboard/components/ChainCard.tsx, packages/dappmanager/src/modules/chains/drivers/ethereum.ts, packages/dappmanager/src/modules/chains/drivers/ethereum2.ts, packages/dappmanager/src/modules/chains/index.ts, packages/dappmanager/src/utils/ethers.ts, packages/dappmanager/test/unit/modules/chains/ethereum.test.ts, packages/dappmanager/test/unit/modules/chains/ethereum2.test.ts
1. Rounded down the progress percentage (Not shown 100.00% and syncing)
2. Fixed chain cards position (not changed in useEffect)
3. Binary sync status for ECs
4. Added connected peers to chain cards
=> Fixing chain card bugs

packages/admin-ui/src/pages/dashboard/components/ChainCard.tsx
Check the repository dnp name to show the chain card
=> Check repository dnp name for the chain card

package.json
Add clean commands for removing:
- `node_modules`
- `build`
=> Add clean commands

packages/common/src/types.ts, packages/dappmanager/src/modules/stakerConfig/stakerParamsByNetwork.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts, packages/dappmanager/src/params.ts
Add Lodestar Prater to StakersUI backend replacing #1202 Tracked in #1194 and GH Project 40.
Closes #1203
=> Add lodestar Prater to StakersUI Backend

packages/admin-ui/src/__mock-backend__/data/dnps/web3signer.ts, packages/admin-ui/src/__mock-backend__/stakerConfig.ts
Adding Lodestar to the server mock originanally proposed in #1202
=> add lodestar to server Mock

packages/dappmanager/src/modules/stakerConfig/stakerParamsByNetwork.ts
Lodestar Prater is removed from the stakers UI
=> Removed lodestar from prater stakers UI

packages/admin-ui/package.json, packages/common/package.json, packages/dappmanager/package.json, yarn.lock
Update sdk dependency to v0.2.71
=> Update sdk dependency to v0.2.71

packages/admin-ui/src/components/welcome/features/ChangeHostPassword.tsx, packages/admin-ui/src/components/welcome/features/Repository.tsx
Text shown in the onboarding to the users are now clearer
=> Modify onboarding texts

packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
Only show the staker launchpad if network is prater
=> Only show stakers launchpad if network is prater

packages/admin-ui/src/pages/community/components/CommunityHome.tsx, packages/admin-ui/src/pages/community/components/community.scss, packages/admin-ui/src/pages/stakers/components/launchpad/launchpad-validators.scss
Fix dark theme issues in stakers UI
=> Fix dark theme in stakers UI

packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts
Add fee recipient backwards compatibility for setting the pkg env variable `FEE_RECIPIENT_ADDRESS`
=> Add fee recipient backwards compatibility

packages/admin-ui/src/App.tsx
=> Set usage mode to advanced by default

packages/admin-ui/src/App.tsx
=> Fix CI (unused variable)

packages/admin-ui/src/pages/repository/components/Eth.tsx, packages/dappmanager/src/modules/installer/runPackages.ts
Fix for small typos pointed out by @chuygarcia92
=> Fixed small typos

packages/dappmanager/src/modules/stakerConfig/stakerParamsByNetwork.ts
Add Lodestar Mainnet to stakersUI
Not to be merged until lodestar mainnet is published, web3signer is updated, and testing is complete
=> add lodestar Mainnet to stakers UI

packages/dappmanager/src/modules/stakerConfig/stakerParamsByNetwork.ts
add lodestar Gnosis to stakersUI
Lodestar gnosis package must be published first along with web3signer gnosis with changes for lodestar
=> add lodestar Gnosis to stakers UI

packages/dappmanager/package.json, packages/dappmanager/src/modules/ipfs/writeStreamToFs.ts, packages/dappmanager/tsconfig.json, yarn.lock
Improve download IPFS package speed
=> Improve download ipfs speed

Dockerfile.dev, packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
The consensus client useEffect was been not updated cause the hook was missing few deps
=> Fix stakers preselection

packages/common/src/types.ts
Lodestar is added to the available types in stakers UI
=> Added lodestar mainnet and gnosis to staker types

packages/admin-ui/src/__mock-backend__/httpsPortal.ts, packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/pages/packages/components/Network/HttpsMappings.tsx, packages/admin-ui/src/pages/system/components/Advanced/ChangeDappnodeWebName.tsx, packages/admin-ui/src/pages/system/components/Network/HttpsMappings.tsx, packages/common/src/routes.ts, packages/dappmanager/src/api/startTestApi.ts, packages/dappmanager/src/calls/dappnodeWebNameSet.ts, packages/dappmanager/src/calls/httpsPortal.ts
Add to test api args containing arrays of strings
=> Support in test api args containing arrays of strings

packages/dappmanager/src/params.ts
Added key to dappmanager so that whenever the ETC Cooperative publish packages it shows the `ETC Cooperative` as author of the package.
=> Added ETC Cooperative key

packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx, packages/admin-ui/src/pages/stakers/components/launchpad/LaunchpadSteps.tsx
Simplify consensus card in stakers UI
=> Simplify consensus card

packages/admin-ui/src/components/toast/toastStyle.scss, packages/admin-ui/src/dappnode_colors.scss
=> Fix toast background

packages/dappmanager/src/api/startTestApi.ts
Be more verbose on test API and print error to console
=> Be more vervose on test api

packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts
Relocate writes on db in `setStakerConfig`. It may lead to errors when the installation of certain packages was done without global envs
=> Relocate writes on db in `setStakerConfig`

packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
=> Visual modification of MEV Boost in Stakers

packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts
Skip possible returns when writting on db and setting new staker config
=> Skip possible returns when writting on db

packages/admin-ui/package.json, packages/common/package.json, packages/dappmanager/package.json, yarn.lock
Bump dappnode deps:
- types:0.1.14
- schemas:0.1.7
=> Bump dappnode deps

.github/workflows/build.yml, .github/workflows/main.yml, .github/workflows/netlify.yml, Dockerfile, Dockerfile.dev, packages/common/package.json
=> Bump node version to 20.3.0

packages/admin-ui/src/pages/installer/components/dappnodeDappstore/InstallerDnp.tsx, packages/admin-ui/src/params.ts, packages/dappmanager/src/calls/fetchDirectory.ts
Add stakehouse card to redirect users to LSD deposit website
=> Add stakehouse card

packages/dappmanager/src/modules/stakerConfig/set/setSigner.ts, packages/dappmanager/src/modules/stakerConfig/set/setStakerConfig.ts
Use await all in stakers configuration
=> Use await all in staker

package.json, packages/dappmanager/src/calls/stakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/set/setConsensusClient.ts, packages/dappmanager/src/modules/stakerConfig/set/setExecutionClient.ts, packages/dappmanager/src/modules/stakerConfig/set/setMevBoost.ts, packages/dappmanager/src/modules/stakerConfig/set/setSigner.ts, packages/dappmanager/src/modules/stakerConfig/set/setSignerConfig.ts, packages/dappmanager/src/modules/stakerConfig/set/setStakerConfig.ts, releases.json, yarn.lock
Fix esm imports not detected by eslint
=> Fix esm imports

.gitignore, Dockerfile.dev, docker-compose-dev.yml, docker/start_dev.sh, packages/dappmanager/package.json, yarn.lock
Fix dev mode and improves its efficiency by executing the installs and builds in docker build stage
=> Fix dev mode

packages/dappmanager/src/modules/stakerConfig/utils.ts
Fix typos in getStakerConfigByNetwork
=> Fix typos in getStakerConfigByNetwork

packages/admin-ui/src/pages/stakers/components/utils.ts
Remove deprecated relay in mev boost
=> Remove deprecated relay

packages/dappmanager/src/modules/release/getRelease.ts
Add checker for origin in `getRelease`
=> Add checker for origin in `getRelease`

packages/dappmanager/src/db/interceptGlobalEnvOnSet.ts
check for nullish value in interceptGlobalEnvOnSet
=> check for nullish value in interceptGlobalEnvOnSet

packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
=> Fix installer for ipfs hashes

packages/admin-ui/src/pages/dashboard/components/ChainCard.tsx, packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx, packages/admin-ui/src/pages/packages/components/Info/RemovePackage.tsx
Fix redirection after installing or removing pkg
=> Fix redirection after installing or removing pkg

packages/admin-ui/package.json, packages/common/package.json, packages/dappmanager/package.json
Add `^` to allow minor/patch updates
=> Allow minor/patch updates on dappnode types

packages/admin-ui/src/pages/wifi/components/wifi/WifiCredentials.tsx
Change wifi credentials functionality was not working. This fixes it.
=> Fix change wifi credentials

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/api/initialCalls.ts, packages/admin-ui/src/components/NotificationsMain.tsx, packages/admin-ui/src/pages/packages/components/Network/HttpsMappings.tsx, packages/admin-ui/src/pages/system/components/AutoUpdates/AutoUpdateRowItem.tsx, packages/admin-ui/src/pages/system/data.ts, packages/admin-ui/src/pages/system/index.ts, packages/admin-ui/src/services/dappnodeStatus/actions.ts, packages/admin-ui/src/services/dappnodeStatus/reducer.ts, packages/admin-ui/src/services/dappnodeStatus/selectors.ts, packages/common/src/routes.ts, packages/dappmanager/src/calls/index.ts, packages/dappmanager/src/calls/rebootHostIsRequiredGet.ts
Add reboot is required notification so users are aware that weather the host machine require or not a reboot
=> Add reboot is required notification

packages/admin-ui/src/App.tsx
Add fallback redirect for backwards compatibility and default to dashboard for non matching routes
=> Add fallback redirect

packages/admin-ui/src/pages/system/components/SystemRoot.tsx
=> Fix add ipfs peer subpath

packages/dappmanager/src/calls/packageRestartVolumes.ts, packages/dappmanager/src/modules/docker/api/network.ts, packages/dappmanager/src/modules/ethClient/ethereumClient.ts, packages/dappmanager/src/modules/migrations/addAliasToRunningContainers.ts, packages/dappmanager/test/unit/modules/docker/network.test.ts
State was reverted in order to only apply changes related to LUKSO. Getting this back as they need to be published ASAP.
=> Revert "Reverted to state at v0.2.71 (#1558)"

packages/dappmanager/test/integration/dnpLifecycle.test.int.ts
=> skip lifecycle test

packages/dappmanager/src/modules/migrations/setDefaultEthicalMetricsEmail.ts
Enable ethical metrics daemon in migration if required
=> Enable ethical metrics in migration

packages/admin-ui/src/components/welcome/features/EnableEthicalMetrics.tsx
Typo in Ethical Metrics onboarding
=> "Loosing" typo

packages/dappmanager/src/daemons/ethicalMetrics/checkEthicalMetricsStatus.ts
This import was not being used
=> Remove unused import

packages/admin-ui/src/components/welcome/features/EnableEthicalMetrics.tsx
Enable ethical metrics depending on if email is correct or not
=> Enable ethical metrics depending on email

packages/admin-ui/src/pages/system/components/SystemUpdate/SystemUpdateDetails.tsx
Fix modifying existing dnp core update object to remove the warningOnInstall
=> Fix modifying existing dnp core update object

packages/admin-ui/src/pages/rollups/components/OpCommunity.tsx, packages/admin-ui/src/pages/rollups/components/Optimism.tsx, packages/admin-ui/src/pages/rollups/components/opCommunity.css
Added community dropdown card for Rollups>Optimism:
=> OP community

packages/admin-ui/src/App.tsx, packages/admin-ui/src/types.ts
=> Fix dark mode confirm dialog

packages/admin-ui/src/components/welcome/features/EnableEthicalMetrics.tsx, packages/admin-ui/src/params.ts
Users might want more information about Ethical Metrics before setting up their email in the onboarding
=> Add learn more link to Ethical Metrics in onboarding

packages/admin-ui/package.json, packages/admin-ui/src/__mock-backend__/index.ts, packages/common/package.json, packages/dappmanager/package.json, packages/dappmanager/src/modules/optimism/params.ts, packages/eventBus/package.json, packages/utils/package.json, yarn.lock
To be merged after https://github.com/dappnode/types/pull/32
=> Remove op-erigon temporarily

packages/dappmanager/src/utils/autoUpdateHelper.ts
Auto update interval was wrongly set to `AUTO_UPDATE_DAEMON_INTERVAL`
=> Fix auto update interval

packages/admin-ui/package.json, packages/admin-ui/src/__mock-backend__/index.ts, packages/common/package.json, packages/dappmanager/package.json, packages/dappmanager/src/modules/optimism/params.ts, packages/eventBus/package.json, packages/utils/package.json, yarn.lock
=> Re-add OP Erigon

Dockerfile, packages/params/package.json, packages/utils/src/buildNetworkAlias.ts, packages/utils/src/fileToGatewayUrl.ts, packages/utils/src/getPrivateNetworkAliases.ts
Add missing modules to dockerfile:
- dockerApi
- dockerCompose
- hostScripts
=> Add missing modules to dockerfile

packages/admin-ui/src/pages/dashboard/components/ChainCard.tsx, packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx, packages/admin-ui/src/pages/system/data.ts
closes #1571 
To test, open dappmanager and click on "?" button. it should navigate to /repository/eth view, where you can swap local or remote ethereum repo.
Test back button: install /ipfs/QmcqMTkaU7jwmVKRC7WmRX6mRfiH54T38AzyresvBbKBNe. Get to the disclaimer page and click on "back" button. Should redirect to setup.
=> Fix interrogation link

packages/common/src/types.ts, packages/dappmanager/src/api/routes/metrics.ts
=> collect docker version metric

packages/hostScripts/hostScripts/collect_host_info.sh
Add checker for docker compose version using `docker compose version` in addition to `docker-compose`
=> Add checker for docker compose version

packages/admin-ui/package.json, packages/admin-ui/src/__mock-backend__/stakerConfig.ts, packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/StakersRoot.tsx, packages/admin-ui/src/pages/stakers/components/launchpad/LaunchpadSteps.tsx, packages/common/package.json, packages/common/src/types.ts, packages/dappmanager/package.json, packages/dappmanager/src/api/routes/metrics.ts, packages/dappmanager/src/modules/stakerConfig/get/getStakerDnpNamesByNetwork.ts, packages/dappmanager/src/modules/stakerConfig/set/getStakerCompatibleVersionsByNetwork.ts, packages/dappmanager/src/modules/stakerConfig/set/setStakerConfig.ts, packages/dappmanager/src/modules/stakerConfig/utils.ts, packages/db/package.json, packages/db/src/globalEnvs.ts, packages/db/src/stakerConfig.ts, packages/dockerApi/package.json, packages/dockerCompose/package.json, packages/eventBus/package.json, packages/installer/package.json, packages/installer/src/packages/packageRemove.ts, packages/params/src/params.ts, packages/utils/package.json, packages/utils/src/stakerUtils.ts, yarn.lock
Setup holesky network. Prater is about to be deprecated
=> Setup holesky network

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/components/NotificationsMain.tsx, packages/admin-ui/src/services/dappnodeStatus/actions.ts, packages/admin-ui/src/services/dappnodeStatus/reducer.ts, packages/admin-ui/src/services/dappnodeStatus/selectors.ts, packages/common/src/routes.ts, packages/common/src/types.ts, packages/dappmanager/src/calls/rebootHostIsRequiredGet.ts, packages/hostScripts/hostScripts/reboot_required.sh, packages/hostScripts/src/index.ts, packages/hostScripts/src/runScripts.ts, packages/hostScripts/src/scripts/rebootRequired.ts
fix get reboot required using a host script instead
=> fix get reboot required

packages/dappmanager/tsconfig.json
Remove installer pkg in dappmanager tsconfig include
=> Remove installer in dappmanager tsconfig include

packages/dappmanager/src/modules/stakerConfig/set/getStakerCompatibleVersionsByNetwork.ts
Added nethermind and besu to minimum versions in network Holesky
=> Add nethermind and besu to minimum versions

packages/admin-ui/README.md, packages/chains/README.md, packages/common/README.md, packages/daemons/README.md, packages/dappmanager/README.md, packages/db/README.md, packages/dockerApi/README.md, packages/dockerCompose/README.md, packages/dyndns/README.md, packages/ethicalMetrics/README.md, packages/eventBus/README.md, packages/hostScriptsServices/README.md, packages/httpsPortal/README.md, packages/installer/README.md, packages/ipfs/README.md, packages/logger/README.md, packages/manifest/README.md, packages/migrations/README.md, packages/optimism/README.md, packages/params/README.md, packages/stakers/README.md, packages/upnpc/README.md, packages/utils/README.md
Add readmes templates to modules
=> Add readmes templates to modules

packages/db/src/globalEnvs.ts, packages/db/src/stakerConfig.ts
Remove fee recipient from db
Part of https://github.com/dappnode/DNP_DAPPMANAGER/pull/1691
=> Remove fee recipient from db

packages/eventBus/src/index.ts, packages/logger/src/index.ts, tsconfig.json
Add isolated modules to speed up the CI
=> Add isolated modules

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/pages/dashboard/components/HostStats.tsx, packages/common/src/routes.ts, packages/dappmanager/src/calls/getHostUptime.ts, packages/dappmanager/src/calls/index.ts, packages/dappmanager/test/unit/calls/getHostUptime.test.ts
Added a card to display the uptime of the host in the dashboard
=> Add card to display the uptime of the host

packages/hostScriptsServices/hostScripts/update_upgrade.sh, packages/hostScriptsServices/hostServices/update-upgrade-host.service
Remove unnecessary flag and do not `set -e` in update upgrade
=> Remove unnecessary flag and do not `set -e` in update upgrade

packages/admin-ui/README.md, packages/chains/README.md, packages/common/README.md, packages/daemons/README.md, packages/dappmanager/README.md, packages/db/README.md, packages/dockerApi/README.md, packages/dockerCompose/README.md, packages/dyndns/README.md, packages/ethicalMetrics/README.md, packages/eventBus/README.md, packages/hostScriptsServices/README.md, packages/httpsPortal/README.md, packages/installer/README.md, packages/logger/README.md, packages/migrations/README.md, packages/optimism/README.md, packages/params/README.md, packages/schemas/README.md, packages/stakers/README.md, packages/toolkit/README.md, packages/upnpc/README.md, packages/utils/README.md
Assign responsabilities.
- Understand the module assigned: what it does, where is it called, etc
- Clean code: try to reduce amount of dependencies, organize better the code if possible, reduce utilities functions etc
- Cover all the module with unit and or integration testing
- Document it
cc: @pablomendezroyo @Marketen @3alpha @dappnodedev @GiselleNessi @kdelap00 @darkda567
=> Assign responsabilities

packages/admin-ui/src/pages/rollups/components/columns/ExecutionClient.tsx, packages/admin-ui/src/pages/rollups/components/columns/LegacyGeth.tsx, packages/admin-ui/src/pages/rollups/components/columns/OptimismNode.tsx, packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx, packages/admin-ui/src/pages/stakers/components/columns/ExecutionClient.tsx, packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx, packages/admin-ui/src/pages/stakers/components/columns/RemoteSigner.tsx, packages/common/package.json, packages/common/src/transport/socketIo/index.ts, packages/common/src/validation/index.ts, yarn.lock
bump ajv and strict false in common to avoid throwing validation not expected errors in the frontend
=> bump ajv and set strict to `false` in common

packages/schemas/src/validateDappnodeCompose.ts
skip bind compose network validation until new bind is published
=> skip bind compose network validation

packages/dappmanager/src/api/startHttpApi.ts
Bypass proxy middlewares: eth and ipfs
=> Bypass proxy middleware

packages/dappmanager/src/calls/fetchDirectory.ts, packages/dockerApi/test/unit/parseContainerInfo.test.ts, packages/utils/src/fileToGatewayUrl.ts
Use remote gateway to render logos instead of local IPFS proxy
=> Use remote gateway to render logos

packages/dyndns/src/updateDyndnsIp.ts, packages/dyndns/test/unit/dyndns.test.ts
=> Add tests for dyndns module

packages/dappmanager/src/calls/cleanCache.ts
Removed unnecessary loop for cleaning cache DB
=> Remove unnecessary loop to clean cache

packages/utils/src/getPublicIpFromUrls.ts, packages/utils/test/unit/getPublicIpFromUrls.test.ts
=> Improve public IP fetch

packages/utils/src/buildNetworkAlias.ts, packages/utils/test/unit/getPrivateNetworkAliases.test.ts
Add tests for the function in charge of building all the available aliases of a container
=> Add test for aliases util function

packages/dappmanager/src/calls/copyFileTo.ts
=> Use node `fs` in calls

packages/chains/tsconfig.json, packages/common/tsconfig.json, packages/daemons/tsconfig.json, packages/dappmanager/tsconfig.json, packages/db/tsconfig.json, packages/dockerApi/tsconfig.json, packages/dockerCompose/tsconfig.json, packages/dyndns/tsconfig.json, packages/ethicalMetrics/tsconfig.json, packages/eventBus/tsconfig.json, packages/hostScriptsServices/tsconfig.json, packages/httpsPortal/tsconfig.json, packages/installer/tsconfig.json, packages/logger/tsconfig.json, packages/migrations/tsconfig.json, packages/optimism/tsconfig.json, packages/params/tsconfig.json, packages/schemas/tsconfig.json, packages/stakers/tsconfig.json, packages/toolkit/tsconfig.json, packages/upnpc/tsconfig.json, packages/utils/tsconfig.json, tsconfig.json
Add `declarationMap: true` in root `tsconfig.json`
=> Add `declarationMap: true` in root `tsconfig.json`

packages/dockerApi/package.json, packages/installer/package.json, packages/installer/src/ethClient/ethereumClient.ts, packages/installer/src/installer/restartPatch.ts, packages/migrations/package.json, yarn.lock
=> Bump dockerode depenedency

Dockerfile, Dockerfile.dev, packages/dockerApi/src/compose/cli.ts, packages/installer/src/installer/restartPatch.ts
Use of compose plugin command instead of `docker-compose` binary
=> Use of compose plugin

packages/dappmanager/package.json, packages/dappmanager/src/api/middlewares/ethForward/resolveDomain.ts, packages/dappmanager/src/api/startHttpApi.ts, packages/dappmanager/src/utils/sign.ts, packages/dappmanager/test/unit/ethForward/resolveDomain.test.int.ts, packages/dappmanager/test/unit/utils/sign.test.ts, yarn.lock
bump ethers dep in dappmanager
=> bump ethers dep in dappmanager

packages/toolkit/package.json, packages/toolkit/src/repository/releaseSignature.ts
Fix not signed and add watcher to toolkit
=> Fix not signed

packages/admin-ui/src/pages/stakers/components/useStakerConfig.ts
stop comparing only relay lenght to define if changes were made.
now we check also relay content
=> Improve relays changes

packages/migrations/package.json, packages/migrations/src/migrateDockerNetworkIpRange/ensureDockerNetworkConfig.ts, packages/migrations/src/migrateDockerNetworkIpRange/subnetsOverlap.ts, packages/migrations/test/unit/subnetsOverlap.unit.test.ts
With this PR we make sure that there are no other docker networks whose subnets might overlap with the one we want to create
=> Implement network overlapping check

packages/migrations/package.json
Fixing IP range migration tests failing
=> Fix IP range migration tests

docker-compose.yml
Remove hardcoded ip from compose file
=> Remove hardcoded ip from compose file

packages/daemons/src/avahi/index.ts
Silent avahi daemon error stack trace log
=> Silent avahi daemon error stack trace

packages/dappmanager/src/calls/fetchDirectory.ts
Print only error message on fetch directory error
=> Print only error message on fetch directory error

packages/dockerCompose/src/setDappnodeComposeDefaults.ts
Ensure none uses reserved IPs in compose files
=> Ensure none uses reserved IPs in compose files

packages/dockerCompose/src/setDappnodeComposeDefaults.ts, packages/dockerCompose/test/unit/composeSpecs.test.ts, packages/dockerCompose/test/unit/releaseSpecs/dappmanager/docker-compose.parsed.yml, packages/dockerCompose/test/unit/releaseSpecs/vpn/docker-compose.parsed.yml, packages/dockerCompose/test/unit/setDappnodeComposeDefaults.test.ts, packages/params/src/params.ts
fix unit test in dockerCompose module
=> fix unit test in dockerCompose module

packages/migrations/src/migrateDockerNetworkIpRange/connectContainersToNetworkWithPrio/connectContainerWithIp.ts
Check containertname before disconnect in migration
=> Check containertname before disconnect

packages/installer/src/ethClient/ethersProvider.ts, packages/toolkit/src/directory/directory.ts, packages/toolkit/src/registry/registry.ts, packages/toolkit/src/repository/apmRepository.ts
=> use static network

packages/hostScriptsServices/hostScripts/check_docker_network.sh
=> Fix typos in comments

packages/daemons/src/bind/ensureBindContainerIpAndRunning.ts
Add force recreate in docker compose up bind daemon
=> Add force recreate

packages/chains/package.json, packages/chains/src/drivers/ethereum.ts
Use fetch instead of ethers in chains drivers
=> Use fetch instead of ethers in chains drivers

packages/dappmanager/src/index.ts
Use defaults on error when initializing dappnodeInstaller instance to avoid error on app startup
=> Use defaults on error when initializing dappnodeInstaller instance

packages/dockerCompose/src/setDappnodeComposeDefaults.ts
Allow bind hardcoded ip in installer
=> Allow bind hardcoded ip

packages/dappmanager/src/index.ts, packages/dappmanager/src/initializeDb.ts
Relocate initialized db so its created before any other call
=> Relocate initialized db

.github/workflows/npm.yml
Add workflow for publishg internal modules:
- schemas
- toolkit
- types
=> Add workflow for publishg internal modules

packages/migrations/src/addDappnodePeerToLocalIpfsNode.ts, packages/migrations/src/index.ts, packages/migrations/test/unit/addPeerToLocal.unit.test.ts
Add Dappnode Peer to Local Ipfs Node
=> - Add Dappnode Peer to Local Ipfs Node

packages/schemas/package.json, packages/schemas/test/testUtils.ts
Remove utils from schemas dependency
=> Remove utils from schemas

packages/dappmanager/package.json, packages/installer/package.json, packages/toolkit/package.json
bump dappnode toolkit dep to 0.1.21
=> bump dappnode toolkit dep

packages/schemas/src/validateDappnodeCompose.ts
Remove docker network bind checker since the 0.2.9 is not necessary
=> Remove docker network bind checker

packages/daemons/src/bind/ensureBindContainerIpAndRunning.ts, packages/daemons/src/bind/index.ts, packages/migrations/src/index.ts, packages/utils/src/asyncFlows.ts
Delay bind daemon so it start 10 seconds after initialization, this way allow bind package to start itself if is a core update
=> Delay bind daemon

packages/params/src/params.ts
Add mgarciate key as release trusted key. Packages intended to be published by mgarciate:
- Rotki
- Alephium
=> Add mgarciate key as release trusted key

packages/admin-ui/package.json, packages/chains/package.json, packages/common/package.json, packages/daemons/package.json, packages/dappmanager/package.json, packages/db/package.json, packages/dockerCompose/package.json, packages/eventBus/package.json, packages/hostScriptsServices/package.json, packages/httpsPortal/package.json, packages/installer/package.json, packages/installer/src/dappGet/fetch/DappGetFetcher.ts, packages/installer/src/dappnodeInstaller.ts, packages/logger/package.json, packages/migrations/package.json, packages/optimism/package.json, packages/schemas/package.json, packages/schemas/src/schemas/manifest.schema.json, packages/stakers/package.json, packages/toolkit/package.json, packages/types/package.json, packages/types/src/manifest.ts, packages/upnpc/package.json, packages/utils/package.json
Add optional dependencies to allow to update packages **installed** in a package update. If the optional dependency is not installed then it will not be installed
=> Add optional dependencies

packages/params/src/params.ts, packages/schemas/src/params.ts, packages/schemas/src/validateDappnodeCompose.ts
Reverts dappnode/DNP_DAPPMANAGER#1779
=> Revert "Trigger private IP range migration"

packages/params/src/params.ts
Add HOPR team key as trusted publisher key
=> Add HOPR team key

packages/stakers/src/set/getStakerCompatibleVersionsByNetwork.ts, packages/types/src/stakers.ts
Add erigon gnosis as execution client
=> Add erigon gnosis 

packages/stakers/src/set/getStakerCompatibleVersionsByNetwork.ts, packages/types/src/stakers.ts
This PR add Nimbus client support for Gnosis chain.
[nimbus-gnosis package](https://github.com/gnosischain/DAppNodePackage-nimbus-gnosis)
=> Add nimbus-gnosis client

packages/stakers/src/set/getStakerCompatibleVersionsByNetwork.ts, packages/types/src/stakers.ts
According to dappnode naming convention, naming for execution clients packages should follow the format: `network-client`
This PR change erigon gnosis package name in a way:
`erigon-gnosis` --> `gnosis-erigon`
=> Update to adhere to naming convention

dappmanager-grafana-dashboard.json, packages/dappmanager/src/api/routes/metrics.ts
Create cpu temperature metric and its corresponding grafana dashboard
=> Create cpu temperature metric and its corresponding grafana dashboard

packages/admin-ui/src/pages/system/components/SystemUpdate/SystemUpdateDetails.tsx
Deprecate warningOnInstall core 0.2.0 edge case where the warning on install was manually edited
=> Deprecate warningOnInstall core 0.2.0

packages/toolkit/test/directory/directory.test.ts
Directory test is reaching timeout error using infura provider. Skip test until find a proper solution
=> Skip directory test

packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx, packages/admin-ui/src/pages/installer/components/Steps/Warnings.tsx, packages/dappmanager/src/calls/fetchDnpRequest.ts, packages/types/src/calls.ts
Fix showing warnings when:
- onMinorUpdate
- onPatchUpdate
- onMajorUpdate
- onInstall
=> Fix showing warnings 

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/api/initialCalls.ts, packages/admin-ui/src/components/NotificationsMain.tsx, packages/admin-ui/src/pages/support/components/AutoDiagnose.tsx, packages/admin-ui/src/pages/support/formaters/autoDiagnoseTexts.ts, packages/admin-ui/src/pages/support/types.ts, packages/admin-ui/src/params.ts, packages/admin-ui/src/services/dappnodeStatus/actions.ts, packages/admin-ui/src/services/dappnodeStatus/reducer.ts, packages/admin-ui/src/services/dappnodeStatus/selectors.ts, packages/dappmanager/src/calls/getIsConnectedToInternet.ts, packages/dappmanager/src/calls/index.ts, packages/types/src/routes.ts
Warning to the user with an alert if the dappnode host is not connected to internet. Also adding a link to our documentation in Autodiagnose for this case.
=> Notifying if internet disconnected with an alert

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/pages/system/components/Advanced/DockerUpgrade.tsx, packages/admin-ui/src/pages/system/components/Advanced/UpdateUpgrade.tsx, packages/admin-ui/src/pages/system/components/Advanced/index.tsx, packages/dappmanager/src/calls/dockerUpgrade.ts, packages/dappmanager/src/calls/index.ts, packages/hostScriptsServices/hostScripts/docker_upgrade.sh, packages/hostScriptsServices/hostServices/docker-upgrade.service, packages/hostScriptsServices/src/hostScripts/runScripts.ts, packages/hostScriptsServices/src/hostScripts/scripts/dockerUpgradeCheck.ts, packages/hostScriptsServices/src/hostScripts/scripts/index.ts, packages/hostScriptsServices/src/hostServices/index.ts, packages/hostScriptsServices/src/hostServices/runService.ts, packages/hostScriptsServices/src/hostServices/services/dockerUpgrade.ts, packages/hostScriptsServices/src/hostServices/services/index.ts, packages/types/src/calls.ts, packages/types/src/routes.ts
Implement docker upgrade action from the UI:
- Script to check requirements:
- Docker is in unattended upgrades
- Docker host version
- Docker latest version
- Docker is installed through apt
- Script to upgrade docker
- Check internet and dns resolution
- Remove legacy docker packages
- Get download urls depending on OS
- Install new docker with apt
- Add docker to unattended upgrades
- Add docker alias
=> Implement docker upgrade

packages/hostScriptsServices/hostScripts/docker_upgrade.sh
Update docker upgrade script to reflect new changes in the official docker installation method
=> Update docker upgrade script

packages/params/src/params.ts
Added dappnode address as trusted key for public packages
=> Add dappnode key for public packages

packages/admin-ui/src/App.tsx, packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/api/initialCalls.ts, packages/admin-ui/src/components/Smooth.tsx, packages/admin-ui/src/components/smooth.scss, packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/columns.scss, packages/admin-ui/src/params.ts, packages/admin-ui/src/services/dappnodeStatus/actions.ts, packages/admin-ui/src/services/dappnodeStatus/reducer.ts, packages/admin-ui/src/services/dappnodeStatus/selectors.ts, packages/dappmanager/src/calls/index.ts, packages/dappmanager/src/calls/smooth.ts, packages/db/src/ui.ts, packages/types/src/routes.ts
Show smooth modal
Please see issue #1808
=> Smooth modal integration

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/components/sidebar/SideBar.tsx, packages/admin-ui/src/components/sidebar/sidebar.scss, packages/dappmanager/src/calls/getCoreVersion.ts, packages/dappmanager/src/calls/index.ts, packages/types/src/routes.ts
Displaying version of the core package in the bottom of the UI Sidebar
=> Core version displayed in Sidebar bottom

packages/admin-ui/package.json, packages/chains/package.json, packages/common/package.json, packages/daemons/package.json, packages/dappmanager/package.json, packages/db/package.json, packages/dockerCompose/package.json, packages/eventBus/package.json, packages/hostScriptsServices/package.json, packages/httpsPortal/package.json, packages/installer/package.json, packages/logger/package.json, packages/migrations/package.json, packages/optimism/package.json, packages/schemas/package.json, packages/stakers/package.json, packages/toolkit/package.json, packages/types/package.json, packages/upnpc/package.json, packages/utils/package.json
=> Bump dappnode types to 0.1.36

packages/installer/package.json, packages/schemas/package.json
bump dappnode schemas to 0.1.14
=> bump dappnode schemas to 0.1.14

packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
Only show warnings update if exist
=> Only show warnings update if exist

packages/db/src/system.ts, packages/migrations/src/determineIsDappnodeCloud.ts, packages/migrations/src/index.ts
implement `determineIsDappnodeCloud` by retrieving user ID and telegram token from user data.
Start telegram bot daemon to allow authenticated user to retrieve wireguard credentials
=> implement determineIsDappnodeCloud

packages/admin-ui/src/pages/stakers/components/StakersRoot.tsx
The descriptions for the various blockchains we support in the stakers UI are... terrible.  
I rewrote them to make them actually relevant and explain things about the network on its goals/abilities, not just like `ethereum is based on blockchain tech, it has a programming language called solidity` 
For the sources of the new descriptions I used references from each of the projects' home page/about descriptions.
I found it hard to even fit single sentences for each since the description just seemed too, incomplete or like it needed another phrase, so after checking with Vercel CI that having 2-3 sentences for each description doesn't make the display appear weird or off to me …
=> Update descriptions of chains in stakers UI

packages/params/src/params.ts
Add Blockswap Labs key as authorized developer for public packages
=> Add Blockswap Labs key

packages/migrations/src/determineIsDappnodeAws.ts
split aws calls and add `--` to `shellHost`
=> split aws calls and add `--` to `shellHost`

packages/admin-ui/src/pages/installer/components/Steps/Info.tsx, packages/admin-ui/src/pages/packages/components/Info/index.tsx, packages/daemons/src/autoUpdates/sendUpdateNotification.ts, packages/dappmanager/src/api/routes/packageManifest.ts, packages/types/src/manifest.ts, packages/types/src/utils/READEME.md, packages/types/src/utils/index.ts, packages/types/src/utils/upstreamVersionToString.ts
Adapt upstream version string format to the newly implemented way of managing multi-upstream packages
=> Handle new upstream format

packages/admin-ui/src/pages/installer/components/dappnodeDappstore/InstallerDnp.tsx
updated old branding in loading screens
=> updated old branding in loading screens

packages/schemas/src/schemas/manifest.schema.json
Add missing properties to manifest JSON schema:
- runOrder
- restartCommand
- restartLaunchCommand
=> Add missing properties to manifest JSON schema

packages/admin-ui/src/__mock-backend__/data/dnpRequest.ts, packages/admin-ui/src/__mock-backend__/data/sample.ts, packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx, packages/dappmanager/src/calls/fetchDnpRequest.ts, packages/installer/test/int/fetchRelease.test.int.ts, packages/schemas/src/schemas/manifest.schema.json, packages/types/src/calls.ts, packages/types/src/manifest.ts
Implement requirement not installed packages. This requirement will enforce to uninstall a package manually before moving forward with an update or a installation from scratch
=> Implement requirement not installed packages

packages/stakers/src/consensus.ts, packages/stakers/src/mevBoost.ts, packages/stakers/src/stakerComponent.ts
Fix persisting mev boost relays in stakers network
=> Fix persisting mev boost relays

packages/dockerCompose/src/userSettings.ts, packages/installer/src/installer/getInstallerPackageData.ts, packages/stakers/src/consensus.ts, packages/stakers/src/execution.ts, packages/stakers/src/mevBoost.ts, packages/stakers/src/signer.ts, packages/stakers/src/stakerComponent.ts
Fix persist docker networks and user settings related to docker networks
=> Fix persist docker networks

packages/stakers/src/consensus.ts
Fix setting consensus env when NOT installed
=> Fix setting consensus env

packages/db/src/stakerConfig.ts, packages/stakers/src/consensus.ts, packages/stakers/src/execution.ts, packages/stakers/src/mevBoost.ts
Fix staker global envs prefix, it was being used the constant value instead of the contant key
=> Fix staker global envs prefix

packages/stakers/src/execution.ts, packages/types/src/stakers.ts
Add reth to available  execution clients in holesky network
=> Add reth to execution clients holesky

packages/stakers/src/mevBoost.ts
Persist existing relays in `stakerComponent`
=> Persist existing relays in `stakerComponent`

packages/admin-ui/src/pages/repository/components/Eth.tsx, packages/admin-ui/src/pages/repository/components/Ipfs.tsx, packages/admin-ui/src/services/notifications/actions.ts, packages/installer/src/ethClient/clientStatus.ts, packages/installer/src/ethClient/ethereumClient.ts
=> Fix: typos

packages/daemons/src/ethicalMetrics/checkEthicalMetricsStatus.ts
Do not install exporter pkg if ethical metrics enabled.
Requirement for DMS v2 to be published
=> Do not install exporter pkg if ethical metrics enabled

packages/schemas/src/validateComposeSchema.ts
Use new `compose` plugin for file validation. instead of legacy binary `docker-compose`
=> Use compose plugin for file validation

Dockerfile.dev
Remove port from vite app api env
=> Remove port from vite app api env

packages/params/src/params.ts
Add lighthouse team key. It will be used to publish:
`lighthouse.dnp.dappnode.eth`
`lighthouse-holesky.dnp.dappnode.eth`
`lighthouse-gnosis.dnp.dappnode.eth`
=> Add lighthouse team key

packages/admin-ui/src/services/coreUpdate/reducer.ts, packages/admin-ui/src/services/dappnodeStatus/reducer.ts, packages/admin-ui/src/services/isInstallingLogs/reducer.ts, packages/daemons/src/ethMultiClient/index.ts, packages/dappmanager/src/calls/packageRestartVolumes.ts, packages/dappmanager/src/calls/packageSetPortMappings.ts, packages/db/src/updatePkgsWithGlobalEnvs.ts, packages/dockerApi/src/dockerComposeUp.ts, packages/installer/src/calls/packageSetEnvironment.ts, packages/installer/src/ethClient/ethereumClient.ts, packages/installer/src/installer/rollbackPackages.ts, packages/installer/src/installer/runPackages.ts, packages/stakers/src/stakerComponent.ts
Fix `dockerComposeUp` args and wrap all of them into an object for easier read
=> Fix `dockerComposeUp` args

packages/stakers/src/execution.ts
Add execution client reth to network mainnet
=> Add execution client reth

packages/stakers/src/execution.ts, packages/types/src/stakers.ts
Fix typo reth execution client mainnet
=> Fix typo reth execution client mainnet

packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
Removing deprecated eden relay & adding titan.
Lido post: https://research.lido.fi/t/rmc-proposal-remove-deprecated-eden-relay-add-titan-relays/8591
Lido SC with relay list: https://etherscan.io/address/0xf95f069f9ad107938f6ba802a3da87892298610e#readContract
=> Add titan relays delete eden

packages/logger/test/unit/logs.test.ts, packages/toolkit/truffle/contracts/contracts_v0.4/proxy.sol, packages/toolkit/truffle/contracts/contracts_v0.4/registry.sol
=> chore: remove redundant words

packages/stakers/src/stakerComponent.ts
Remove `forceRecreate` from  `compose up ` on persist stakers. This setting was introduced to force the recreation of the nimbus pkg when migrating it from monoservice tu multiservice. This migration was already done and its critical to docker by itselve determines if a recreation is required or not!
=> Remove `forceRecreate` from  `compose up ` on persist stakers

packages/admin-ui/src/pages/system/components/Advanced/SshManager/ChangePort.tsx, packages/admin-ui/src/pages/system/components/Advanced/SshManager/ChangeStatus.tsx, packages/admin-ui/src/pages/system/components/Advanced/SshManager/index.tsx, packages/admin-ui/src/pages/system/components/Advanced/SshManager/sshManager.scss
Replaced the SSH enable/disable section in `/system/advanced` with a switch for easier control.
=> Refactor SSH section in `/system/advanced`

packages/admin-ui/src/pages/system/components/AutoUpdates/AutoUpdateRowItem.tsx, packages/admin-ui/src/pages/system/components/AutoUpdates/autoUpdates.scss, packages/admin-ui/src/pages/system/components/Network/HttpsMappings.tsx, packages/admin-ui/src/pages/system/components/Network/https-mapping.scss, packages/admin-ui/src/pages/system/components/volumes.scss
=> System tab mobile fixes

packages/admin-ui/src/pages/support/components/Activity.tsx, packages/admin-ui/src/pages/support/components/PortsStatusTable.tsx, packages/admin-ui/src/pages/support/components/activity.scss, packages/admin-ui/src/pages/support/components/support.scss
=> Support tab mobile fixes

packages/admin-ui/src/pages/installer/components/installer.scss
Enhanced usability in Dappstore's by simplifying mobile view by making the following adjustments:
- DNP card descriptions hidden
- Featured packages hidden
- Categories hidden
=> Dappstore mobile fixes

packages/admin-ui/src/pages/packages/components/Network/HttpsMappings.tsx, packages/admin-ui/src/pages/packages/components/Network/PortsByService.tsx, packages/admin-ui/src/pages/packages/components/Network/https-mapping.scss, packages/admin-ui/src/pages/packages/components/Network/network.scss
Implemented mobile quick-win changes to enhance legibility and usability in the `package/network` tab.
=> `packages` > `network` mobile fix

packages/params/src/params.ts
Add shutter team key to show Shutter pkgs as a trusted package
=> Add shutter trusted key

packages/admin-ui/src/dappnode_styles.scss, packages/admin-ui/src/pages/community/components/CommunityHome.tsx, packages/admin-ui/src/pages/packages/components/PackagesList.tsx, packages/admin-ui/src/pages/repository/components/Eth.tsx, packages/admin-ui/src/pages/repository/components/Ipfs.tsx, packages/admin-ui/src/pages/rollups/components/Optimism.tsx, packages/admin-ui/src/pages/rollups/components/columns.scss, packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/stakers.scss
This PR enhances the DappManager UI with the following updates:
- Updated card styles by removing some borders, decreasing padding, and adjusting the border radius.
- Removed unnecessary cards that were wrapping entire tabs.
=> Card style update

packages/types/package.json
=> bump dappnode types to 0.1.40

packages/admin-ui/src/__mock-backend__/index.ts, packages/dappmanager/src/calls/gatusConfig.ts, packages/dappmanager/src/calls/index.ts, packages/installer/src/installer/writeAndValidateFiles.ts, packages/types/src/routes.ts, packages/utils/src/index.ts, packages/utils/src/writeManifest.ts
Implement backend api calls to configure gatus config file
=> Implement backend api calls

packages/admin-ui/src/light_dark.scss
The alert text color has been adjusted to enhance visibility in dark mode
=> Fix alerts content color

packages/admin-ui/src/components/Searchbar.tsx, packages/admin-ui/src/components/searchbar.scss, packages/admin-ui/src/pages/notifications/NotificationsRoot.tsx, packages/admin-ui/src/pages/notifications/data.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/Inbox.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/NotificationsCard.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/inbox.scss
this PR includes the `Inbox` supath and its components to display the received notifications in the UI
=> Implement notifications `inbox` subpath

packages/dappmanager/src/calls/notifications.ts, packages/notifications/src/index.ts, packages/notifications/src/manifest.ts, packages/types/src/routes.ts
Check is core package before updating notifications settings to determind the manifest path
=> Check is core package before updating notifications settings

packages/notifications/src/manifest.ts
Initialize in single line object to improve redability
=> Initialize in single line object

packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx, packages/admin-ui/src/pages/installer/components/Steps/info.scss
Adjusting the installer view styles during package installation.
=> fix installer view styles

packages/admin-ui/src/components/dnpNameVerified.scss, packages/admin-ui/src/pages/installer/components/installer.scss
Enhancing the styling and responsiveness of featured package cards.
=> featured pkgs card styles

packages/admin-ui/src/__mock-backend__/stakerConfig.ts, packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx, packages/admin-ui/src/pages/stakers/components/StakersRoot.tsx, packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx, packages/daemons/src/stakerConfig/index.ts, packages/dappmanager/src/api/routes/metrics.ts, packages/dappmanager/src/calls/packageInstall.ts, packages/db/src/globalEnvs.ts, packages/db/src/stakerConfig.ts, packages/params/src/params.ts, packages/stakers/README.md, packages/stakers/src/consensus.ts, packages/stakers/src/execution.ts, packages/stakers/src/mevBoost.ts, packages/stakers/src/signer.ts, packages/stakers/src/stakerComponent.ts, packages/types/src/globalEnvs.ts, packages/types/src/stakers.ts, packages/utils/src/stakerUtils.ts
Implementing "Hoodi" network in dappmanager.
Whats left to merge?
- Publish Hoodie Network clients (ECs, CCs, Signer, Brain & MevBoost)
- Add Hoodie Network relays in `MevBoost.tsx` when available
=> Implement "Hoodi" network

packages/admin-ui/src/pages/notifications/tabs/Inbox/Inbox.tsx, packages/types/src/notifications.ts
Filter "error" notifications on `notifications/inbox` subtab.
=> Filter error notifications on `Inbox`

packages/admin-ui/src/pages/stakers/components/StakersRoot.tsx
=> fix Pectra typo in description

packages/admin-ui/src/pages/notifications/tabs/Inbox/Inbox.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/NotificationsCard.tsx, packages/types/src/notifications.ts
Retrieve the notification icon from the notification itself
=> Retrieve notification icon from the notification itself

packages/stakers/src/stakerComponent.ts
Rollback `stakercomponent` to production code. It was temporary changed for testing purposes
=> Rollback `stakercomponent` to production code

packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
Adding relays for Hoodi network
=> Add hoodi relays

packages/admin-ui/src/components/Slider.tsx, packages/admin-ui/src/pages/notifications/tabs/Settings/GatusEndpointItem.tsx, packages/admin-ui/src/pages/notifications/tabs/Settings/ManagePackageNotifications.tsx, packages/admin-ui/src/pages/notifications/tabs/Settings/Settings.tsx
Ensures that the state in `notifications/settings` is correctly updated after modifications are made in the installer notifications step
=> Ensure endpoints state update after pkg installation

packages/notifications/package.json, packages/notifications/src/manifest.ts, packages/notifications/test/unit/notifications.test.ts, packages/types/src/notifications.ts
Implement unit testing to all the edge cases when merging notifications user settings
=> Add unit testing to merge notifications user settings

packages/params/src/params.ts
=> Add ethPandaOps trusted key

packages/installer/test/unit/ethClient/fullNodeEdit.test.ts
=> make mkdir idempotent

notifications.yaml, packages/daemons/src/autoUpdates/sendUpdateNotification.ts, packages/daemons/src/diskUsage/index.ts, packages/dappmanager/src/calls/setStaticIp.ts, packages/schemas/src/schemas/notifications.schema.json, packages/schemas/test/unit/validateSchema.test.ts, packages/types/src/notifications.ts
Add priority field. Allowed values are:
- low
- medium
- high
- critical
=> Add priority field

packages/daemons/src/autoUpdates/sendUpdateNotification.ts, packages/daemons/src/diskUsage/index.ts, packages/dappmanager/src/calls/setStaticIp.ts, packages/schemas/test/unit/validateSchema.test.ts, packages/types/src/notifications.ts
Add status field to notification
=> Add status field to notification

packages/admin-ui/src/pages/notifications/tabs/Inbox/Inbox.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/NotificationsCard.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/inbox.scss
- Category label updated
- Priority labels
- Prettified body
- New notifications unfolded by default
- Supports MD
=> Notifications inbox UI fixes

packages/admin-ui/src/pages/notifications/tabs/Inbox/NotificationsCard.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/inbox.scss
- Implement call to action button in notifications card
- Also fixing mobile styles for `NotificationsCard`
=> Implement call to action button in notifications card

packages/daemons/src/autoUpdates/formatNotificationBody.ts, packages/daemons/src/autoUpdates/sendUpdateNotification.ts, packages/daemons/src/diskUsage/index.ts, packages/daemons/src/hostReboot/index.ts, packages/daemons/src/internetConnection/index.ts, packages/daemons/src/repositoryHealth/index.ts, packages/dappmanager/src/calls/passwordManager.ts, packages/dappmanager/src/calls/setStaticIp.ts, packages/dappmanager/src/calls/wifi.ts
=> Alerts copies review

packages/admin-ui/src/components/IpfsClient.tsx, packages/admin-ui/src/pages/repository/components/Ipfs.tsx
=> Clickable urls ipfs

packages/params/src/params.ts
Add Pol's Address as trusted key
=> Add Pol's Address as trusted key

packages/admin-ui/src/components/welcome/Welcome.tsx, packages/admin-ui/src/components/welcome/features/EnableNotifications.tsx, packages/admin-ui/src/components/welcome/welcome.scss, packages/admin-ui/src/pages/notifications/tabs/Legacy/index.tsx, packages/admin-ui/src/params.ts, packages/dappmanager/src/calls/systemInfoGet.ts, packages/dappmanager/src/initializeDb.ts, packages/types/src/calls.ts
Adding a modal step on the `Welcome` section to warn users about the new notifications feature
=> Welcome notifications modal

packages/admin-ui/src/pages/notifications/tabs/Inbox/Inbox.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/inbox.scss
Adding pagination to the history section in `notifications/inbox`
=> Add pagination to history

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/components/NotificationsMain.tsx, packages/admin-ui/src/pages/notifications/tabs/Inbox/NotificationsCard.tsx, packages/dappmanager/src/calls/index.ts, packages/dappmanager/src/calls/notifications.ts, packages/notifications/src/api.ts, packages/notifications/src/index.ts, packages/types/src/routes.ts
Update seen by correlationId endpoint
=> Update seen by correlationId endpoint

packages/admin-ui/src/layout.scss, packages/admin-ui/src/pages/notifications/tabs/Settings/ManagePackageNotifications.tsx, packages/admin-ui/src/pages/notifications/tabs/Settings/settings.scss
If none of the containers in a package are running, a tooltip appears to warn the user that notifications will not be sent
=> Notifications settings tooltip

packages/dappmanager/src/calls/ipfsClientTargetSet.ts, packages/installer/src/dappnodeInstaller.ts, packages/toolkit/src/repository/repository.ts
Pin ipfs hash with fetch and not wait
=> Pin ipfs hash with fetch

packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
Do not update notis config in frontend, since its already done in the backend
=> Do not update notis config in frontend

packages/params/src/params.ts
Use gateway port in local ipfs
=> Use gateway port in local ipfs

packages/daemons/src/internetConnection/index.ts
Add failure treshold 5 to internet notification
=> Add failure treshold to internet notification

packages/admin-ui/src/pages/packages/components/Network/index.tsx, packages/admin-ui/src/pages/packages/components/Network/network.scss, packages/dockerApi/src/list/parseContainerInfo.ts, packages/types/src/calls.ts
Add private IP in the backend so it can be displayed in the frontend
=> Add private IP in the backend

packages/admin-ui/public/offline.html, packages/admin-ui/public/vpnoff.html, packages/admin-ui/src/pages/notifications/tabs/Devices/DevicesSubs.tsx, packages/admin-ui/src/pages/system/components/App/PwaInstallCards.tsx
=> VPN off fix

packages/stakers/src/consensus.ts
Implement `getBackupIfActive` to update validator env `BACKUP_BEACON_NODES` when changing the consensus client in the stakers
=> Implement `getBackupIfActive`

packages/dappmanager/src/index.ts
Implement handlers for unhandled promise rejections and uncaught exceptions to improve error logging and application stability. Additionally, ensure graceful shutdown on SIGINT.
=> Add error handling for unhandled rejections and exceptions

packages/admin-ui/src/components/sidebar/SideBar.tsx
In the subroutes of the sidebar's routes, the items were not shown as active
=> sidebar active item fix

packages/admin-ui/src/__mock-backend__/index.ts, packages/admin-ui/src/components/PwaRequirementsWrapper.tsx, packages/admin-ui/src/components/pwaRequirementsWrapper.scss, packages/admin-ui/src/hooks/PWA/usePwaRequirements.ts, packages/admin-ui/src/params.ts, packages/dappmanager/src/calls/pwaRequirementsGet.ts, packages/params/src/params.ts, packages/types/src/routes.ts
Adds pwa checks in `.private` domain
=> PWA checks report

.github/instructions/api-calls.instructions.md
Add copilot instructions for api calls so its easier to implement new functionalities using agent
=> Add copilot instructions for api calls
