- build/src/src/calls/createGetUserActionLogs.js
- build/src/src/calls/createInstallPackage.js
- build/src/src/calls/createListPackages.js
- build/src/src/calls/createManagePorts.js
- build/src/src/calls/createRemovePackage.js
- build/src/src/calls/createRestartPackage.js
- build/src/src/calls/createRestartPackageVolumes.js
- build/src/src/calls/createTogglePackage.js
- build/src/src/calls/createUpdatePackageEnv.js
- build/src/src/eventBus.js
- build/src/src/index.js
- build/src/src/logUserAction.js
- build/src/src/logs.js
- build/src/src/params.js
This should be useful to help assist user on errors. It implemented a subscription to have to receive the full list of logs only once. Linked to https://github.com/dappnode/DNP_ADMIN/pull/92
> Track and emit user interaction logs

- build/src/src/modules/getManifest.js
- build/src/src/modules/ipfs/ipfsTasks.js
- build/src/test/modules/getManifest.test.js
File size over a limit (100KB)
File not containing a valid json (it's an image or binary)
JSON not parsable (syntax error)
Parsable but the manifest is broken (no image hash)
> Show specific errors if the manifest is not valid

- build/src/src/calls/installPackage.js
- build/src/src/modules/packages.js
- build/src/test/calls/installPackage.test.js
- build/src/test/modules/packages.test.js
If you install DNP_A which depends on DNP_B, it is very possible that DNP_A download succeeds but DNP_B doesn't because it's not available or it hasn't propagated yet. If that happened, DNP_A will be loaded and it's manifest and docker-compose will be changed. But the install will error.
To fix this dangerous intermediate state, now the installation is split in 3 steps:
1. Download: download all of DNP's images. If a single image is not available the installation will stop at this stage.
2. Load: load the docker image and overwrite the manifest and docker-compose of each DNP.
3. Run: docker-compose up each DNP
> dont load DNP until all downloads are successful

- build/Dockerfile
- build/src/package.json
- build/src/src/calls/cleanCache.js
- build/src/src/calls/index.js
- build/src/src/calls/installPackage.js
- build/src/src/db.js
- build/src/src/modules/dappGet/aggregate/index.js
- build/src/src/modules/dappGet/basic.js
- build/src/src/modules/dappGet/index.js
- build/src/src/modules/dappGet/utils/shouldUpdate.js
- build/src/src/modules/docker/dockerSafe.js
- build/src/src/modules/packages.js
- build/src/src/params.js
- build/src/src/utils/getPath.js
- build/src/src/watchers/chains/index.js
- build/src/test/calls/installPackage.test.js
- build/src/test/modules/dappGet/basic.test.js
- build/src/test/modules/packages.test.js
- build/src/yarn.lock
- dappnode_package.json
- docker-compose.yml
- Prevent DNP installation dangerous intermediate stage on download error https://github.com/dappnode/DNP_DAPPMANAGER/issues/205
- Fix bitcoin's API RPC typo. Fixes https://github.com/dappnode/DNP_ADMIN/issues/268
- Do not downgrade on dappget. Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/202
- Fix dependency import order, which causes the lockPorts module to crash. Fixed https://github.com/dappnode/DNP_ADMIN/issues/281
- Add clean DAPPMANAGER's cache RPC. Fixes #210
> v0.2.2 Release

- build/src/src/utils/configFiles.ts
- build/src/src/utils/dockerComposeParsers.ts
- build/src/test/utils/configFiles.test.ts
- build/src/test/utils/dockerComposeParsers.test.ts
- dappnode_package.json
- docker-compose.yml
- Make sure all docker volume paths are normalized before applying logic to them. If the developer slightly changes the path of a volume, this can be merged with a pre-existing path and docker consider the compose bad and freeze the package. 
```
from: ethchaindnpdappnodeeth_geth:/root/.ethereum/
to  : ethchaindnpdappnodeeth_geth:/root/.ethereum
```
> v0.2.13 Release - Volume path hotfix

- build/src/src/db/index.ts
- build/src/src/db/systemFlags.ts
- build/src/src/initializeDb.ts
More defensive approach where if only if all is good the VPN will not be reseted.
---
To test, do a VPN -> DAPPMANAGER migration twice and make sure you see the correct logs
If a migration HAD to happen
```
Added global ENVs and restarted the VPN
```
If the migration has already happened
```
Globals ENVs are already set in the VPN environment
```
> Check if global envs are in the VPN environment

- build/src/src/db/index.ts
- build/src/src/db/systemFlags.ts
- build/src/src/index.ts
- build/src/test/fetchExternalData.test.int.ts
Fixes issue where after a restore or second install .env are not migrated, causing issues.
> Remove env files migrated flag

- build/src/src/modules/docker/dockerCommands.ts
- build/src/src/modules/docker/shell.ts
- build/src/src/utils/shell.ts
Increases the limit from 200Kb - 1MB (documentation is not clear) to 10MB
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/302
> Increase max buffer limit for docker logs

- build/src/hostScripts/migrate_volume.sh
During a test migration, the resulting docker volumes dir looked like
```
[root@DAppNodeLion:/var/lib/docker/volumes]# tree -L 2 openethereumdnpdappnodeeth_data/
openethereumdnpdappnodeeth_data/
├── _data
│   ├── cache
│   ├── chains
│   ├── keys
│   ├── network
│   └── signer
└── dncore_ethchaindnpdappnodeeth_data
└── _data
```
Seems that the migration moved the directory `dncore_ethchaindnpdappnodeeth_data` to `openethereumdnpdappnodeeth_data` but since this last directory already existed, the first directory was placed inside instead of renamed.
Make sure the destination directory does not exist. @vdo:
- Is there an option of a flag for `mv` to prevent the behavior of placing the from a directory inside the target directory?
- Is this the best policy? Should we return an error and …
> Prevent directories from merging into destination

- build/src/src/modules/docker/dockerApi.ts
- build/src/src/modules/docker/utils.ts
- build/src/test/modules/docker/utils.test.ts
When fetching logs from the API, each line is prefixed by a Header
It is encoded on the first 8 bytes like this:
header := [8]byte{STREAM_TYPE, 0, 0, 0, SIZE1, SIZE2, SIZE3, SIZE4}
`STREAM_TYPE` can be:
-   0: stdin (will be written on stdout)
-   1: stdout
-   2: stderr
`SIZE1, SIZE2, SIZE3, SIZE4` are the 4 bytes of
the uint32 size encoded as big endian.
Example:
```
\u0001\u0000\u0000\u0000\u0000\u0000\u0000O\u001b[32minfo\u001b[39m Starting cache DB cacheDbPath: \"/usr/src/app/data/cachedb.json\"\n\n
\u0001\u0000\u0000\u0000\u0000\u0000\u0000L\u001b[32minfo\u001b[39m IPFS HTTP API httpApiUrl: \"http://ipfs.dappnode:5001/api/v0\"\n
\u0001\u0000\u0000\u0000\u0000\u0000\u0000X\u001b[32minfo\u001b[39m IPFS Cluster HTTP API clusterApiUrl: \"http://ipfs-cluster.dappnode:9094\"\n …
```
> Remove prepended bytes added to each line by the docker API

- build/src/src/registerHandler.ts
- build/src/src/watchers/autoUpdates/index.ts
- build/src/src/watchers/autoUpdates/updateMyPackages.ts
- build/src/src/watchers/chains/index.ts
- Control chain watcher log noise
- Reduce auto-update log noise on expected errors
- Print only warning without stack in WAMP RPC calls on EthProviderError
> Reduce log noise

- build/src/src/ethForward/index.ts
- build/src/src/ethForward/views/base.ts
- build/src/src/utils/url.ts
- Fix `http-proxy` binding issue that prevents resolving webs. The source code would fail since an internal use of `this` which was not binded failed
- Report ethForward ProxyErrors with more detail. Make sure the full original stack trace can be fetched by the user easily.
- Make sure only one HTML is written in the ethForward response. Fixed a typo that wrote data to the response stream after closing it
> Fix multiple ETHFORWARD issues

- build/src/src/modules/legacy/removeLegacyBindVolume.ts
- build/src/src/params.ts
- build/src/src/watchers/nsupdate/index.ts
- Remove new legacy bind volume
- When the BIND is re-created, run `nsupdate` on all domains
> BIND issue patch

- build/src/src/modules/legacy/removeLegacyBindVolume.ts
- build/src/src/params.ts
- build/src/src/watchers/nsupdate/index.ts
- dappnode_package.json
- docker-compose.yml
- Remove new and old legacy bind volume
- When the BIND is re-created, run nsupdate on all domains
- Delay nsupdate call when bind is restarting
- Retry nsupdate calls
- Bump versions
> Bind hotfix - multiple issues

- build/src/src/db/index.ts
- build/src/src/watchers/autoUpdates/index.ts
- build/src/src/watchers/chains/index.ts
- build/src/src/watchers/diskUsage/index.ts
- build/src/src/watchers/dyndns/index.ts
- build/src/src/watchers/index.ts
- build/src/src/watchers/natRenewal/index.ts
- build/src/src/watchers/nsupdate/index.ts
Prevent running unexpected code when just importing a module.
- Do not run watchers code in the body of the module
> Run functions only in the index

- packages/admin-ui/server-mock/data/dnps/lightningNetwork.ts
- packages/admin-ui/server-mock/data/dnps/openEthereum.ts
- packages/admin-ui/server-mock/methods/index.ts
- packages/admin-ui/server-mock/methods/pending.ts
- packages/admin-ui/server-mock/methods/volumes.ts
- packages/admin-ui/src/common/types.ts
- packages/admin-ui/src/pages/packages/components/Info/Vols.tsx
- packages/admin-ui/src/pages/packages/components/Info/index.tsx
- packages/admin-ui/src/pages/packages/pages/ById.tsx
- packages/dappmanager/src/calls/packageGet.ts
- packages/dappmanager/src/calls/volumesGet.ts
Fetching volume data is very expensive as it uses `docker system df` underneath. UI should consume data from the package and volume endpoint and merge it in the info display.
> Move volume data fetching data to volumeGet method

- packages/dappmanager/src/api/index.ts
- packages/dappmanager/src/api/routes/publicPackagesData.ts
`GET`, no credentials
```
/public-packages/:id?
```
Returns
```ts
{
name: string;
version: string;
ip?: string;
state: string;
}
```
> Expose public packages endpoint

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/calls/packageRemove.ts
- packages/dappmanager/src/calls/packageRestart.ts
- packages/dappmanager/src/calls/packageStartStop.ts
- packages/dappmanager/src/db/coreUpdate.ts
- packages/dappmanager/src/modules/compose/labelsDb.ts
- packages/dappmanager/src/modules/docker/listContainers.ts
- packages/dappmanager/src/modules/docker/restartPackage.ts
- packages/dappmanager/src/modules/docker/restartPackageVolumes.ts
- packages/dappmanager/src/modules/docker/utils.ts
- packages/dappmanager/src/modules/installer/getInstallerPackageData.ts
- packages/dappmanager/src/modules/installer/rollbackPackages.ts
- packages/dappmanager/src/modules/installer/runPackages.ts
- packages/dappmanager/test/calls/packageRemove.test.ts
- packages/dappmanager/test/integration/dnpLifecycle.test.int.ts
- packages/dappmanager/test/integration/resilienceFeatures.test.int.ts
- packages/dappmanager/test/testUtils.ts
**Added timeout parameter to:**
- `dockerComposeUp():` called in restartPackage, restartPackageVolumes, rollbackPackages, runPackages, and tests.
- `dockerComposeDown():` called in packageRemove and tests.
- `dockerComposeStop():` no needed to change anything in the background since it is not called anywhere.
- `dockerStop():` called in packageStartStop and tests.
**Added new funtion:**
- `getDockerTimeoutMax():` this function returns the maximum timeout value from all the docker packages, in order to be used in the corersponding place.
**Other changes**
These changes were implemented after running yarn build
- Due to the delete of the timeout parameter in some functions in the previous commit, there have appeared some errors due to functions calls with this parameter. There have been …
> Pablo docker timeout

- packages/admin-ui/server-mock/index.ts
- packages/dappmanager/src/api/routes/index.ts
- packages/dappmanager/src/api/routes/sign.ts
- packages/dappmanager/src/api/routes/signFromPackage.ts
- packages/dappmanager/src/api/startHttpApi.ts
- packages/dappmanager/src/params.ts
- packages/dappmanager/src/utils/sign.ts
- packages/dappmanager/test/utils/sign.test.ts
Exposes endpoint to sign arbitrary data from other DAppNode packages.
```
POST /sign?data=some-payload
```
Unless the request comes from a container of a DAppNode package, it will be rejected
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/473
> Add sign endpoint

- packages/admin-ui/src/pages/packages/components/Logs.tsx
**Main changes**
- New useState in _/admin-ui/src/pages/packages/components/Logs.tsx_: the new useState has been created to track whenever the serviceName selected has changed.
**Result**
Now the logs changed to display the new serviceName selected, even with the option "Auto refresh logs" disabled
> Fix logs UI bug with multi-services packages

- packages/dappmanager/src/calls/packageRestart.ts
- packages/dappmanager/src/calls/packageStartStop.ts
- packages/dappmanager/src/modules/docker/api/container.ts
Right now `packageRestart` recreates the containers which not intuitive.
> Make packageRestart call docker restart

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/modules/compose/unsafeCompose.ts
Allows docker-compose service keys that may be useful but don't pose any obvious thread.
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/551
> Allow safe compose keys

- packages/admin-ui/src/pages/packages/actions.ts
- packages/admin-ui/src/pages/packages/components/DnpSpecific/DappmanagerDnpDappnodeEth.tsx
- packages/admin-ui/src/pages/packages/components/Info/ContainerList.tsx
- packages/admin-ui/src/pages/packages/components/Info/RemovePackage.tsx
- packages/admin-ui/src/pages/packages/components/Info/VolumesList.tsx
- packages/admin-ui/src/pages/system/actions.ts
- packages/admin-ui/src/pages/system/components/Advanced/SshManager/ChangeStatus.tsx
- packages/admin-ui/src/pages/system/components/Identity.tsx
- packages/admin-ui/src/pages/system/components/PowerManagment.tsx
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/548
**Changes**
- Added confirmation dialog to: 
- SSH service when user attemps to disable it
- Wifi package when user attemps to stop it.
**On both cases there will be shown a warming message advicinf user that he/she may loose access**
**Results**
**SSH**
**WIFI**
> Add alert banners to dangerous actions

- packages/admin-ui/src/__mock-backend__/fetchPkgsData.ts
- packages/admin-ui/src/common/types.ts
- packages/admin-ui/src/pages/system/components/SystemUpdate/SystemUpdateDetails.tsx
- packages/admin-ui/src/services/coreUpdate/actions.ts
- packages/admin-ui/src/services/coreUpdate/selectors.ts
- packages/dappmanager/src/calls/fetchCoreUpdateData.ts
- packages/dappmanager/src/daemons/autoUpdates/formatNotificationBody.ts
- packages/dappmanager/src/daemons/autoUpdates/index.ts
- packages/dappmanager/src/daemons/autoUpdates/sendUpdateNotification.ts
- packages/dappmanager/src/daemons/autoUpdates/updateMyPackages.ts
- packages/dappmanager/src/daemons/autoUpdates/updateSystemPackages.ts
- packages/dappmanager/src/daemons/telegramBot/commands.ts
- packages/dappmanager/src/db/notification.ts
- packages/dappmanager/test/integration/fetchExternalData.test.int.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/550
Extends the auto-updates daemon to also send new version available notifications
1. Check if new version available
2. Send notification if hasn't sent notification yet
3. Auto-update package if auto-updates are enabled for that package
> Send notification on new package version available

- packages/admin-ui/src/api/mock/routes.ts
- packages/admin-ui/src/api/routes/index.ts
Partially fixes https://github.com/dappnode/DAppNode/issues/261
This extra attribute is only meant for testing. In a production context it will turn a failed download attempt into a file that does not exist
> Remove typo on a attribute

- packages/admin-ui/src/pages/devices/components/DeviceDetails.tsx
We are changing the position of the QR code. The button is under the inputs : username and admin password now. Furthermore, when the qr image is showed is under the admin username and password too.
> Change the position of the QR box on devices page

- packages/admin-ui/src/components/navbar/navbarItems.ts
- packages/admin-ui/src/pages/devices/components/DevicesHome.tsx
- packages/admin-ui/src/pages/devices/data.ts
- packages/admin-ui/src/pages/index.ts
Fixes #459
We have changed the name devices for "VPN", we have included a description text due to what you should set up on this section. 
I have not changed the folder name admin-ui/src/pages/devices for admin-ui/src/pages/vpn. Maybe it would be better to understand the structure of the project after this modification.
> Change devices tab name to VPN

- docker-compose.yml
- packages/dappmanager/.env
- packages/dappmanager/src/calls/systemInfoGet.ts
- packages/dappmanager/src/modules/ethClient/ethersProvider.ts
- packages/dappmanager/src/params.ts
- test/test_integration.sh
Adds two ENV variables
- `ETH_MAINNET_RPC_URL_OVERRIDE`: If defined the DAPPMANAGER will always use this rpc URL to fetch package data
- `ETH_MAINNET_RPC_URL_REMOTE`: Defines the remote node, only used under certain conditions
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/619
> Improve usability of ETH_MAINNET_RPC_URL variables

- packages/admin-ui/src/__tests__/pages/installer/parsers/setupWizardParser.test.ts
- packages/admin-ui/src/common/types.ts
- packages/admin-ui/src/pages/installer/parsers/formDataParser.ts
Add this feature:  this Setup wizard: Share variables with multiple services #633 
I created this package to test it where we have a package using both ways to define variables:
You can install it: 
Release hash : /ipfs/QmYH3vbqN4bt3eDpbBp4Gcn72CM61LVR9Q2drTviZuLTcX
http://my.dappnode/#/installer/%2Fipfs%2FQmYH3vbqN4bt3eDpbBp4Gcn72CM61LVR9Q2drTviZuLTcX
The format is the following:
```yaml
fields:
- id: ethereum_url
target:
type: environment
name: ETHEREUM_URL
services: [service1, service2]
```
> Share variables with multiples services

- packages/dappmanager/src/modules/dockerUpdate/utils.ts
- packages/dappmanager/src/modules/https-portal/migration.ts
- packages/dappmanager/src/utils/sanitizeVersion.ts
- packages/dappmanager/test/integration/migrationCompose/migration.test.int.ts
Error in migration process:
```
ERROR [modules/https-portal/migration:63] Error adding alias to container DAppNodeCore-dappmanager.dnp.dappnode.eth TypeError: Cannot read property 'aliases' of undefined
at migrateCoreNetworkAndAliasInCompose (/usr/src/app/webpack:/src/modules/https-portal/migration.ts:121:20)
```
> Fix bug in migration: check if aliases is defined in compose

- packages/admin-ui/src/pages/packages/components/FileManager/index.tsx
- packages/admin-ui/src/pages/packages/components/Network/index.tsx
The packages > network view is a bit overloaded and confusing. Splitting it into multiple cards give it some breathing room. For consistency, the files view is also splitted
> Split packages view

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/modules/release/getRelease.ts
Unused and now replaced by HTTPs portal
> Remove manifest.ssl property

- packages/dappmanager/src/calls/notificationsGet.ts
- packages/dappmanager/src/db/cache.ts
- packages/dappmanager/src/db/dbCache.ts
- packages/dappmanager/src/db/dbFactory.ts
- packages/dappmanager/src/db/dbMain.ts
- packages/dappmanager/src/db/ethClient.ts
- packages/dappmanager/src/db/fileTransferPath.ts
- packages/dappmanager/src/db/notification.ts
- packages/dappmanager/src/db/package.ts
- packages/dappmanager/src/db/system.ts
- packages/dappmanager/src/db/ui.ts
- packages/dappmanager/test/daemons/ethMultiClient/index.test.ts
- Use named arguments to clarify the meaning of each argument
- Do key concatenation on the factory by default
- Expose extra method `getAll()`
- Rename to better name
> Refactor db dynamicKeyValidate

- packages/admin-ui/src/__mock-backend__/data/dnps/lightningNetwork.ts
- packages/admin-ui/src/common/routes.ts
- packages/admin-ui/src/common/types.ts
- packages/admin-ui/src/pages/dashboard/components/ChainCard.tsx
- packages/admin-ui/src/pages/dashboard/components/Dashboard.tsx
- packages/admin-ui/src/pages/dashboard/components/PackageUpdates.tsx
- packages/admin-ui/src/pages/dashboard/components/dashboard.scss
- packages/dappmanager/src/calls/packagesGet.ts
- packages/dappmanager/src/db/dbFactory.ts
- Extend `packagesGet()` call to return last known version added in https://github.com/dappnode/DNP_DAPPMANAGER/pull/686
- Show a list of packages to update with an update button
- Button re-directs to install package
**Future todo**:
- Install all button
- Should also add an install queue system so not everything is updated at once
In big sreens
> Add package updates view in dashboard

- packages/dappmanager/src/daemons/autoUpdates/updateMyPackages.ts
Fixes a regression introduced in DAPPMANAGER version `v0.2.38` which prevents auto-updating non-system packages if some package previous to it is already updated.
https://github.com/dappnode/DNP_DAPPMANAGER/blob/845a220da45754d2455a18692178e23d6c55258f/packages/dappmanager/src/daemons/autoUpdates/updateMyPackages.ts#L42
Introduced in commit: https://github.com/dappnode/DNP_DAPPMANAGER/pull/563/commits/845a220da45754d2455a18692178e23d6c55258f#diff-ad2a1d84e4dc97132ac60340f7678d281cf6fa16cb18f6f2f61ce5ab503a073fR42
Depending on the ordering of the containers returned by the docker API this bug may prevent all non-core packages from being updated or only some.
---
I've reviewed all return statements in the repo and there's no other instance of a similar bug
> Fix auto updates return in loop bug

- docker-compose.yml
Adding `my.dappnode` alias is necessary for DNS resolution
> Adding proper alias for dappmanager

- packages/dappmanager/src/domains.ts
- packages/dappmanager/src/modules/compose/unsafeCompose.ts
- packages/dappmanager/src/params.ts
- packages/dappmanager/test/modules/releaseSpecs/dappmanager/docker-compose.parsed.yml
- packages/dappmanager/test/modules/releaseSpecs/dappmanager/docker-compose.yml
- Add `my.dappnode` alias to dappmanager
- Keep custom aliases for core packages
> Add unique alias for dappmanager Admin UI

- packages/dappmanager/src/modules/nsupdate/utils.ts
- packages/dappmanager/test/modules/docker/dockerApiSamples/containers.ts
- packages/dappmanager/test/modules/docker/parseContainerInfo.test.ts
- packages/dappmanager/test/modules/nsupdate/utils.test.ts
Fixes a regression introduced in https://github.com/dappnode/DNP_DAPPMANAGER/pull/636 which prevents the DAPPMANAGER from updating the root domain of packages to the bind
> Fix root domain nsupdate

- packages/dappmanager/src/daemons/autoUpdates/updateMyPackages.ts
- packages/dappmanager/src/params.ts
Allows to auto-update the `https.dnp.dappnode.eth` package not being a dependency of `core.dnp.dappnode.eth`
> Allow to auto-update some core packages

- packages/dappmanager/src/modules/https-portal/exposable/predefined.ts
Fix the little error that affects including owncloud package as a predefined exposable service for HTTPS.
Fix #739
> Fix owncloud predefined exposasable service

- packages/admin-ui/src/pages/vpn/components/VpnHome.tsx
- packages/admin-ui/src/pages/vpn/index.ts
Sort OpenVPN and Wireguard by placing the first the installed package. If both are installed or none, keep the same order. This will make users land first on the VPN option they have already installed.
> Sort VPN subpages by isInstalled

- packages/dappmanager/src/ethForward/index.ts
- packages/dappmanager/src/ethForward/ipfsProxy.ts
- packages/dappmanager/src/modules/docker/list/parseContainerInfo.ts
- packages/dappmanager/src/params.ts
- packages/dappmanager/src/utils/distributedFile.ts
- packages/dappmanager/test/ethForward/ipfsGatewayProxy.test.ts
- packages/dappmanager/test/integration/fetchRelease.test.int.ts
- packages/dappmanager/test/modules/docker/parseContainerInfo.test.ts
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/760
Attaches a new HTTP proxy to the Ethfoward where requests with a pathname that starts with `ipfs-gateway-proxy` will be proxied to ipfs.dappnode:8080/ipfs
Re-uses the same code from the Ethforward, it's error handling and error views
---
I have not tested it yet on a real DAppNode
> Add IPFS gateway proxy

- packages/dappmanager/src/daemons/avahi/index.ts
- packages/dappmanager/src/daemons/index.ts
- packages/dappmanager/src/utils/shell.ts
- Use child_process.spawn, has not stream buffer limits nor timeouts
> Improve avahi spawner

- packages/admin-ui/src/__mock-backend__/httpsPortal.ts
- packages/admin-ui/src/common/routes.ts
- packages/admin-ui/src/pages/system/components/Network/HttpsMappings.tsx
- packages/dappmanager/src/calls/httpsPortal.ts
Containers on restart may loose it mapping in the https portal. A button to refresh the mapping should fix the issue
> HTTPs portal refresh button 

- packages/dappmanager/src/modules/chains/drivers/ethereum2Prysm.ts
When the code of chains was done, DAppNode packages did not have multi services. The "chain method" obtains the container IP where it does the pull of the data using the index 0, instead of searching this service by its name. This PR solves this problem for PRYSM, but it would be interesting to create an issue and solving how this task is done for the other chains.
To test this fix:
1. Install pyrmont/prysm 
2. Change the graffiti
3. Look if there is an error on the card chain of the dashboard view.
> Fix the visual bug of prysm and pyrmont package

- packages/dappmanager/src/modules/docker/list/parseContainerInfo.ts
- packages/dappmanager/test/modules/docker/parseContainerInfo.test.ts
An old function inside the docker list response parsing assumed containers' name has a specific format only valid for single service packages. This PR makes the function a bit smarter.
Packages not installed through the DAPPMANAGER but coming from the ISO directly do not have labels. Relying on them is not a good idea so we should move away from them eventually.
> Parse dnpName considering multi-service

- packages/dappmanager/src/domains.ts
- packages/dappmanager/src/modules/release/getRelease.ts
Otherwise packages with a single service whose serviceName !== dnpName won't get the root domain
> Make single service isMain = true

- packages/admin-ui/src/pages/wifi/components/wifi/WifiStatus.tsx
Stopped is a user action, totally expected. The log should be something to show when something unexpected happened, this means a wifi status different than running and stopped
> Do not show wifi log when wifi is running OR stopped

- packages/dappmanager/src/params.ts
In new DAPPMANAGER version it will invite users to install vpn.dnp.dappnode.eth if it's not installed.
Requires https://github.com/dappnode/DNP_CORE/pull/71
Closes https://github.com/dappnode/DNP_DAPPMANAGER/issues/809
Closes https://github.com/dappnode/DNP_DAPPMANAGER/issues/802
> Remove VPN as mandatory dependency

- packages/dappmanager/src/db/dbFactory.ts
Otherwise if the value is a boolean and the default value is true, `db.value.get()` will always return true
> Do a nullish compare on db.get()

- packages/admin-ui/src/__mock-backend__/index.ts
- packages/admin-ui/src/common/routes.ts
- packages/admin-ui/src/pages/support/components/Ports.tsx
- packages/admin-ui/src/pages/support/components/PortsStatusTable.tsx
- packages/dappmanager/src/calls/index.ts
- packages/dappmanager/src/calls/natRenewal.ts
- packages/dappmanager/src/calls/upnpPortsOpen.ts
- packages/dappmanager/src/daemons/natRenewal/index.ts
- packages/dappmanager/src/db/upnp.ts
- packages/dappmanager/src/modules/upnpc/upnpcCommand.ts
- packages/dappmanager/src/utils/getInternalIp.ts
- packages/dappmanager/src/utils/getLocalIp.ts
Added button in **support > ports** to attemp to open ports using UPnP. This may be useful if the `NAT RENEWAL` daemon fails so the user would be able to open ports using UPnP manually.
> Button to open ports using UPnP

- packages/dappmanager/hostScripts/detect_fs.sh
Fixes #837
With these changes selecting and using LVM volumes works:
> Don't crash when installing onto LVM

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/modules/compose/unsafeCompose.ts
Allow docker-compose service pid property. Only allow `service:*` values for security reasons
Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/857
> Allow docker-compose service pid property

- packages/admin-ui/src/pages/wifi/components/wifi/WifiStatus.tsx
Just a typo. Hotspot was misspelled as hostpot.
> Fix hostpot typo

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/modules/compose/unsafeCompose.ts
It is safe to add, shouldn't have any negative impact on existing package.
> Add depends_on key to compose service whitelist

- packages/admin-ui/src/pages/packages/components/Info/Links.tsx
- packages/admin-ui/src/pages/packages/components/Info/index.tsx
This button aims to redirect users to the **bugs** URL provided in the package manifest, in order to move support from dappnode to upstream projects.
UIX
> Add bug link on packages view

- packages/admin-ui/src/params.ts
VPN is not longer a mandatory core package, it can be removed/installed on demmand. For this reason it must be removed from the support check
> removed vpn from mandatory package

- packages/admin-ui/src/__mock-backend__/data/dnps/lightningNetwork.ts
- packages/admin-ui/src/pages/packages/components/Info/PackageSentData.tsx
- packages/admin-ui/src/pages/packages/components/Info/packageSentData.scss
- packages/admin-ui/src/utils/isLink.ts
If the data sent from the container to the dappmanager starts with **http** then render it as a Link. Related to https://github.com/dappnode/DAppNodePackage-prysm-prater/issues/19
Consider having a hardcoded key instead for links/URLs
> Render link in package sent data

- packages/admin-ui/src/pages/packages/components/Info/PackageSentData.tsx
There was used a link with the full url path, instead it should be used only the package ENS domain
> Fix link in dataSent feature

- packages/dappmanager/src/modules/release/getManifest.ts
- packages/dappmanager/test/integration/ipfs/ipfsGateway.test.int.ts
- packages/dappmanager/test/integration/releaseFormat.test.int.ts
- packages/dappmanager/test/integration/signedRelease.test.int.ts
- packages/dappmanager/test/modules/ipfs/index.test.int.ts
The IPFS method `dag/export/ does not allow to use IPFS hashes in path format, i.e:
`QmXcZnd6euc3wfQqwb8m9r2hWuefrS6cPic29k5VZz7S6d/dappnode_package.json`
There must be used the CID of the file
> Fix get manifest from IPFS remote

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/calls/httpsPortal.ts
- packages/dappmanager/src/modules/installer/exposeByDefaultHttpsPorts.ts
- packages/dappmanager/src/modules/installer/runPackages.ts
Expose HTTPS ports defined in the manifest with `exposedByDefault` as `true` 
e.g
``` 
exposable: {
"name": "Geth JSON RPC",
"description": "JSON RPC endpoint for Geth mainnet",
"serviceName": "beacon_chain",
"port":  8545,
"exposedByDefault": true
}
```
> Expose https ports by default on installation

- packages/dappmanager/src/calls/packageInstall.ts
- packages/dappmanager/src/modules/installer/ensureIsNotValidatorLegacyPackage.ts
- packages/dappmanager/src/params.ts
The dappstore will not allow to install older versions of package however users still can use hashes to install validator package previous to the remote signer support.
This PR checks a hardcoded version for the Prysm prater to ensure it supports remote signer. Prysm mainnet and Gnosis is on the roadmap
> Ensure not installing legacy validators

- packages/dappmanager/src/modules/dappGet/aggregate/aggregateDependencies.ts
Do not allow to continue a package installation if there was an error aggregating dependencies
> throw error on aggregateDependencies

- packages/dappmanager/src/params.ts
Reorder params from web3signer and client legacy:
```
web3SignerClientsDnpNames: [
{
clientDnpName: "prysm-prater.dnp.dappnode.eth",
web3SignerDnpName: "web3signer-prater.dnp.dappnode.eth"
}
],
```
> Fix map order

- packages/dappmanager/src/modules/installer/ensureEth2MigrationRequirements.ts
- packages/dappmanager/src/params.ts
Fix a wrong check to not allow installing web3signer while having a legacy client installed in dappnode.
> Fix wrong check when installing web3signer

- packages/dappmanager/hostScripts/lvm.sh
It was required to add the -y flag when the pvcreate command is executed.
If you try to expand the hard disk of your dappnode and the disk you want to expand contains something, it appears a warning message and the script stop working.
It's required to add the -y in the line where the command pvcreate is used.
Use the expand disk function.
> Fix lvm.sh file

- packages/dappmanager/src/modules/ipfs/Ipfs.ts
- packages/dappmanager/src/modules/release/ipfs/downloadRelease.ts
Ipfs was pinning content on every visit to the dappstore by the user. This is fine when using IPFS local but not when using IPFS remote.
Only pin when using IPFS local.
- Test that visiting the dappstore using IPFS local does pins the content
- Test that visiting the dappstore using IPFS remote does not pin the content
> Only pin if is ipfs local

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/modules/chains/drivers/index.ts
- packages/dappmanager/src/modules/chains/getChainDriverName.ts
- packages/dappmanager/src/modules/compose/labelsDb.ts
- packages/dappmanager/test/modules/compose/labelDb.test.ts
- packages/dappmanager/test/modules/docker/parseContainerInfo.test.ts
The changes implemented to get dynamically the chain driver based on port and service name was breaking the old hardcoded way of defining the chain.
Fix chain driver. There was referring to `.driver` instead of `.chain`. This should be compatible with both methods:
```
"chain" : "ethereum2-beacon-chain"
```
and 
```
"chain": {
"driver": "ethereum-beacon-chain",
"serviceName": "beacon-chain",
"portNumber": 3500
}
```
Install valid dappnode packages with both options in the manifest and maks sure that the chain is shown in the dashboard
> Fix chain driver

- packages/dappmanager/src/modules/chains/getChainDriverName.ts
knownChains are a boostrap mechanism to enable the chains feature before we released versions for all packages. That's the only purpose of that file, not to add new packages that can just have the chain property in the manifest.
Instead add "chain" property in your package, like https://github.com/dappnode/DAppNodePackage-prysm/pull/65. Full docs: https://docs.dappnode.io/developers/manifest-reference#chain
I've checked every package manually to ensure all of them define the chain property. All are fine except https://github.com/dappnode/DAppNodePackage-prysm/pull/65
```ts
const knownChains: { [dnpName: string]: ChainDriver } = {
// Has `"chain": "ethereum"` in v0.2.12
"openethereum.dnp.dappnode.eth": "ethereum",
// Has `chain "ethereum"` in v0.3.14
"ropsten.dnp.dappnode.eth": "ethereum", …
```
> Remove properties from knownChains

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/modules/compose/unsafeCompose.ts
Add the `security_opt` to the docker compose safe keys. See https://docs.docker.com/compose/compose-file/#security_opt
This is necessary to install the web3signer package which has included this key to avoid an environment error
Add the key
Test installation package works as expected
> add security_opt

- packages/admin-ui/src/utils/validation.ts
fixes #1024
Fixes #1024 (by making the max WPA passphrase character length an argument in the validator implemented the same as the minimum is, makes it so that this endless loop from #1024 to not be a possible situation by properly setting the max length, a warning appears when it exceeds 63 characters as the WPA standard describes, and it is baked into the validation for password strength function keeping it so that the warning not just pops up over 63 characters, but even when the password is properly copied into the second field, it shows a match, but the change password button remains inactive until the passphrase meets the strong password requirements, which now include the max character length in addition to the minimum.
Add new variable for the max length of 63 characters and …
> Set max WPA characters for passphrase

- packages/dappmanager/src/initializeDb.ts
The ipfs gateway endpoint http://ipfs.dappnode.io:8081 is being deprecated by https://gateway.ipfs.dappnode.io
Migrate the old dappnode ipfs gateway with the new one ONLY if is set to such endpoint
- Having the old ipfs endpoint, after the update it should have been changed by the new one
- Having any other endpoint it should persist
- Ipfs remote should work as expected
> Migrate ipfs gateway endpoint 

- packages/dappmanager/src/domains.ts
- packages/dappmanager/src/modules/https-portal/index.ts
- packages/dappmanager/src/modules/installer/https.ts
- packages/dappmanager/src/modules/installer/runPackages.ts
Packages which have HTTPS mappings on update inject docker-compose which doesn't necessarily have external network specified
During installation process, DNP_HTTPS is queried whether mapping exists, and if it does it adds external network to the compose. 
- Do HTTPS mapping on a package
- Update that same package
- Check if mapping is broken after update
- Test specially when package === DNP_HTTPS and when it is not
> Check for rest of the packages for HTTPS portal

- packages/dappmanager/src/modules/installer/ensureEth2MigrationRequirements.ts
- packages/dappmanager/src/params.ts
The upcoming core release 0.2.56 will be mandatory for validating in gnosis chain with eth2 multiclient + web3signer.
- Not allowed to installed legacy prsm gnosis (<=0.1.8)
- Not allowed to install web3signer gnosis if legacy prysm installed
- Install a legacy version of prysm gnosis, then install the dappmanager to have this PR code, and finally try to install the web3signer gnosis. It should not be allowed.
- Install the dappmanager to have this PR code, the try to install a legacy version of prysm-gnosis. It should not be allowed.
> Add prysm gnosis to `eth2MigrationRequirements`

- packages/dappmanager/src/calls/packageRemove.ts
- packages/dappmanager/src/modules/https-portal/utils/isRunningHttps.ts
HTTPS portal mappings were not removed when uninstalling a dappnode package. This is an unexpected behavior, that prevented from reinstalling a package with an existing portal mapping.
Remove portal mappings when uninstalling a dappnode package
Install a dappnode package with a portal mapping defined in the manifest. Remove the dappnode package and make sure the portal mapping was removed together with the package. Check the HTTPS volumes or use the HTTPS api to check the portal mappings
> Remove https portal mapping when removing a package

- packages/admin-ui/src/__mock-backend__/data/dnps/bitcoin.ts
- packages/admin-ui/src/pages/packages/components/Info/RemovePackage.tsx
Use of the avaialble manifest warning `onRemove` https://docs.dappnode.io/es/developers/manifest-reference/#onremove
Set the warning on the UI when the user attemps to remove a package by calling the function call `onPackageRemove`
Develop a package with a warnning `onRemove`. Install the package, and make sure the warning appears when trying to remove it
> Add warning onRemove

- packages/admin-ui/server-mock/index.ts
- packages/admin-ui/src/__mock-backend__/notifications.ts
- packages/dappmanager/src/api/routes/index.ts
- packages/dappmanager/src/api/routes/notificationSend.ts
- packages/dappmanager/src/api/startHttpApi.ts
Select a non-available client in the web3signer is allowed, this behavior is hard to restrict due to the client been syncing, the API not available, etc.
Implement a notification API endpoint in the dappmanager to allow packages to send notifications to be rendered in the UI
Install this dappmanager branch, perform a notification post to the dappmanager API (from another docker container) and make sure it is shown in the dappmanager bell on the top right corner
```
curl -X POST "http://my.dappnode/data-send?type=danger&title='web3signer client selected not available'&body='Make sure to select an available client'"
```
The request keys must contains the following:
```
{
type:  "danger" | "warning" | "success" | "info";
title: string; // "Some notification"
body: string; // "Some text about …
```
> New API endpoint to send notifications from packages to the dappmanager to be shown in the UI

- packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
- packages/admin-ui/src/pages/installer/components/Steps/Warnings.tsx
Warnings were not shown on package updates
Show warnings not only `onInstall` but also `onUpdate`
Make sure the warning `onUpdate` is shown in a new package during installation or update
> Show warnings onInstall and onUpdates

- packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
The "update" warnings must only be shown during an update, this means that the package is already installed 
Use of the boolean `isInstalled` to ensure that the update warnings are only shown under such condition
> Only show "update" warnings if the package is already installed 

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/modules/compose/unsafeCompose.ts
Nethermind requires the `ulimits` compose feature to prevent from running out of memory 
Add `ulimits` and its types to `unsafeCompose`
Build and install Nethermind package with the ulimits configured. Make sure that the compose feature persists after installation
> Add compose key ulimits

- packages/dappmanager/src/modules/docker/dockerComposeUp.ts
The function `runPackage` called during the installation of packages runs packages with `docker-compose up` on containers with a previous state different than `stopped`. This is an expected behaviour, however, it is preventing from running the core package if the exit code is 0 OR the status is `created` (`created` status is parsed to `stopped`)
Run `docker-compose up` for packages with all the services running previous to the update AND if it is the core package, no matter its previous state.
With this dappmanager and having already the core container in any of the following status: `stopped` or `created`. Do a core update and make sure that the core package is executed during the update
> `docker-compose up` core package always on `runPackage`

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/modules/compose/unsafeCompose.ts
DAppNode packages should be allowed to define the `deploy` compose service key to define resource restrictions. This would be especially useful to avoid dappnode crashing due to linux OOM killer.
Add these key to the safe compose keys
Using this dappmanager install any package with the resources defined in the compose and make sure that after the installation the compose file have this keys AND that the resource limit was applied to the docker container with `docker stats`
> Add compose `deploy: resources` keys

- packages/dappmanager/src/api/utils.ts
Having multiple dappnode and switching from one to another with the vpn credentials result in an uncaught error in the dappmanager (probably because of a wrong cookie cached on the browser) that makes the container restart
Caught this error and end the session with `req.sesion = null`. This is not the ideal solution and must be researched the concrete error thrown when this cookie is wrong and show a beauty page saying something like "wrong cookie, try refreshing the browser".
This will result into a better user experience and dappmanager container not restarting
Having this dappmanager and more than 1 dappnode configured with VPN credentials, switch from one to another an make sure the dappmanager container does not restart
> Fix cookie error unhandled

- patches/any-observable+0.3.0.patch
Due to the recent use of the `@dappnode/dappnodesdk` as a dependency in the dappmanager (see https://github.com/dappnode/DNP_DAPPMANAGER/pull/1049), the `webpack` build was failing when loading the subdependency: `#@dappnode#admin-ui#@dappnode#dappnodesdk#listr#@samverschueren#stream-to-observable#any-observable"` with the following error
```
Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
at loadImplementation (/usr/src/app/webpack:/node_modules/any-observable/register.js:29:1)
at /usr/src/app/webpack:/node_modules/any-observable/loader.js:30:1
at …
```
> Patch `any-observable` library

- packages/admin-ui/src/pages/packages/components/Info/VolumesList.tsx
Connected with this: https://github.com/dappnode/DAppNode/issues/417
Since showing volume size for bind volumes is not feasible since it has to be calculated, we don't show that. However, total volume size is shown, but counting as 0 volume size of bind mount volumes. This PR removes total volume size in those cases since that is obviously wrong information.
In the volumes section of package check whether:
1) total volume size is shown for packages that don't have bind mounts (custom location for volumes)
2) total volume size is not show for packages that have bind mounts
> Add check for volume sizes

- packages/dappmanager/src/params.ts
The upcoming core release 0.2.56 will be mandatory for validating in mainnet chain with eth2 multiclient + web3signer.
- Not allowed to installed legacy prsm  (<=1.0.24)
- Not allowed to install web3signer if legacy prysm installed
- Install a legacy version of prysm , then install the dappmanager to have this PR code, and finally try to install the web3signer . It should not be allowed.
- Install the dappmanager to have this PR code, the try to install a legacy version of prysm. It should not be allowed.
> Add prysm to `eth2MigrationRequirements`

- packages/admin-ui/package.json
- packages/dappmanager/package.json
- packages/dappmanager/src/modules/compose/editor.ts
- packages/dappmanager/src/modules/release/getRelease.ts
- packages/dappmanager/test/modules/compose/editor/composeAliases.test.ts
- yarn.lock
From https://github.com/dappnode/DAppNodeSDK/pull/266, the `globalEnvs` manifest feature allows defining which global envs add to which service. 
Implement the addition of the global envs to the compose file based on this feature. There can be added two types of global envs:
- **all**: this is the current feature implemented, it injects the `.env` file into the `docker-compose`
- Defining envs and services to set those vars
Install two packages:
1. Package with a manifest defining the `globalEnvs` like:
```
globalEnvs?: {
all?: boolean;
} 
``` 
2. Package with a manifest defining the `globalEnvs` like:
```
globalEnvs?: {
envs: string[];
services: string[];
}[ ]
```
Make sure that in both cases the `docker-compose.yml` of the given package was edited and added the envs (env file for the 1 …
> Set `globalEnvs` (as `string [ ]` and `all: true`) in the `docker-compose.yml`

- packages/dappmanager/src/api/routes/globalEnvs.ts
- packages/dappmanager/src/db/dbFactory.ts
- packages/dappmanager/src/db/dyndns.ts
- packages/dappmanager/src/db/index.ts
- packages/dappmanager/src/db/interceptGlobalEnvOnSet.ts
- packages/dappmanager/src/db/network.ts
- packages/dappmanager/src/db/system.ts
- packages/dappmanager/src/db/upnp.ts
- packages/dappmanager/src/modules/compose/editor.ts
- packages/dappmanager/src/modules/globalEnvs.ts
- packages/dappmanager/src/modules/ipfs/Ipfs.ts
- packages/dappmanager/src/params.ts
- packages/dappmanager/test/modules/compose/editor/composeAliases.test.ts
- packages/dappmanager/test/modules/globalEnvs.test.ts
When a given pkg has in its manifest the `globalEnv` configured, and any of this `globalEnv` changes, the package must update its globalEnv.
- Pkgs with  `globalEnv: { all: true}` uses in the compose `env_file:`
- Pkgs with `globalEnv: [{ services: [ ], envs: [ ] }]` defines the given global env in the compose under `environment` section
- If the option is `globalEnv: { all: true}` then write the new global env file and restart the pkgs that have this option in the manifest
- If the option is `globalEnv: [{ services: ["one", "two"], envs: ["FIRST_ENV", "SECOND_ENV"]}` then update this env in all the 
Install pkgs with `globalEnvs` in the manifest with both options.  Make sure that in both cases the global env is updated in the container
> Update packages global envs

- packages/dappmanager/src/modules/nsupdate/utils.ts
- packages/dappmanager/test/modules/nsupdate/utils.test.ts
Add the dns resolution for multilabel domains with the format `*.ipfs.dappnode.` to the IPFS container IP
See IPFS subdomains https://github.com/ipfs/kubo/blob/master/docs/config.md#gatewaypublicgateways-usesubdomains
Related to https://github.com/dappnode/DNP_IPFS/pull/74
In the `nsUpdate` daemon (triggered in multiple actions by the eventbus), add the mentioned domain resolution rule to the IPFS container 
Make sure the BIND container has implemented the mentioned rule in the to the IPFS container
> Add ipfs multilabel domain `*.ipfs.dappnode.`

- packages/dappmanager/src/modules/nsupdate/utils.ts
Remove the `!isCore` check and execute the `nsUpdate` daemon in all dappnode containers. Core containers are not using static ip anymore
> Execute `nsUpdate` on `isCore` containers also

- packages/dappmanager/src/index.ts
- packages/dappmanager/src/initializeDb.ts
- packages/dappmanager/src/modules/globalEnvs.ts
The function `interceptGlobalEnvsOnSet` is used by `globalEnvs` as a middleware. This function uses IPFS.
The IPFS instance requires some setting from the db to be read before being initialized
In the startup function `initializeDb` read this value and set a default value of `local` if not set
Make sure the ipfsClientTarget value is read and set propertly if required on startup
> read `ipfsClientTarget` on `initializeDb`

- packages/dappmanager/src/db/dyndns.ts
- packages/dappmanager/src/db/network.ts
- packages/dappmanager/src/db/stakerConfig.ts
- packages/dappmanager/src/db/system.ts
- packages/dappmanager/src/db/upnp.ts
Instead of `_DAPPNODE_GLOBAL_consensus-client-prater` use `_DAPPNODE_GLOBAL_CONSENUS_CLIENT_PRATER`
> Set proper `globalEnv` key prefix to `globalEnvs` used iby `interceptGlobalEnvOnSet`

- packages/dappmanager/hostScripts/host_update.sh
Log of host updates do not contain any useful data. /dev/null redirect is removed so logs are more verbose.
> Remove /dev/null redirect in hosts scripts

- packages/dappmanager/src/modules/https-portal/utils/exposeByDefaultHttpsPorts.ts
When installing packages with the `exposable` feature and the `exposeByDefault` not defined, the dappmanager was throwing an error if the HTTPS package was not installed. This is unexpected behavior and there should be only thrown errors when the `exposeByDefault` is set to true and the HTTPS package is not installed
Install a dappnode package with the exposable defined and the `exposaByDefault` not defined or set to false and make sure its get installed.
> Relocate error throwing when `exposeByDefault` HTTPS ports

- packages/dappmanager/src/modules/https-portal/utils/exposeByDefaultHttpsPorts.ts
When installing packages with the `exposable` feature and the `exposeByDefault` not defined, the dappmanager was throwing an error if the HTTPS package was not installed. This is unexpected behavior and there should be only thrown errors when the `exposeByDefault` is set to true and the HTTPS package is not installed
Install a dappnode package with the exposable defined and the `exposaByDefault` not defined or set to false and make sure its get installed.
> Attemp to expose HTTPS ports by default only when are

- packages/dappmanager/src/modules/docker/dockerComposeUp.ts
The container status exited means that the container has received a signal to stop or kill its internal process. Depending on how the docker container handles the signal it will exit with code 0 or != 0. So it cannot be determined if the container was **manually** stopped or not. It would be required that all dappnode packages implementers handles propertly docker signals to stop gracefully shutdowns.
> Consider status exited as stopped always

- packages/dappmanager/src/calls/packageSetEnvironment.ts
- packages/dappmanager/src/modules/globalEnvs.ts
Do not remove orphan containers on `packageSetEnvironment`. This option may break docker functionality while calling `docker-compose up` with the option `force recreate` and `noStart: true`
> Do not remove orphan containers on `packageSetEnvironment`

- packages/admin-ui/src/common/types.ts
- packages/dappmanager/src/daemons/stakerConfig/index.ts
- packages/dappmanager/src/db/stakerConfig.ts
- packages/dappmanager/src/modules/stakerConfig/setDefaultStakerConfig.ts
- packages/dappmanager/src/modules/stakerConfig/utils.ts
The dappmanager db for the stakers UI uses `null` values to express a non-definition value for every value in execution and consensus clients for networks mainnet prater and gnosis. After the first run, these values should have any string value but not `null`. Setting `undefined` results in a default value of `null` which is a false positive of the value not been set.
> Use empty string instead of `undefined` for none option in the stakers UI 

- packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
- packages/admin-ui/src/pages/stakers/components/columns/ExecutionClient.tsx
If no previous consensus client selected and installed, set defaults graffiti and checkpointsync:
- Graffiti: validating_from_DAppNode
- Checkpointsync: dappnode endpoint
> Set defaults graffiti and checkpointsync

- packages/dappmanager/src/index.ts
- packages/dappmanager/src/modules/ethClient/index.ts
- packages/dappmanager/src/modules/ethClient/switchEthClientIfOpenethereumOrGethLight.ts
Deprecate `geth-light` client in favor of "remote"
> Deprecate geth-light client

- packages/admin-ui/src/common/routes.ts
- packages/dappmanager/src/logUserAction.ts
- packages/dappmanager/src/modules/migrations/index.ts
- packages/dappmanager/src/modules/migrations/pruneUserActionLogs.ts
- packages/dappmanager/test/utils/logUserAction.test.ts
- Truncate the file `userActionLogs.json` to 0 if the size is greater than 4MB. Files with size higher are dangerous to parse and may result into unexpected behaviours.
- Do not allow to write new logs to the file if the size of the log exceeds 3KB.
> Prune`userActionLogs`

- packages/dappmanager/src/modules/migrations/pruneUserActionLogs.ts
Fi the path to the file `userActionLogs.json`  to be pruned
> Fix prune of userActionLogs.json file

- packages/admin-ui/src/__mock-backend__/stakerConfig.ts
ENS for the package is different than the metadata file.
Not sure if it matters at all but thought if its one way in the definition of the package it should stay consistent.
> Make ENS/DNP name the same for mainnet besu

- packages/admin-ui/src/common/types.ts
- packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
- packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx
- packages/admin-ui/src/pages/stakers/components/columns/ExecutionClient.tsx
- packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
- packages/admin-ui/src/pages/stakers/components/columns/RemoteSigner.tsx
- packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts
- packages/dappmanager/src/modules/stakerConfig/utils.ts
The JSON schemas generated between front and back throw validation errors when users using staker UI and the field `size` was not provided.
Set the size property as optional to avoid a strict JSON schema validation
Needs more research on why the property size was not there eventually
> Set `StakerItem.data` type as optional

- packages/admin-ui/src/pages/stakers/components/utils.ts
Removed warning shown when both consensus and execution clients are deselected
> Allowed stopping CC and EC from stakers UI

- .gitignore
- Dockerfile.dev
- docker-compose-dev.yml
- docker/start_dev.sh
To improve the developing experience, bind mount the code in a docker volume so getting into the dev container is no longer needed.
> Bind mount code in a docker volume

- packages/dappmanager/webpack.config.js
fix 
```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/x.y.z)
```
> fix ethers error on production

- packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts
Only set staker global envs if necessary. This would prevent from unnecesary triggers of `interceptGlobalenvOnSet` and its corresponding behaviour
> Only set staker global envs if necessary

- packages/admin-ui/src/common/routes.ts
- packages/admin-ui/src/pages/system/actions.ts
- packages/dappmanager/src/calls/ethClientTargetSet.ts
- packages/dappmanager/src/modules/ethClient/ethereumClient.ts
When switching client through **system > repository > ethereum**, make sure the new client target is running
> When switch to a new client make sure its running

- packages/dappmanager/src/calls/systemInfoGet.ts
Deprecate `ethClientTarget` in new features to be shown on startup. From now on it will depend on execution and consensus client values to be not `null`
> Deprecate `ethClientTarget` in new features to be shown on startup

- packages/admin-ui/src/pages/system/components/Repository/Eth.tsx
When switching repository to a new full node, make sure to use the checkpointSync arg
> Switch Ethereum repository with `useCheckpointSync`

- packages/dappmanager/src/calls/packageSetEnvironment.ts
- packages/dappmanager/src/modules/docker/dockerComposeUp.ts
Catch error when renaming a container with the same name. If that happens then:
1. Try recreating the containers
2. Try `compose down` and `compose up`
> Catch error renaming container with the same name

- packages/dappmanager/src/daemons/ethMultiClient/index.ts
When switching full node to an installed client, ensure its running
> When switchin full node, start client if not running

- packages/dappmanager/src/modules/ethClient/apiUrl.ts
The Nimbus package is a monoservice and is using the following ports:
- 3500: validator API
- 4500: beacon APi
See [ref](https://github.com/dappnode/DAppNodePackage-nimbus)
Todo: find a better way to get dynamically the beacon API
> Use port 4500 for nimbus

- packages/dappmanager/src/modules/ethClient/clientStatus.ts
- packages/dappmanager/src/modules/ethClient/ethersProvider.ts
- packages/dappmanager/src/utils/ethers.ts
In Ethereum repository, when using full node and fallback is activated, compare the latest block of dappnode remote node and local full node to determine if it is synced or not
> Ensure is synced with remote execution

- packages/admin-ui/src/components/navbar/dropdownMenus/BaseDropdown.tsx
- packages/admin-ui/src/pages/dashboard/components/ChainCard.tsx
Currently chain synchronization progress is shown floored to the closest integer, as such during a refresh UI may jump from 99% to 100%. This is fine in cases where the time it takes to make 1% progress is linear. Though in reality chain synchronization progress may seriously slow down in the last few percent, as such the experience is often to see the UI stuck at 99% for a very long time.
The purpose of this PR is to allow showing 2 fractional digits on the progress bar as to provide more granular progress in order to provide more accurate feedback in the last few percent of chain synchronization.
Use the `toFixed(2)` JavaScript number method to remove other fractional digits.
Chain synchronization progress in both the chain card in the main dashboard and in the chain dropdown should …
> Display progress percent with 2 fraction digits

- packages/dappmanager/src/modules/stakerConfig/getStakerConfig.ts
- packages/dappmanager/src/modules/stakerConfig/utils.ts
Tracked in https://github.com/dappnode/DAppNodePackage-teku/issues/34 4 other related PRs are tracked there for each implementation of Teku
fixed handling of fee recipient address ENV variable for Teku, the flag enabling it must be used in both the beacon-chain and validator service.
Fixes #1258 
Add functionality in the dappmanager's stakersUI to set the Fee recipient address properly in Teku's beacon-chain service to avoid warnings about certain rare/edge case failures surrounding the fee recipient address the `--validators-proposer-default-fee-recipient-address=<ADDRESS>` flag to both services of Teku, not just the validator service, but also the beacon chain.  
1. Install core v0.2.61 (or later if Gnosis chain) with this PRs changes.
2. install and sync Teku checked out from the …
> fix fee recipient for teku

- packages/dappmanager/src/eventBus.ts
Fix TypeError when using checkpointsync in the `ethClientInstaller`
> Fix TypeError

- packages/admin-ui/src/pages/stakers/components/utils.ts
Documentation for Monet and Gnosis relays added to MEV Boost in stakers UI
> Added doc URL for MEV Boost relays

- packages/dappmanager/src/modules/migrations/index.ts
Disallow the `setDefaultStakerConfig` migration. This uses `packageSetEnvironment` to update the staker config envs var which in the ends rewrites compose files and restart containers.
> Disallow setStakerConfig migration

- Dockerfile
- Dockerfile.dev
Upgrade node to 19.2.0 so the crypto module does not miss a strong random source.  18 is not working.
This is critical for creating from scratch the dynds identity
> Upgrade node to 19.2.0

- packages/dappmanager/src/db/stakerConfig.ts
- packages/dappmanager/src/modules/globalEnvs.ts
- packages/dappmanager/src/modules/migrations/index.ts
- packages/dappmanager/src/modules/migrations/setDefaultFeeRecipient.ts
Set `FEE_RECIPIENT_<NETWORK>` global env var. The compose env `FEE_RECIPIENT_ADDRESS` value will be retrieved from the Consensus Client selected, if not possible to retrieve the value the global env `FEE_RECIPIENT_<NETWORK>` will be set to an empty string, in order to avoid triggering the migration again.
> Implement default fee recipient

- packages/admin-ui/src/__mock-backend__/stakerConfig.ts
- packages/admin-ui/src/pages/stakers/components/AdvanceView.tsx
- packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
- packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx
- packages/admin-ui/src/pages/stakers/components/launchpad/LaunchpadSteps.tsx
- packages/admin-ui/src/pages/stakers/components/launchpad/LaunchpadValidators.tsx
- packages/admin-ui/src/pages/stakers/components/launchpad/launchpad-validators.scss
- packages/admin-ui/src/pages/stakers/components/utils.ts
- packages/common/src/types.ts
- packages/dappmanager/src/modules/stakerConfig/getStakerConfig.ts
- packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts
- packages/dappmanager/src/modules/stakerConfig/stakerParamsByNetwork.ts
- packages/dappmanager/src/modules/stakerConfig/utils.ts
Set the fee recipient as a new global env instead of been as a env from each consensus client pkg
**TODO** set in every consensus client:
- min dappnode version
- remove fee recipient as env in the compose and set it as new global env in the manifest
> Set fee recipient as global env

- packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
- packages/admin-ui/src/pages/stakers/components/launchpad/LaunchpadSteps.tsx
- packages/admin-ui/src/pages/stakers/components/launchpad/LaunchpadValidators.tsx
- packages/common/src/types.ts
- packages/dappmanager/src/daemons/ethMultiClient/index.ts
- packages/dappmanager/src/modules/ethClient/ethereumClient.ts
- packages/dappmanager/src/modules/stakerConfig/setStakerConfig.ts
- packages/dappmanager/src/modules/stakerConfig/utils.ts
Use fee recipient as a mandatory value in the backend. 
Only allow to apply staker changes if fee recipient is valid
> Use fee recipient as mandatory

- packages/dappmanager/src/modules/stakerConfig/params.ts
All clients and signers are now compatible with Lodestar, so the versions can be set up definitely now
> Definitive lodestar compatible versions

- packages/admin-ui/src/App.tsx
- packages/admin-ui/src/components/topbar/TopBar.tsx
- packages/admin-ui/src/types.ts
Beta tag will only be shown while the user is in light mode
> Hide beta tag for light mode

- .eslintrc.cjs
- package.json
- packages/admin-ui/.eslintrc.cjs
- packages/admin-ui/.eslintrc.json
- packages/common/.eslintrc.cjs
- packages/common/package.json
- packages/dappmanager/.eslintrc.cjs
- packages/dappmanager/package.json
1. Linter was not being used in `common`
2. Linter was not taking advantage of inheritance
3. Linter files were not consistent with format (`.json` and `.cjs`)
> Fix Linter

- packages/admin-ui/src/pages/stakers/components/utils.ts
Removes the Anomymous relay (relayooor.wtf) from the list of available relays as it's been discontinued and now returns HTTP 502 errors.
See: https://twitter.com/builder0x69/status/1639029339743297537
> fix(relay): removed Anomynous relay

- packages/dappmanager/src/modules/chains/drivers/monero.ts
Monero chain card was showing `Daemon is not a constructor`. This issue is fixed by updating the import of `monero-rpc` library.
> Fix import for monero

- packages/admin-ui/src/__mock-backend__/stakerConfig.ts
- packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx
PR related to issue #1427. Some concensus clients had **_useCheckpointSync_** defined to false by default. Others didn't have it defined (when **_useCheckpointSync_** its not defined properly in each concensus client, its value is set to false, this does not change in this PR) https://github.com/dappnode/DNP_DAPPMANAGER/blob/f3f654426ba28e2b770236fcae3a25e52b522339/packages/admin-ui/src/pages/stakers/components/columns/ConsensusClient.tsx#L27
Each concensus clients now has its **_useCheckpointSync_** variable to "true" by default. 
Check that sync is set to true in "Stakers" frontend by default
> Set `useCheckpointSync` to true for all concensus clients

- packages/admin-ui/src/components/sidebar/navbarItems.ts
Changing the 3rd icon's link to https://giveth.io/project/dappnode
> Adding link to Giveth

- packages/admin-ui/nodemon.json
- packages/dappmanager/package.json
- packages/dappmanager/src/calls/packageRestartVolumes.ts
Stop container before remove on `packageRestartVolumes` allowing the container to perform any needed task before closing
> Stop container before remove on `packageRestartVolumes`

- packages/dappmanager/src/calls/packageRestartVolumes.ts
Only stop containers running in `packageRestartVolumes`
> Only stop containers running

- packages/dappmanager/src/api/routes/metrics.ts
one liner to set prometheus metric `dappmanager_staker_config` to 5 if lodestar is set.
> add lodestar metric

- packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
Ultrasound relay was removed in https://github.com/dappnode/DNP_DAPPMANAGER/pull/1508 , but it is right. Only relayor.wtf should be removed (which already was)
> Revert ultrasound relay removed

- packages/admin-ui/src/pages/installer/components/dappnodeDappstore/InstallerDnp.tsx
In stakers mainnet and gnosis fake cards, use absolute paths for redirection
> Use absolute paths to redirect to stakers

- packages/dappmanager/src/calls/packageRestartVolumes.ts
Use container core prefix for core containers on `packageRestartVolumes`. This would fix the issue of removing volumes from core containers
> Use container core prefix for core containers on `packageRestartVolumes`

- packages/dappmanager/src/modules/stakerConfig/utils.ts
LUKSO checkpoint is not supported by Dappnode, it is supported by the LUKSO team
> Fix LUKSO checkpoint

- packages/dappmanager/src/calls/packageRemove.ts
- packages/dappmanager/src/calls/packageRestartVolumes.ts
- packages/dappmanager/src/modules/ethicalMetrics/params.ts
Ethical Metrics instance should be unregistered before removing the package volumes
> Unregister EM before removal

- packages/admin-ui/src/pages/system/components/Notifications/EthicalMetrics.tsx
If email has not changed, user should not be able to submit the email change to the ethical metrics server
> Disable submit if email has not changed

- packages/admin-ui/src/pages/system/components/Notifications/EthicalMetrics.tsx
Regenerating version `v0.2.73` of the dappmanager to include this feature:
New email submit should only be allowed if it is different to the registered one
> Disable submit on email not change (EM) for `v0.2.73`

- packages/admin-ui/src/dappnode_colors.scss
- packages/admin-ui/src/light_dark.scss
Danger alerts and error messages have been defined in `light_dark.scss` to be readable in dark mode
**Before:**
**After:**
> Improve dark theme danger alerts & errors

- packages/dappmanager/src/modules/migrations/setDefaultEthicalMetricsEmail.ts
Update container name to tor-hidden-service to retrieve default ethical metrics email used in the migration
> Update container name to tor-hidden-service

- packages/dappmanager/src/modules/optimism/getOptimismConfig.ts
- packages/dappmanager/src/modules/optimism/getOptimismNodeRpcUrlIfExists.ts
Use static method `getUserSettingIfEsists` to get the optimism rpc URL and avoid having an unhandled error
> Use static method to get op node rpc url

- packages/dappmanager/src/modules/chains/drivers/ethereum.ts
OP Erigon and OP geth include the flag `--nodiscover` so in the case of OP Erigon this is probably the cause that `net_peerCount` returns an error. This error should not prevent the user from seeing whether the client is synced or not
> Fix OP Erigon not showing peers

- packages/admin-ui/src/pages/rollups/components/Optimism.tsx
Update copy in Rollups>Optimism
Replaced "Legacy Geth" by "Optional Modules"
> Optional modules

- packages/dappmanager/src/modules/migrations/addAliasToRunningContainers.ts
We didnt check for existing aliases when adding new aliases so aliases duplicated were added:
``` 
"Aliases": [
"DAppNodePackage-geth.dnp.dappnode.eth",
"geth.dnp.dappnode.eth",
"geth.dappnode",
"4104c791f928",
"geth.dnp.dappnode.eth.geth.dappnode",
"geth.dappnode"
],```
> Ensure aliases uniqueness

- Dockerfile
DB module was not added to `Dockerfile`, so the dappmanager did not start
> Fix db module not found

- packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
Removed 2 relays as they have been discontinued:
- **Blocknative:** https://docs.blocknative.com/blocknative-relay/mev-relay-instructions-for-ethereum-validators
- **Bloxroute Ethical:** https://twitter.com/bloXrouteLabs/status/1690065892778926080
> Removed the relays from the MevBoost.tsx file.
Test via UI, as well as make sure it correctly updates the current config of MEV Boost.
> fix(relay): removed BloxrouteEthical & Bocknative

- packages/dappmanager/src/daemons/ethMultiClient/index.ts
- packages/dappmanager/src/modules/ethClient/ethereumClient.ts
- packages/dappmanager/src/modules/ethClient/index.ts
- packages/dappmanager/src/modules/migrations/addAliasToRunningContainers.ts
- packages/dappmanager/src/modules/stakerConfig/set/setStakerConfig.ts
- packages/dappmanager/test/unit/modules/ethClient/fullNodeEdit.test.ts
- packages/dockerApi/src/api/network.ts
- packages/eventBus/src/eventBus.ts
`fullnode.dappnode` domain should point to the mainnet execution selected by the user, if any
Also, each network (prater, gnosis and lukso) has its own fullnode domain, following this pattern: `<network>.fullnode.dappnode`
> Fix `fullnode.dappnode` alias

- package.json
Add engines to `package.json` so the engine compatible is shown when compiling
> Add engines to package json

- Dockerfile.dev
Installer module was not included in the `Dockerfile.dev`
> Add installer module to dev Dockerfile

- packages/hostScriptsServices/src/hostScripts/scripts/rebootRequired.ts
Add max age to reboot required to reboot script, otherwise the script is executed only once at startup and will not show the reboot required until dappmanager container restarts
> Add max age to reboot required to reboot script

- packages/params/src/params.ts
Overrides https://github.com/dappnode/DNP_DAPPMANAGER/pull/1714 to use the env key for allowing Ethereum mainnet node requests
> Add Besu key

- packages/dappmanager/src/calls/getHostUptime.ts
Fix hostuptime memo by exporting the function instead of the var
> Fix hostuptime memo

- packages/dappmanager/src/api/routes/dataSend.ts
Increase the length of the data sent via an HTTP param to the `data-send` endpoint.
This is needed for SSV package, which creates public keys of `612` characters that need to be shown in the package info
> Increase data send arg length to 700

- packages/migrations/src/ensureDockerNetworkConfig/connectContainersToNetworkWithPrio.ts
The function `getDappmanagerAndBindContainerNames` is not necessary as we already have the container names defined as `params`. Also, in the case the params were not well-defined, this function would not help either
> Remove unnecessary function

- packages/dockerApi/package.json
- packages/dockerApi/src/api/network.ts
- packages/dockerApi/test/int/getNetworkAliasesMap.int.test.ts
- packages/installer/src/ethClient/ethereumClient.ts
- packages/migrations/src/addAliasToRunningContainers.ts
- packages/migrations/src/ensureDockerNetworkConfig/connectContainerRetryOnIpUsed.ts
- packages/migrations/src/ensureDockerNetworkConfig/connectContainersToNetworkWithPrio.ts
- packages/migrations/src/ensureDockerNetworkConfig/ensureDockerNetworkConfig.ts
- packages/params/src/params.ts
In order to keep the aliases that each container has inside the `dncore_network`, we need to retrieve them before disconnecting the containers from the network
> Handle container aliases for IP range migration

- packages/migrations/src/migrateDockerNetworkIpRange/connectContainerWithIp.ts
Renamed util function `sanitizeIpFromNetworkInspectContainers` to `removeCidrSuffix` as it is more accurate to what it is actually doing
> Rename "sanitize IP" to "remove CIDR suffix"

- packages/dockerCompose/src/setDappnodeComposeDefaults.ts
- packages/migrations/src/addAliasToRunningContainers.ts
Add `getIsMonoService` checker to adding aliases to docker containers
> Add `getIsMonoService` checker to adding aliases to docker containers

- packages/dockerCompose/src/setDappnodeComposeDefaults.ts
- packages/migrations/src/ensureCoreComposesHardcodedIpsRange.ts
Delete every hardcoded IP in installer.
Consider in the future allowing only bind to have a hardcoded IP
> Delete hardcoded IP in installer

- packages/stakers/src/set/getStakerCompatibleVersionsByNetwork.ts
Fixes Holesky StakersUI, currently it does not allow selecting Holesky Nethermind or Holesky Besu, throwing this error
```
error2Call to stakerConfigSet
Today, 25 min ago
Reply: Invalid execution client [object Object] for network holesky
Error: Invalid execution client [object Object] for network holesky
at ensureSetRequirements (file:///usr/src/app/packages/dappmanager/src/modules/stakerConfig/set/ensureSetRequirements.ts:48:11)
at setStakerConfig (file:///usr/src/app/packages/dappmanager/src/modules/stakerConfig/set/setStakerConfig.ts:75:3)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at stakerConfigSet …
```
> Fix Holesky Nethermind and Holesky Besu in Holesky StakersUI

- packages/chains/src/drivers/ethereum.ts
- packages/dappmanager/src/api/middlewares/ethForward/resolveDomain.ts
- packages/installer/src/ethClient/clientStatus.ts
This PR aims to avoid the errors:
```
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not …
```
> Set static network for all JSON RPC providers

- packages/dappmanager/src/calls/chainDataGet.ts
Remove `memoizee` from `chainDataGet` which was causing cache issues in the dashboard chain cards
> Remove `memoizee` from `chainDataGet`

- packages/daemons/src/bind/ensureBindContainerIpAndRunning.ts
- packages/migrations/src/migrateDockerNetworkIpRange/connectContainersToNetworkWithPrio/connectContainerWithIp.ts
- packages/migrations/src/migrateDockerNetworkIpRange/connectContainersToNetworkWithPrio/connectContainersToNetworkWithPrio.ts
Remove intermedium container if any. There has been detected issues when updating other core packages that has an intermedium container with a name prefixed with the container ID that conflicts with the existing container
> Remove intermedium container if any

- packages/daemons/src/bind/index.ts
Catch error on bind daemon, so the main app does not crash
Todo: force somehow all daemons to have error catched, or catch it on the main app
> Catch error on bind daemon

- packages/common/src/types/calls.ts
- packages/dappmanager/src/initializeDb.ts
- packages/db/src/ethClient.ts
Deprecate ethereum client target. It was subsituted in dappmanager 0.2.54 by splitted execution and consensus clients targets
> Deprecate ethereum client target

- packages/dappmanager/src/calls/fetchDnpRequest.ts
Fix setupwizard appearence.
Since toolkit integration the dappnode installer returns the setupwizard as a separated file instead as a field in the manifest
> Fix setupwizard appearence

- packages/admin-ui/package.json
- packages/chains/package.json
- packages/common/package.json
- packages/daemons/package.json
- packages/dappmanager/package.json
- packages/db/package.json
- packages/dockerCompose/package.json
- packages/eventBus/package.json
- packages/hostScriptsServices/package.json
- packages/httpsPortal/package.json
- packages/installer/package.json
- packages/logger/package.json
- packages/migrations/package.json
- packages/optimism/package.json
- packages/schemas/package.json
- packages/stakers/package.json
- packages/toolkit/package.json
- packages/types/package.json
- packages/upnpc/package.json
- packages/utils/package.json
bump dappnode deps internally:
- schemas: 0.1.11
- types: 0.1.34
Since these packages are also npm modules it is required for them to have the proper version in the package.json for those npm modules that has as dependency another npm module
> bump dappnode deps internally: types and schemas

- packages/dappmanager/src/api/routes/packageManifest.ts
Return after send 404 in packageManifest http API
> Return after send 404 in packageManifest

- packages/params/src/params.ts
Decrease bind daemon intervale for resilience. Consider putting a higher value after the ip range migration
> Decrease bind daemon intervale for resilience

- packages/installer/src/dappGet/fetch/DappGetFetcher.ts
Fix injecting opt dependencies when dependencies does not exist. This issue happened when installing package without dependencies and with optional dependencies
> Fix injecting opt dependencies when dependencies does not exist

- packages/admin-ui/src/pages/dashboard/components/HostStats.tsx
Temperature is `null` in cloud dappnodes since there are no data, dont show those cards in such cases
> Only show temp card if data exists

- packages/admin-ui/src/components/NotificationsMain.tsx
While waiting for the api response and dispatching the new state, the property active was "!null", displaying that way the alert.
> Disconnected host alert while loading fixed

- packages/admin-ui/src/pages/rollups/components/RollupsRoot.tsx
Temporarily disabled the 'zkevm' tab pending the mainnet launch for this feature
> removed zkevm tab in rollups

- packages/admin-ui/src/__mock-backend__/data/dnpRequest.ts
- packages/admin-ui/src/__mock-backend__/data/sample.ts
- packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
- packages/dappmanager/src/calls/fetchDnpRequest.ts
- packages/dappmanager/src/calls/getIsConnectedToInternet.ts
- packages/dockerApi/src/api/getDockerVersion.ts
- packages/dockerApi/src/api/index.ts
- packages/schemas/src/schemas/manifest.schema.json
- packages/types/src/calls.ts
- packages/types/src/manifest.ts
When trying to install a package whose ```minimumDockerVersion``` in manifest is higher than the current docker version, the installation will be blocked and an alert with a btn will redirect to "Docker update" in "System / advanced"
> Add minimumDockerVersion as optional requirement in manifest

- packages/admin-ui/src/pages/packages/components/Info/VolumesList.tsx
This pull request addresses a bug related to volume size calculation in packages and introduces an enhancement for better code clarity.
**Changes include:**
- Fixed volume size calculation logic to handle null or undefined values, ensuring accurate aggregation across packages.
- Removed redundant checks for undefined volume sizes, streamlining rendering and enhancing code clarity.
These changes aim to improve the reliability and maintainability of volume size calculations within the application.
> Bug Fix and Enhancement: Volume Size Calculation

- packages/admin-ui/src/components/EthMultiClient.tsx
- packages/admin-ui/src/pages/packages/components/Info/VolumesList.tsx
- packages/admin-ui/src/pages/repository/components/Eth.tsx
This pull request addresses the issue of persisting the previous Ethereum repository configuration when switching to a remote connection in the EthMultiClients component.
**Changes include:**
- Added logic to ensure that the previous Ethereum repository configuration is preserved when switching to a remote connection.
- Utilized Redux useSelector hook to access the current Ethereum repository target.
- Improved the code structure for better readability and maintainability.
These changes aim to enhance the user experience by maintaining consistency in Ethereum repository configurations when transitioning between local and remote connections.
> Eth repository config persistence during remote switch in EthMultiClients component

- packages/admin-ui/src/__mock-backend__/index.ts
- packages/admin-ui/src/components/welcome/features/EnableEthicalMetrics.tsx
- packages/admin-ui/src/pages/system/components/Notifications/EthicalMetrics.tsx
- packages/daemons/src/ethicalMetrics/checkEthicalMetricsStatus.ts
- packages/dappmanager/src/calls/ethicalMetrics.ts
- packages/db/src/ethicalMetrics.ts
- packages/ethicalMetrics/src/register.ts
- packages/migrations/src/changeEthicalMetricsDbFormat.ts
- packages/migrations/src/index.ts
- packages/types/src/calls.ts
- packages/types/src/routes.ts
Implement telegram channel id in the backend:
- Change the ethical metrics settings in the database
- Add migration to database
- Change type
- Add implementation of tgChannelId in ethical metrics register
> Ethical metrics - add telegram implementation into backend

- packages/admin-ui/src/components/SwitchBig.tsx
- packages/admin-ui/src/components/sidebar/sidebar.scss
- packages/admin-ui/src/pages/system/components/Notifications/EthicalMetrics.tsx
- packages/admin-ui/src/pages/system/components/Notifications/ethicalMetrics.scss
- packages/daemons/src/ethicalMetrics/checkEthicalMetricsStatus.ts
- packages/dappmanager/src/calls/ethicalMetrics.ts
- packages/dappmanager/src/initializeDb.ts
- packages/db/src/ethicalMetrics.ts
- packages/migrations/src/changeEthicalMetricsDbFormat.ts
- Db key `notifications` instead of `ethical-metrics`
- onboarding ethical metrics modal retriggered 
System / Notifications
- Same switch as used in onboarding modal
- UI data removed when disabling ethical metrics
- Disabling switch when ANY regex validation fails
- Layout changed
- Message displayed when Switch is off to guide the user
- Confirmation popUp when disabling ethical metrics
- Notifications copy updated
> Ethical metrics changes

- packages/admin-ui/src/components/welcome/features/EnableEthicalMetrics.tsx
- packages/admin-ui/src/components/welcome/features/enableEthicalMetrics.scss
- Add a short copy about what the user is about to download and redirect them to the docs
- Disable update button after user clicked on update by fetching content again. Use `await ethicalMetricsConfig.revalidate()`
- Ensured that the update button remains disabled if no changes are made or if validation errors occur
- Added a delay to clear the success message after enabling ethical metrics
- Refactored button disable conditions for clarity and readability
> Ethical metrics enhancement modal

- packages/admin-ui/src/pages/stakers/components/StakersRoot.tsx
This pull request addresses urgent issues by removing the "Goerli" tab from the Stakers UI. Recent problems with checkpoint syncs have rendered Goerli functionality unreliable, necessitating its immediate removal to maintain a stable user experience. This action aims to mitigate potential disruptions and ensure continued functionality for users accessing the Stakers UI.
> Remove goerli from stakers 

- packages/admin-ui/src/components/welcome/features/EnableEthicalMetrics.tsx
- packages/admin-ui/src/pages/system/components/Notifications/EthicalMetrics.tsx
Consolidated email and Telegram channel ID validations into a single useEffect hook for improved code organization and readability. Additionally, enhanced the regex pattern to allow for groups in the Telegram channel ID format, providing added flexibility and versatility.
Telegram IDs can be in the format `'-1001234567890'` or `'-1001761649725_393'`
> Updated telegram id regex to allow for groups ids

- packages/params/src/params.ts
Add gnosis team key to show Gnosis Erigon as a trusted package
> Add gnosis team key

- packages/admin-ui/src/components/welcome/features/EnableEthicalMetrics.tsx
- packages/admin-ui/src/pages/system/components/Notifications/EthicalMetrics.tsx
Enabling changes of the switch that allows to turn `ON/OFF` ethical metrics when:
- Ethical metrics is loading, no matter if it's turning `ON` or `OFF`
- Enabling the switch when ethical metrics is `ON` and want to turn it `OFF`, and both fields (telegramChannelID and mail) are empty
> Disabling Ethical Metrics Switch cases when loading and empty fields when ON

- packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
- packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
- packages/db/src/globalEnvs.ts
- packages/db/src/stakerConfig.ts
- packages/installer/src/calls/packageRemove.ts
- packages/stakers/src/get/getStakerDnpNamesByNetwork.ts
- packages/stakers/src/set/getStakerCompatibleVersionsByNetwork.ts
- packages/stakers/src/set/setMevBoost.ts
- packages/stakers/src/set/setStakerConfig.ts
- packages/stakers/src/utils.ts
- packages/types/src/stakers.ts
Please see issue #1865
This pull request adds support for the Holesky testnet to MEV-Boost, including integration of working relays for Flashbots, Aestus, and Ultrasound networks. Additionally, it ensures a consistent user experience across different networks, mirroring the UX of MEV-Boost on other platforms. With Prater nearing deprecation and its relays no longer maintained, this update is crucial for seamless transition and continued functionality.
> Add MEV-Boost package to Stakers Holesky

- packages/dockerApi/src/api/copyFileTo.ts
Before copying files to a docker container using `docker cp` the container needs to be running. This causes trouble in packages like Obol, where some services are stopped by default
> Start container before docker cp

- packages/schemas/src/schemas/manifest.schema.json
Upstream software was not completely defined in the manifest schema. This way we can handle several upstream repos for a single package (this feature was already implemented in the SDK).
However, this is just a temporary fix until this issue is completed: https://github.com/dappnode/DAppNodeSDK/issues/408
> Add upstream definition in manifest schema

- packages/admin-ui/src/pages/packages/components/Info/PackageSentData.tsx
For packages like Obol we need several values sent to the dappmanager and the ideal situation involves having them sorted alphanumerically. This is the objective of the present PR.
Before:
After:
> Order data sent in pkg info

- packages/daemons/src/autoUpdates/formatNotificationBody.ts
- packages/schemas/src/schemas/manifest.schema.json
- packages/schemas/test/unit/validateSchema.test.ts
- packages/types/src/calls.ts
- packages/types/src/manifest.ts
Improve upstream repo schema to support the old way of handling upstream repos together with the newly defined in https://github.com/dappnode/DAppNodeSDK/issues/408
There are 3 possible cases:
1. No upstream settings defined
2. Upstream settings defined in the old way (upstreamRepo, upstreamArg and upstreamVersion fields)
3. Upstream settings defined in the new way (upstream object, with the fields repo, version and arg inside it)
It is not possible to define both at the same time
> Improve upstream repo schema

- packages/schemas/src/schemas/manifest.schema.json
- packages/schemas/test/unit/validateSchema.test.ts
- packages/types/src/manifest.ts
After researching, I have not found any package that defines multiple upstream repos like an array of string, so we have decided that the only way of having multiple upstream projects will be using the new format defined in https://github.com/dappnode/DAppNodeSDK/issues/408#issuecomment-2063702185
> Only support 1 upstream repo with separate fields

- packages/migrations/src/pruneUserActionLogs.ts
skip prunning if file user action log does not exist
> skip prunning if file does not exist

- packages/types/src/manifest.ts
Added `UpstreamItem` type to `types` package. It will be used in SDK for the bump upstream action
> Add UpstreamItem type

- packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
Added titan and bloxroute holesky relays. With these 2 additions, we support all 5 relays recognized by holesky.beaconcha.in: https://holesky.beaconcha.in/relays
mevboost logs:
```
time="2024-05-13T10:13:51.15Z" level=info msg="relay #1: https://0x821f2a65afb70e7f2e820a925a9b4c80a159620582c1766b1b09729fec178b11ea22abb3a51f07b288be815a1a2ff516@bloxroute.holesky.blxrbdn.com" version=v1.7.1
time="2024-05-13T10:13:51.15Z" level=info msg="relay #2: https://0xaa58208899c6105603b74396734a6263cc7d947f444f396a90f7b7d3e65d102aec7e5e5291b27e08d02c50a050825c2f@holesky.titanrelay.xyz" version=v1.7.1
time="2024-05-13T10:13:51.15Z" level=info msg="relay #3: https://0xab78bf8c781c58078c3beb5710c57940874dd96aef2835e7742c866b4c7c0406754376c2c8285a36c630346aa5c5f833@holesky.aestus.live" version=v1.7.1 …
```
> Add titan and bloxroute holesky relays

- packages/admin-ui/src/dappnode_styles.scss
- packages/admin-ui/src/pages/packages/components/Info/PackageSentData.tsx
Displaying a "Copied" tooltip when clicking the copy button from inputs in `packages/my/package-name/info`
> "Copied tooltip" in `packages/info`

- packages/admin-ui/src/pages/packages/pages/ById.tsx
Preventing the package tab routes from auto-reloading after cursor being focused in another window. 
Passing the `react.render` as a `JSX element`, was creating a new instance of the element on each render, triggering unnecessary re-renders.
> Prevent packages routes from auto-rendering

- packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
- Adding manifold and aestus relays, as these are the last 2 relays whitelisted by lido not implemented already in dappnode's stakers UI. Both are NOT OFAC compliant relays. Specified here: https://github.com/eth-educators/ethstaker-guides/blob/main/MEV-relay-list.md
- Changed bloxroute (max-profit) to be OFAC compliant, as it is since Dec 2023: https://x.com/bloXrouteLabs/status/1736819783520092357
To see lido whitelisted relays, query `get_relays` method of https://etherscan.io/address/0xf95f069f9ad107938f6ba802a3da87892298610e#readContract
> Add manifold and aestus mainnet relays 

- packages/admin-ui/src/pages/packages/components/Network/HttpsMappings.tsx
- packages/admin-ui/src/pages/packages/components/Network/https-mapping.scss
- packages/httpsPortal/src/apiClient.ts
- packages/httpsPortal/src/httpsPortal.ts
- packages/types/src/calls.ts
Implement auth for https in backend:
- Allows to add optional query argument to add mapping API call **auth**
- The auth comes as a string in format `${username}:{SSHA}${combined}`
- No password stored in dappmanager side
> Implement auth for https in backend

- packages/dappmanager/src/calls/sshManager.ts
SSH status fetch is failing in modern Ubuntu distributions as `sshd` is not found anymore as a service. It is `ssh` instead. There needs to be some more testing but in my research it seems to be quite backwards compatible.
> Get status of ssh instead of sshd

- packages/params/src/params.ts
Updated Nethermind address, following the new authorized address provided by the Nethermind team. Previous address is not authorised anymore
> Update Nethermind address

- packages/toolkit/src/repository/repository.ts
closes https://github.com/dappnode/DAppNodePackage-DMS/issues/47 as part of the project https://github.com/orgs/dappnode/projects/72/views/1
**getPkgAsset()** now takes into account the "multiple" field of `fileConfig` parameter. If `multiple == true` and at least one file (here defined as IpfsEntry) passes the given name regex for the `fileConfig`,  **getPkgAsset()** will return `<T>` as a **json array**, instead of a **json object**.
For example, [dappnode exporter package](https://github.com/dappnode/DAppNodePackage-exporter) has two files that end with `grafana-dashboard.json`. When the IPFS content of the package is downloaded, dappmanager will now notice that both files must be appended as an array, since we permit multiple `grafana-dashboard.json` to exist in a dnp, and both files …
> Fix `getPkgAsset` to return an array if multiple elements exist

- packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
- packages/admin-ui/src/pages/stakers/components/useStakerConfig.ts
- packages/types/src/stakers.ts
Use mev boost as optional in stakers frontend due to the possibility of not available in networks: Lukso and Gnosis chain
> Use mev boost as optional in stakers frontend

- packages/dockerCompose/src/userSettings.ts
- packages/stakers/src/consensus.ts
- packages/stakers/src/execution.ts
- packages/stakers/src/mevBoost.ts
- packages/stakers/src/signer.ts
- packages/stakers/src/stakerComponent.ts
Merge consensus aliases:
- Existing aliases set by the installer
- New alises set by the stakers network for engine coms
> Merge consensus aliases

- packages/admin-ui/src/pages/support/components/activity.scss
Removing some unused styles that were causing a warning when building with vite
> Vite build warning fix

- packages/toolkit/test/directory/directory.test.ts
- packages/toolkit/test/registry/registry.test.ts
- packages/toolkit/test/repository/repository.test.ts
Fix int tests from toolkit to use new ethers
> Fix int tests toolkit

- packages/admin-ui/src/pages/installer/components/InstallDnpContainer.tsx
- packages/admin-ui/src/pages/installer/components/InstallerRoot.tsx
- packages/admin-ui/src/pages/installer/components/dappnodeDappstore/InstallerDnp.tsx
This fixes a bug introduced in https://github.com/dappnode/DNP_DAPPMANAGER/pull/2013
Version of a package is now defined as a query param (`?version=x.x.x`) instead of a path (`/x.x.x/`) so that each of the steps of the installation, like the setup wizard or the disclaimer are properly rendered in the browser
Version to install is now defined like:
> Define pkg version as query param instead of path

- packages/params/src/params.ts
Add LUKSO team key
This key will be authorized to publish the following packages:
`lukso-geth.dnp.dappnode.eth`
`prysm-lukso.dnp.dappnode.eth`
`teku-lukso.dnp.dappnode.eth`
> Add LUKSO team key

- packages/stakers/src/stakerComponent.ts
set compose up flag `forceRecreate` to false on migration. This way containers will not be recereated on dappmanager initialziation
> set compose up flag `forceRecreate` to false on migration

- packages/stakers/src/stakerComponent.ts
In the method `setStakerPkgConfig` we check if there are user settings to apply. Only recreate the package containers in case that there are any user settings that have been modified
> Only recreate on modified user settings

- packages/dappmanager/src/calls/packageInstall.ts
Exit the function `ensureNimbusConnection` if the DNP name does not correspond to a Nimbus package
> Return if not nimbus

- .github/workflows/main.yml
Skip int test for release. Rn the integration tests require a deep work of refactoring. Integration tests are failling and block releases, skip as for now untile fix
> Skip int test for release

- packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
- packages/installer/src/calls/packageInstall.ts
- packages/installer/src/installer/checkInstallRequirements.ts
- packages/installer/src/installer/index.ts
- packages/schemas/test/unit/validateSchema.test.ts
Ensure requirements in `packageInstall` and not only on `fetchDnpRequest`.
This will affect mainly auto updates as long as the install from the dappstore is already tracked with the compatible data
> ensure requirements in `packageInstall` and not only on `fetchDnpRequest`

- packages/schemas/src/params.ts
Add tailscale to whitelist of using docker bind mount volumes.
> Add tailscale to whitelist of using docker bind mount volumes

- packages/dockerCompose/src/editor.ts
- packages/dockerCompose/test/unit/composeDeleteDns.test.ts
The current `edit()` method merges the original service object with the partial updates returned by `serviceEditor(service)`. Merging { ...service, ...updatedFields } doesn't remove properties from service unless they are explicitly overwritten. Properties that aren't included in updatedFields remain in the merged object.
```
private edit(serviceEditor: (service: ComposeService) => Partial<ComposeService>): void {
const service = this.parent.compose.services[this.serviceName];
this.parent.compose.services[this.serviceName] = {
...service,
...serviceEditor(service)
};
}
```
This is why this implementation of removeDns() doesnt work
```
removeDns(): void {
this.edit((service) => {
if (!service.dns) return service;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const { dns, …
```
> add deletedns unit test

- packages/stakers/src/stakerComponent.ts
Implement nimbus checker to bypass `isMatch` when changin service name of a published package
> Implement nimbus checker

- packages/admin-ui/server-mock/index.ts
- packages/dappmanager/src/api/routes/env.ts
- packages/dappmanager/src/api/routes/envGet.ts
- packages/dappmanager/src/api/routes/index.ts
- packages/dappmanager/src/api/startHttpApi.ts
implement get env endpoint: `GET http://my.dappnode/env/mev-boost.dnp.dappnode.eth?envName=RELAYS`
> implement get env endpoint

- packages/stakers/src/consensus.ts
- packages/stakers/src/execution.ts
- packages/stakers/src/mevBoost.ts
- packages/stakers/src/signer.ts
- packages/stakers/src/stakerComponent.ts
Remove fullnode alias from dncore network when unsetting a staker pkg
> Remove fullnode alias from dncore network

- packages/stakers/src/consensus.ts
- packages/stakers/src/execution.ts
- packages/stakers/src/mevBoost.ts
- packages/stakers/src/signer.ts
- packages/stakers/src/stakerComponent.ts
Remove validator and beacon fullnode alises from the `dncore_network` when unsetting the staker configuration.
> Remove validator and beacon-chain fullnode alises

- packages/installer/src/installer/getInstallerPackageData.ts
Dont migrate userSettings of `geth.dnp.dappnode.eth` if servicename of previous userSettings is `geth`. Otherwise the previous `userSettings` will be erased.
> Dont migrate userSettings of `geth.dnp.dappnode.eth` if servicename of previous userSettings is `geth`

- packages/stakers/src/stakerComponent.ts
Make sure compose write is called after applying user settings, otherwise these new settings will be lost and the `compose up` action will not take effect since there are no changes detected in the compose file
> Make sure compose write is called after applying user settings

- packages/migrations/src/createStakerNetworkAndConnectStakerPkgs.ts
Ensure all promisses are settled when persisting staker configuration per network. Its a more robust solution to persist staking configuration when at least one of them can fail
> Ensure all promisses are settled when persisting staker configuration per network

- packages/admin-ui/src/dappnode_styles.scss
- packages/admin-ui/src/pages/packages/components/PackagesList.tsx
- packages/admin-ui/src/pages/packages/components/StateBadge/stateBadge.scss
- packages/admin-ui/src/pages/packages/components/packages.scss
Includes mobile view fixes for the `/packages` list tab:
- Hid "title-labels" as they were not displaying correctly due to reduced screen width.
- Smaller "status pill"
- Smaller icons
> Packages tab mobile fixes

- packages/admin-ui/src/pages/stakers/components/columns.scss
- packages/admin-ui/src/pages/stakers/components/columns/MevBoost.tsx
Updated the MevBoost table style and hid the OFAC link in mobile view in `/stakers`.
> Mev Boost table style updated

- packages/admin-ui/src/pages/packages/components/Info/ContainerList.tsx
- packages/admin-ui/src/pages/packages/components/Info/VolumesList.tsx
- packages/admin-ui/src/pages/packages/components/Info/containerList.scss
- packages/admin-ui/src/pages/packages/components/Info/volumesList.scss
Hid "title-labels" in `/package/info` in mobile view as they were not displaying correctly due to reduced screen width.
> Hide title labels in `/package/info` mobile view

- packages/admin-ui/src/components/topbar/dropdownMenus/dropdown.scss
Fixing the Topbar dropdowns in mobile view, reducing excessive width for better usability.
> Topbar's dropdowns mobile fix

- packages/admin-ui/src/pages/dashboard/components/PackageUpdates.tsx
- packages/admin-ui/src/pages/dashboard/components/dashboard.scss
Improved the `PackageUpdates` cards in `/dashboard` by placing all upstream versions inside a collapsable section for better readability. Also included fixes for mobile responsiveness.
> Collapsable `PackageUpdatesCards`

- packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
- packages/admin-ui/src/pages/stakers/components/stakers.scss
Since network descriptions are long and can take up most of the screen in mobile view, they are now hidden on mobile. However, they should be reviewed and rewritten if necessary.
> Hidden network descriptions on mobile view

- packages/dappmanager/src/api/routes/packageManifest.ts
- packages/installer/src/dappnodeInstaller.ts
- packages/installer/test/unit/release/findEntries.test.ts
- packages/toolkit/src/repository/repository.ts
- packages/types/src/index.ts
- packages/types/src/manifest.ts
- packages/types/src/notifications.ts
- packages/types/src/pkg.ts
- packages/types/src/releaseFiles.ts
Implement new release file notifications.yaml:
- Add file as release file
- Add types for the new release file
> Implement new release file notifications.yaml

- packages/admin-ui/src/components/sidebar/navbarItems.ts
- packages/admin-ui/src/pages/index.ts
- packages/admin-ui/src/pages/notifications/NotificationsRoot.tsx
- packages/admin-ui/src/pages/notifications/data.tsx
- packages/admin-ui/src/pages/notifications/index.ts
- packages/admin-ui/src/pages/notifications/tabs/InstallNotifications/InstallNotifications.tsx
- packages/admin-ui/src/pages/notifications/tabs/InstallNotifications/installNotifications.scss
This PR includes:
- root Notifications tab to support subpaths in upcoming PRs.
- check for the Notifications package. If the package is not installed, the user is redirected to the Installer to install it (implemented, but won't work as expected until `notifications.dnp.dappnode.eth` is published).
> Implement Root notifications tab

- packages/dappmanager/src/calls/gatusConfig.ts
Fixing notifications package's urls. 
`fetch()` expects a valid URL, and `new URL(path, base)` treats path as invalid if this starts with `:`
> Fix `gatusConfig` urls

- packages/schemas/package.json
- packages/schemas/src/ajv.ts
- packages/schemas/src/index.ts
- packages/schemas/src/schemas/notifications.schema.json
- packages/schemas/src/utils.ts
- packages/schemas/src/validateNotificationsSchema.ts
- packages/schemas/test/unit/validateSchema.test.ts
- packages/types/src/routes.ts
- yarn.lock
Implement notifications file validation
> Implement notifications file validation

- packages/admin-ui/src/__mock-backend__/index.ts
- packages/dappmanager/src/calls/notifications.ts
- packages/notifications/src/index.ts
- packages/notifications/src/manifest.ts
- packages/types/src/routes.ts
Return `isCore` to determine manifest path from `getEndpoints`
> Return `isCore` to determine manifest path

- packages/notifications/src/manifest.ts
Ensures `notificationsEndpoints[pkg.dnpName]` is initialized before assigning properties in `getNotifications` method
> `getNotifications` method fix

- packages/admin-ui/src/components/Slider.tsx
- packages/admin-ui/src/components/slider.scss
- packages/admin-ui/src/pages/notifications/NotificationsRoot.tsx
- packages/admin-ui/src/pages/notifications/data.ts
- packages/admin-ui/src/pages/notifications/tabs/Settings/CustomEndpointItem.tsx
- packages/admin-ui/src/pages/notifications/tabs/Settings/EndpointItem.tsx
- packages/admin-ui/src/pages/notifications/tabs/Settings/GatusEndpointItem.tsx
- packages/admin-ui/src/pages/notifications/tabs/Settings/ManagePackageNotifications.tsx
- packages/admin-ui/src/pages/notifications/tabs/Settings/Settings.tsx
- packages/admin-ui/src/pages/notifications/tabs/Settings/settings.scss
Implementing `Settings` notifications subtab. Supports gatus and custom endpoints.
> Add  `notifications/settings` subpath

- packages/notifications/src/manifest.ts
Ensures `notificationsEndpoints[pkg.dnpName]` is initialized before assigning properties in `getNotifications` method
> Initialize endpoints set by pkg

- packages/admin-ui/src/components/slider.scss
- packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
- packages/admin-ui/src/pages/installer/components/Steps/Notifications.tsx
- packages/admin-ui/src/pages/notifications/NotificationsRoot.tsx
- packages/admin-ui/src/pages/notifications/tabs/Settings/InstallerEndpointsList.tsx
- packages/admin-ui/src/pages/notifications/tabs/Settings/settings.scss
- packages/admin-ui/src/params.ts
Implementing the "Notifications" step in the installer to configure package notifications during installation.
> Notifications step in installer

- packages/admin-ui/src/pages/notifications/tabs/Settings/ManagePackageNotifications.tsx
Prevent unnecessary calls to `api.notificationsUpdateEndpoints` by tracking whether the state has been modified by the user. Otherwise, it was triggered when rendering the component.
Additionally, update the state when the prop value changes.
> Prevent endpoints autoupdate

- packages/migrations/src/createStakerNetworkAndConnectStakerPkgs.ts
Removed unnecessary await calls to ensure all promises run concurrently in `Promise.allSettled`
> fix createStakerNetwork

- packages/admin-ui/src/__mock-backend__/index.ts
- packages/admin-ui/src/pages/notifications/tabs/Settings/Settings.tsx
- packages/daemons/src/autoUpdates/sendUpdateNotification.ts
- packages/dappmanager/src/calls/index.ts
- packages/dappmanager/src/calls/notifications.ts
- packages/installer/src/installer/getInstallerPackageData.ts
- packages/notifications/src/index.ts
- packages/notifications/src/manifest.ts
- packages/types/src/routes.ts
Persist user settings in notifications when a package update event happens
> Persist user settings in notifications

- packages/admin-ui/src/__mock-backend__/index.ts
- packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
- packages/dappmanager/src/calls/index.ts
- packages/dappmanager/src/calls/notifications.ts
- packages/types/src/routes.ts
Persist user's notifications settings on installer if "new manifest" endpoints' names match
> Merge endpoints config on installer

- packages/admin-ui/src/__mock-backend__/stakerConfig.ts
- packages/admin-ui/src/pages/stakers/components/StakerNetwork.tsx
- packages/dappmanager/src/calls/stakerConfig.ts
- packages/types/src/routes.ts
Set stakerConfigGet argument as object. This will fix the allowance of calling the endpoint when running dappmanager with env `TEST=true` as follows:
```bash
curl -X POST http://172.33.1.7:7000/stakerConfigGet \
-H "Content-Type: application/json" \
-d '{"network": "mainnet"}'
```
> Set stakerConfigGet argument as object

- packages/admin-ui/src/__mock-backend__/index.ts
- packages/admin-ui/src/components/topbar/dropdownMenus/Notifications.tsx
- packages/dappmanager/src/calls/index.ts
- packages/dappmanager/src/calls/notifications.ts
- packages/notifications/src/api.ts
- packages/notifications/src/index.ts
- packages/types/src/routes.ts
Track number of new notifcations to display a blue dot in Topbar's notifications icon
> "Blue dot" on Notifications

- packages/admin-ui/src/components/topbar/TopBar.tsx
- packages/admin-ui/src/components/topbar/topbar.scss
- packages/admin-ui/src/light_dark.scss
Updating the background color of sidebar items on hover in dark mode to a darker one for improved readability and color consistency. Also, remove the 'BETA' label from the dark mode theme toggler
> Sidebar dark style fix

- packages/admin-ui/src/pages/dashboard/components/PackageUpdates.tsx
Apply the same card style as the other `/dashboard` cards when no package updates are found
> Package updates card style

- packages/admin-ui/src/pages/installer/components/InstallDnpView.tsx
- packages/admin-ui/src/pages/notifications/NotificationsRoot.tsx
- packages/admin-ui/src/pages/notifications/tabs/InstallNotifications/InstallNotifications.tsx
- packages/admin-ui/src/pages/notifications/tabs/Settings/Settings.tsx
- packages/admin-ui/src/params.ts
- packages/dappmanager/src/calls/packageStartStop.ts
- packages/params/src/params.ts
If the general notifications switch is toggled, now it starts / stops the notifications package. Also, before disabling the switch a modal pops up alerting the user about its consecuences.
> Notifications general switch

- packages/admin-ui/src/components/welcome/BottomButtons.tsx
- packages/admin-ui/src/components/welcome/features/EnableNotifications.tsx
handling notifications pkg not installed edge cases
> Improve notifications onboarding

- packages/admin-ui/src/components/topbar/dropdownMenus/Notifications.tsx
The blue dot indicating new notifications did not disappear after a minute when the notification count dropped to zero
> Blue dot bell fix

- packages/daemons/src/dockerNetworkConfigs/index.ts
- packages/db/src/updatePkgsWithGlobalEnvs.ts
Skip set glob env value if both compose env and glob env are nullish. i.e
- glob env is empty string
- compose env is bool
> Skip set glob env value if both compose env and glob env are nullish

- packages/dockerCompose/src/userSettings.ts
- packages/dockerCompose/test/unit/userSettings.test.ts
Error reported from users
```bash
Command failed: docker compose -f /usr/src/app/DNCORE/docker-compose-bind.yml config <&- validating /usr/src/app/DNCORE/docker-compose-bind.yml: services.bind.dnp.dappnode.eth.networks.dncore_network.ipv4_address must be a string
```
The function `applyUserSettings` merges both network configuration. If IP is defined then the result when merging more than 1 network configuration with IP defined will result into an array of strings with both IPs, and thats an invalid format for docker compose
> Fix bind IP array format

- packages/admin-ui/src/hooks/PWA/useHandleSubscription.ts
IOS devices does not support Notification API if the PWA has not been installed:
- Only call the Notification API if the app is in standalone mode
- catch error
> Call notification API only if PWA

- packages/installer/src/installer/getInstallerPackageData.ts
Fix setting default notifications (from `notifications.yaml`) if no notifications user settings provided.
Fixes bug when installing a package without the installer. i.e using stakers UI
> Fix: set default notifications if not notifications user settings provided

- packages/daemons/src/dockerNetworkConfigs/connectPkgContainers.ts
- packages/daemons/src/dockerNetworkConfigs/index.ts
- packages/params/src/params.ts
Set dappmanager IP 172.33.1.7 in `dncore_network`.
Set bind IP 172.33.1.2 in `dncore_network` and bind IP 10.20.0.2 in `dnprivate_network`
Thsi approach should ensure dappmanager container to always start without IP collision (the `dncore_network` subnet is big enough) and rely on dappmanager to ensure bind starts with proper IP
> Set dappmanager IP only in `dncore_network`

- packages/daemons/src/dockerNetworkConfigs/index.ts
Iterate first over the `dnprivate_network` and then over the `dncore_network` to avoid raising IP collision errors when starting containers.
> Switch docker networks order in daemon

- packages/admin-ui/src/__mock-backend__/index.ts
- packages/admin-ui/src/hooks/useBackupNode.ts
- packages/admin-ui/src/pages/premium/components/BackupNode.tsx
- packages/admin-ui/src/pages/premium/components/backupNode.scss
- packages/dappmanager/src/calls/validatorsFilterActive.ts
- packages/types/src/routes.ts
Now a warning tooltip is displayed explaining that all imported keystores are treated as "active validators" for the validator limit count if the request to the beacon API fails
> Beacon api error validators

- packages/admin-ui/src/components/SectionNavigator.tsx
Updating `SectionNavigator` component so it also catches sub-nested child routes. This fixes the VPN nested sub-routes not rendering bug.
> fix Nested sub-routing
